-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity SubbandRealtimeTopQ610Ip_p_anonymous_namespace_RunRealtimeGSUCellSharedQ610 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    p_read : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read1 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read2 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read3 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read4 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read5 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read6 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read7 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read8 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read9 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read10 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read11 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read12 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read13 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read14 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read15 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read16 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read17 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read18 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read19 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read20 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read21 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read22 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read23 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read24 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read25 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read26 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read27 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read28 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read29 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read30 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read31 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read32 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read33 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read34 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read35 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read36 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read37 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read38 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read39 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read40 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read41 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read42 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read43 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read44 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read45 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read46 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read47 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read48 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read49 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read50 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read51 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read52 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read53 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read54 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read55 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read56 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read57 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read58 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read59 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read60 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read61 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read62 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read63 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read64 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read65 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read66 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read67 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read68 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read69 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read70 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read71 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read72 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read73 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read74 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read75 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read76 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read77 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read78 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read79 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read80 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read81 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read82 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read83 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read84 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read85 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read86 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read87 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read88 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read89 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read90 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read91 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read92 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read93 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read94 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read95 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read96 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read97 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read98 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read99 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read100 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read101 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read102 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read103 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read104 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read105 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read106 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read107 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read108 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read109 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read110 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read111 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read112 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read113 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read114 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read115 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read116 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read117 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read118 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read119 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read120 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read121 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read122 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read123 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read124 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read125 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read126 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read127 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read128 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read129 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read130 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read131 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read132 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read133 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read134 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read135 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read136 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read137 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read138 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read139 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read140 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read141 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read142 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read143 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read144 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read145 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read146 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read147 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read148 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read149 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read150 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read151 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read152 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read153 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read154 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read155 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read156 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read157 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read158 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read159 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read160 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read161 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read162 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read163 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read164 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read165 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read166 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read167 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read168 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read169 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read170 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read171 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read172 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read173 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read174 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read175 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read176 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read177 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read178 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read179 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read180 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read181 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read182 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read183 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read184 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read185 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read186 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read187 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read188 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read189 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read190 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read191 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read192 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read193 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read194 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read195 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read196 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read197 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read198 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read199 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read200 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read201 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read202 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read203 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read204 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read205 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read206 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read207 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read208 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read209 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read210 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read211 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read212 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read213 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read214 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read215 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read216 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read217 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read218 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read219 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read220 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read221 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read222 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read223 : IN STD_LOGIC_VECTOR (15 downto 0);
    weight_ih_0_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    weight_ih_0_ce0 : OUT STD_LOGIC;
    weight_ih_0_q0 : IN STD_LOGIC_VECTOR (511 downto 0);
    weight_ih_1_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    weight_ih_1_ce0 : OUT STD_LOGIC;
    weight_ih_1_q0 : IN STD_LOGIC_VECTOR (511 downto 0);
    weight_hh_0_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    weight_hh_0_ce0 : OUT STD_LOGIC;
    weight_hh_0_q0 : IN STD_LOGIC_VECTOR (511 downto 0);
    weight_hh_1_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    weight_hh_1_ce0 : OUT STD_LOGIC;
    weight_hh_1_q0 : IN STD_LOGIC_VECTOR (511 downto 0);
    bias_ih_0_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    bias_ih_0_ce0 : OUT STD_LOGIC;
    bias_ih_0_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    bias_ih_0_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    bias_ih_0_ce1 : OUT STD_LOGIC;
    bias_ih_0_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    bias_ih_1_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    bias_ih_1_ce0 : OUT STD_LOGIC;
    bias_ih_1_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    bias_ih_1_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    bias_ih_1_ce1 : OUT STD_LOGIC;
    bias_ih_1_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    bn_mul_0_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    bn_mul_0_ce0 : OUT STD_LOGIC;
    bn_mul_0_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    bn_mul_1_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    bn_mul_1_ce0 : OUT STD_LOGIC;
    bn_mul_1_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    bn_add_0_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    bn_add_0_ce0 : OUT STD_LOGIC;
    bn_add_0_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    bn_add_1_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    bn_add_1_ce0 : OUT STD_LOGIC;
    bn_add_1_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    hx_state_q610_0_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    hx_state_q610_0_ce0 : OUT STD_LOGIC;
    hx_state_q610_0_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    hx_state_q610_0_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    hx_state_q610_0_ce1 : OUT STD_LOGIC;
    hx_state_q610_0_we1 : OUT STD_LOGIC;
    hx_state_q610_0_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    hx_state_q610_0_offset : IN STD_LOGIC_VECTOR (31 downto 0);
    hx_state_q610_1_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    hx_state_q610_1_ce0 : OUT STD_LOGIC;
    hx_state_q610_1_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    hx_state_q610_1_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    hx_state_q610_1_ce1 : OUT STD_LOGIC;
    hx_state_q610_1_we1 : OUT STD_LOGIC;
    hx_state_q610_1_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    hx_state_q610_1_offset : IN STD_LOGIC_VECTOR (31 downto 0);
    cx_state_q610_0_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    cx_state_q610_0_ce0 : OUT STD_LOGIC;
    cx_state_q610_0_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    cx_state_q610_0_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    cx_state_q610_0_ce1 : OUT STD_LOGIC;
    cx_state_q610_0_we1 : OUT STD_LOGIC;
    cx_state_q610_0_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    cx_state_q610_0_offset : IN STD_LOGIC_VECTOR (31 downto 0);
    cx_state_q610_1_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    cx_state_q610_1_ce0 : OUT STD_LOGIC;
    cx_state_q610_1_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    cx_state_q610_1_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    cx_state_q610_1_ce1 : OUT STD_LOGIC;
    cx_state_q610_1_we1 : OUT STD_LOGIC;
    cx_state_q610_1_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    cx_state_q610_1_offset : IN STD_LOGIC_VECTOR (31 downto 0);
    output_hy_q610_0_address1 : OUT STD_LOGIC_VECTOR (11 downto 0);
    output_hy_q610_0_ce1 : OUT STD_LOGIC;
    output_hy_q610_0_we1 : OUT STD_LOGIC;
    output_hy_q610_0_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    output_hy_q610_0_offset : IN STD_LOGIC_VECTOR (31 downto 0);
    output_hy_q610_0_offset1 : IN STD_LOGIC_VECTOR (31 downto 0);
    output_hy_q610_1_address1 : OUT STD_LOGIC_VECTOR (11 downto 0);
    output_hy_q610_1_ce1 : OUT STD_LOGIC;
    output_hy_q610_1_we1 : OUT STD_LOGIC;
    output_hy_q610_1_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    output_hy_q610_1_offset : IN STD_LOGIC_VECTOR (31 downto 0);
    output_hy_q610_1_offset2 : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of SubbandRealtimeTopQ610Ip_p_anonymous_namespace_RunRealtimeGSUCellSharedQ610 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal empty_fu_2402_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal empty_reg_3562 : STD_LOGIC_VECTOR (2 downto 0);
    signal empty_618_fu_2407_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal empty_618_reg_3567 : STD_LOGIC_VECTOR (1 downto 0);
    signal empty_619_fu_2412_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal empty_619_reg_3572 : STD_LOGIC_VECTOR (2 downto 0);
    signal empty_620_fu_2417_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal empty_620_reg_3577 : STD_LOGIC_VECTOR (1 downto 0);
    signal empty_621_fu_2422_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal empty_621_reg_3582 : STD_LOGIC_VECTOR (3 downto 0);
    signal empty_622_fu_2427_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal empty_622_reg_3587 : STD_LOGIC_VECTOR (3 downto 0);
    signal empty_623_fu_2432_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal empty_623_reg_3592 : STD_LOGIC_VECTOR (3 downto 0);
    signal empty_624_fu_2437_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal empty_624_reg_3597 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_ap_start : STD_LOGIC;
    signal grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_ap_done : STD_LOGIC;
    signal grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_ap_idle : STD_LOGIC;
    signal grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_ap_ready : STD_LOGIC;
    signal grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_weight_ih_0_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_weight_ih_0_ce0 : STD_LOGIC;
    signal grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_weight_ih_1_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_weight_ih_1_ce0 : STD_LOGIC;
    signal grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_weight_hh_0_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_weight_hh_0_ce0 : STD_LOGIC;
    signal grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_weight_hh_1_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_weight_hh_1_ce0 : STD_LOGIC;
    signal grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bias_ih_0_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bias_ih_0_ce0 : STD_LOGIC;
    signal grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bias_ih_0_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bias_ih_0_ce1 : STD_LOGIC;
    signal grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bias_ih_1_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bias_ih_1_ce0 : STD_LOGIC;
    signal grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bias_ih_1_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bias_ih_1_ce1 : STD_LOGIC;
    signal grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bn_mul_0_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bn_mul_0_ce0 : STD_LOGIC;
    signal grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bn_mul_1_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bn_mul_1_ce0 : STD_LOGIC;
    signal grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bn_add_0_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bn_add_0_ce0 : STD_LOGIC;
    signal grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bn_add_1_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bn_add_1_ce0 : STD_LOGIC;
    signal grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_hx_state_q610_0_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_hx_state_q610_0_ce0 : STD_LOGIC;
    signal grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_hx_state_q610_0_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_hx_state_q610_0_ce1 : STD_LOGIC;
    signal grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_hx_state_q610_0_we1 : STD_LOGIC;
    signal grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_hx_state_q610_0_d1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_hx_state_q610_1_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_hx_state_q610_1_ce0 : STD_LOGIC;
    signal grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_hx_state_q610_1_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_hx_state_q610_1_ce1 : STD_LOGIC;
    signal grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_hx_state_q610_1_we1 : STD_LOGIC;
    signal grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_hx_state_q610_1_d1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_cx_state_q610_0_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_cx_state_q610_0_ce0 : STD_LOGIC;
    signal grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_cx_state_q610_0_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_cx_state_q610_0_ce1 : STD_LOGIC;
    signal grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_cx_state_q610_0_we1 : STD_LOGIC;
    signal grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_cx_state_q610_0_d1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_cx_state_q610_1_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_cx_state_q610_1_ce0 : STD_LOGIC;
    signal grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_cx_state_q610_1_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_cx_state_q610_1_ce1 : STD_LOGIC;
    signal grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_cx_state_q610_1_we1 : STD_LOGIC;
    signal grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_cx_state_q610_1_d1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_output_hy_q610_0_address1 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_output_hy_q610_0_ce1 : STD_LOGIC;
    signal grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_output_hy_q610_0_we1 : STD_LOGIC;
    signal grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_output_hy_q610_0_d1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_output_hy_q610_1_address1 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_output_hy_q610_1_ce1 : STD_LOGIC;
    signal grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_output_hy_q610_1_we1 : STD_LOGIC;
    signal grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_output_hy_q610_1_d1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component SubbandRealtimeTopQ610Ip_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        input_ptr_0_val1 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_1_val2 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_2_val3 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_3_val4 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_4_val5 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_5_val6 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_6_val7 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_7_val8 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_8_val9 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_9_val10 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_10_val11 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_11_val12 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_12_val13 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_13_val14 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_14_val15 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_15_val16 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_16_val17 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_17_val18 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_18_val19 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_19_val20 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_20_val21 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_21_val22 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_22_val23 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_23_val24 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_24_val25 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_25_val26 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_26_val27 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_27_val28 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_28_val29 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_29_val30 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_30_val31 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_31_val32 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_32_val33 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_33_val34 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_34_val35 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_35_val36 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_36_val37 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_37_val38 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_38_val39 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_39_val40 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_40_val41 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_41_val42 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_42_val43 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_43_val44 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_44_val45 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_45_val46 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_46_val47 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_47_val48 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_48_val49 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_49_val50 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_50_val51 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_51_val52 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_52_val53 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_53_val54 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_54_val55 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_55_val56 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_56_val57 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_57_val58 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_58_val59 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_59_val60 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_60_val61 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_61_val62 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_62_val63 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_63_val64 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_64_val65 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_65_val66 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_66_val67 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_67_val68 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_68_val69 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_69_val70 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_70_val71 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_71_val72 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_72_val73 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_73_val74 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_74_val75 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_75_val76 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_76_val77 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_77_val78 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_78_val79 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_79_val80 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_80_val81 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_81_val82 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_82_val83 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_83_val84 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_84_val85 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_85_val86 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_86_val87 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_87_val88 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_88_val89 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_89_val90 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_90_val91 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_91_val92 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_92_val93 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_93_val94 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_94_val95 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_95_val96 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_96_val97 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_97_val98 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_98_val99 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_99_val100 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_100_val101 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_101_val102 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_102_val103 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_103_val104 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_104_val105 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_105_val106 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_106_val107 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_107_val108 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_108_val109 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_109_val110 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_110_val111 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_111_val112 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_112_val113 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_113_val114 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_114_val115 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_115_val116 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_116_val117 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_117_val118 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_118_val119 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_119_val120 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_120_val121 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_121_val122 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_122_val123 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_123_val124 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_124_val125 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_125_val126 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_126_val127 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_127_val128 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_128_val129 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_129_val130 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_130_val131 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_131_val132 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_132_val133 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_133_val134 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_134_val135 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_135_val136 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_136_val137 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_137_val138 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_138_val139 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_139_val140 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_140_val141 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_141_val142 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_142_val143 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_143_val144 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_144_val145 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_145_val146 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_146_val147 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_147_val148 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_148_val149 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_149_val150 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_150_val151 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_151_val152 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_152_val153 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_153_val154 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_154_val155 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_155_val156 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_156_val157 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_157_val158 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_158_val159 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_159_val160 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_160_val161 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_161_val162 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_162_val163 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_163_val164 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_164_val165 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_165_val166 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_166_val167 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_167_val168 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_168_val169 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_169_val170 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_170_val171 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_171_val172 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_172_val173 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_173_val174 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_174_val175 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_175_val176 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_176_val177 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_177_val178 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_178_val179 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_179_val180 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_180_val181 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_181_val182 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_182_val183 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_183_val184 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_184_val185 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_185_val186 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_186_val187 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_187_val188 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_188_val189 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_189_val190 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_190_val191 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_191_val192 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_192_val193 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_193_val194 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_194_val195 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_195_val196 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_196_val197 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_197_val198 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_198_val199 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_199_val200 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_200_val201 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_201_val202 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_202_val203 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_203_val204 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_204_val205 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_205_val206 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_206_val207 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_207_val208 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_208_val209 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_209_val210 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_210_val211 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_211_val212 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_212_val213 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_213_val214 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_214_val215 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_215_val216 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_216_val217 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_217_val218 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_218_val219 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_219_val220 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_220_val221 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_221_val222 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_222_val223 : IN STD_LOGIC_VECTOR (15 downto 0);
        input_ptr_223_val224 : IN STD_LOGIC_VECTOR (15 downto 0);
        weight_ih_0_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        weight_ih_0_ce0 : OUT STD_LOGIC;
        weight_ih_0_q0 : IN STD_LOGIC_VECTOR (511 downto 0);
        weight_ih_1_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        weight_ih_1_ce0 : OUT STD_LOGIC;
        weight_ih_1_q0 : IN STD_LOGIC_VECTOR (511 downto 0);
        weight_hh_0_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        weight_hh_0_ce0 : OUT STD_LOGIC;
        weight_hh_0_q0 : IN STD_LOGIC_VECTOR (511 downto 0);
        weight_hh_1_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        weight_hh_1_ce0 : OUT STD_LOGIC;
        weight_hh_1_q0 : IN STD_LOGIC_VECTOR (511 downto 0);
        bias_ih_0_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        bias_ih_0_ce0 : OUT STD_LOGIC;
        bias_ih_0_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        bias_ih_0_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        bias_ih_0_ce1 : OUT STD_LOGIC;
        bias_ih_0_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
        bias_ih_1_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        bias_ih_1_ce0 : OUT STD_LOGIC;
        bias_ih_1_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        bias_ih_1_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        bias_ih_1_ce1 : OUT STD_LOGIC;
        bias_ih_1_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
        bn_mul_0_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        bn_mul_0_ce0 : OUT STD_LOGIC;
        bn_mul_0_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        bn_mul_1_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        bn_mul_1_ce0 : OUT STD_LOGIC;
        bn_mul_1_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        bn_add_0_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        bn_add_0_ce0 : OUT STD_LOGIC;
        bn_add_0_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        bn_add_1_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        bn_add_1_ce0 : OUT STD_LOGIC;
        bn_add_1_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        hx_state_q610_0_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
        hx_state_q610_0_ce0 : OUT STD_LOGIC;
        hx_state_q610_0_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        hx_state_q610_0_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
        hx_state_q610_0_ce1 : OUT STD_LOGIC;
        hx_state_q610_0_we1 : OUT STD_LOGIC;
        hx_state_q610_0_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
        hx_state_q610_0_offset : IN STD_LOGIC_VECTOR (3 downto 0);
        hx_state_q610_1_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
        hx_state_q610_1_ce0 : OUT STD_LOGIC;
        hx_state_q610_1_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        hx_state_q610_1_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
        hx_state_q610_1_ce1 : OUT STD_LOGIC;
        hx_state_q610_1_we1 : OUT STD_LOGIC;
        hx_state_q610_1_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
        hx_state_q610_1_offset : IN STD_LOGIC_VECTOR (3 downto 0);
        cx_state_q610_0_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
        cx_state_q610_0_ce0 : OUT STD_LOGIC;
        cx_state_q610_0_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        cx_state_q610_0_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
        cx_state_q610_0_ce1 : OUT STD_LOGIC;
        cx_state_q610_0_we1 : OUT STD_LOGIC;
        cx_state_q610_0_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
        cx_state_q610_0_offset : IN STD_LOGIC_VECTOR (3 downto 0);
        cx_state_q610_1_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
        cx_state_q610_1_ce0 : OUT STD_LOGIC;
        cx_state_q610_1_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        cx_state_q610_1_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
        cx_state_q610_1_ce1 : OUT STD_LOGIC;
        cx_state_q610_1_we1 : OUT STD_LOGIC;
        cx_state_q610_1_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
        cx_state_q610_1_offset : IN STD_LOGIC_VECTOR (3 downto 0);
        output_hy_q610_0_address1 : OUT STD_LOGIC_VECTOR (11 downto 0);
        output_hy_q610_0_ce1 : OUT STD_LOGIC;
        output_hy_q610_0_we1 : OUT STD_LOGIC;
        output_hy_q610_0_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
        output_hy_q610_0_offset : IN STD_LOGIC_VECTOR (1 downto 0);
        output_hy_q610_0_offset1 : IN STD_LOGIC_VECTOR (2 downto 0);
        output_hy_q610_1_address1 : OUT STD_LOGIC_VECTOR (11 downto 0);
        output_hy_q610_1_ce1 : OUT STD_LOGIC;
        output_hy_q610_1_we1 : OUT STD_LOGIC;
        output_hy_q610_1_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
        output_hy_q610_1_offset : IN STD_LOGIC_VECTOR (1 downto 0);
        output_hy_q610_1_offset2 : IN STD_LOGIC_VECTOR (2 downto 0) );
    end component;



begin
    grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906 : component SubbandRealtimeTopQ610Ip_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_ap_start,
        ap_done => grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_ap_done,
        ap_idle => grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_ap_idle,
        ap_ready => grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_ap_ready,
        input_ptr_0_val1 => p_read,
        input_ptr_1_val2 => p_read1,
        input_ptr_2_val3 => p_read2,
        input_ptr_3_val4 => p_read3,
        input_ptr_4_val5 => p_read4,
        input_ptr_5_val6 => p_read5,
        input_ptr_6_val7 => p_read6,
        input_ptr_7_val8 => p_read7,
        input_ptr_8_val9 => p_read8,
        input_ptr_9_val10 => p_read9,
        input_ptr_10_val11 => p_read10,
        input_ptr_11_val12 => p_read11,
        input_ptr_12_val13 => p_read12,
        input_ptr_13_val14 => p_read13,
        input_ptr_14_val15 => p_read14,
        input_ptr_15_val16 => p_read15,
        input_ptr_16_val17 => p_read16,
        input_ptr_17_val18 => p_read17,
        input_ptr_18_val19 => p_read18,
        input_ptr_19_val20 => p_read19,
        input_ptr_20_val21 => p_read20,
        input_ptr_21_val22 => p_read21,
        input_ptr_22_val23 => p_read22,
        input_ptr_23_val24 => p_read23,
        input_ptr_24_val25 => p_read24,
        input_ptr_25_val26 => p_read25,
        input_ptr_26_val27 => p_read26,
        input_ptr_27_val28 => p_read27,
        input_ptr_28_val29 => p_read28,
        input_ptr_29_val30 => p_read29,
        input_ptr_30_val31 => p_read30,
        input_ptr_31_val32 => p_read31,
        input_ptr_32_val33 => p_read32,
        input_ptr_33_val34 => p_read33,
        input_ptr_34_val35 => p_read34,
        input_ptr_35_val36 => p_read35,
        input_ptr_36_val37 => p_read36,
        input_ptr_37_val38 => p_read37,
        input_ptr_38_val39 => p_read38,
        input_ptr_39_val40 => p_read39,
        input_ptr_40_val41 => p_read40,
        input_ptr_41_val42 => p_read41,
        input_ptr_42_val43 => p_read42,
        input_ptr_43_val44 => p_read43,
        input_ptr_44_val45 => p_read44,
        input_ptr_45_val46 => p_read45,
        input_ptr_46_val47 => p_read46,
        input_ptr_47_val48 => p_read47,
        input_ptr_48_val49 => p_read48,
        input_ptr_49_val50 => p_read49,
        input_ptr_50_val51 => p_read50,
        input_ptr_51_val52 => p_read51,
        input_ptr_52_val53 => p_read52,
        input_ptr_53_val54 => p_read53,
        input_ptr_54_val55 => p_read54,
        input_ptr_55_val56 => p_read55,
        input_ptr_56_val57 => p_read56,
        input_ptr_57_val58 => p_read57,
        input_ptr_58_val59 => p_read58,
        input_ptr_59_val60 => p_read59,
        input_ptr_60_val61 => p_read60,
        input_ptr_61_val62 => p_read61,
        input_ptr_62_val63 => p_read62,
        input_ptr_63_val64 => p_read63,
        input_ptr_64_val65 => p_read64,
        input_ptr_65_val66 => p_read65,
        input_ptr_66_val67 => p_read66,
        input_ptr_67_val68 => p_read67,
        input_ptr_68_val69 => p_read68,
        input_ptr_69_val70 => p_read69,
        input_ptr_70_val71 => p_read70,
        input_ptr_71_val72 => p_read71,
        input_ptr_72_val73 => p_read72,
        input_ptr_73_val74 => p_read73,
        input_ptr_74_val75 => p_read74,
        input_ptr_75_val76 => p_read75,
        input_ptr_76_val77 => p_read76,
        input_ptr_77_val78 => p_read77,
        input_ptr_78_val79 => p_read78,
        input_ptr_79_val80 => p_read79,
        input_ptr_80_val81 => p_read80,
        input_ptr_81_val82 => p_read81,
        input_ptr_82_val83 => p_read82,
        input_ptr_83_val84 => p_read83,
        input_ptr_84_val85 => p_read84,
        input_ptr_85_val86 => p_read85,
        input_ptr_86_val87 => p_read86,
        input_ptr_87_val88 => p_read87,
        input_ptr_88_val89 => p_read88,
        input_ptr_89_val90 => p_read89,
        input_ptr_90_val91 => p_read90,
        input_ptr_91_val92 => p_read91,
        input_ptr_92_val93 => p_read92,
        input_ptr_93_val94 => p_read93,
        input_ptr_94_val95 => p_read94,
        input_ptr_95_val96 => p_read95,
        input_ptr_96_val97 => p_read96,
        input_ptr_97_val98 => p_read97,
        input_ptr_98_val99 => p_read98,
        input_ptr_99_val100 => p_read99,
        input_ptr_100_val101 => p_read100,
        input_ptr_101_val102 => p_read101,
        input_ptr_102_val103 => p_read102,
        input_ptr_103_val104 => p_read103,
        input_ptr_104_val105 => p_read104,
        input_ptr_105_val106 => p_read105,
        input_ptr_106_val107 => p_read106,
        input_ptr_107_val108 => p_read107,
        input_ptr_108_val109 => p_read108,
        input_ptr_109_val110 => p_read109,
        input_ptr_110_val111 => p_read110,
        input_ptr_111_val112 => p_read111,
        input_ptr_112_val113 => p_read112,
        input_ptr_113_val114 => p_read113,
        input_ptr_114_val115 => p_read114,
        input_ptr_115_val116 => p_read115,
        input_ptr_116_val117 => p_read116,
        input_ptr_117_val118 => p_read117,
        input_ptr_118_val119 => p_read118,
        input_ptr_119_val120 => p_read119,
        input_ptr_120_val121 => p_read120,
        input_ptr_121_val122 => p_read121,
        input_ptr_122_val123 => p_read122,
        input_ptr_123_val124 => p_read123,
        input_ptr_124_val125 => p_read124,
        input_ptr_125_val126 => p_read125,
        input_ptr_126_val127 => p_read126,
        input_ptr_127_val128 => p_read127,
        input_ptr_128_val129 => p_read128,
        input_ptr_129_val130 => p_read129,
        input_ptr_130_val131 => p_read130,
        input_ptr_131_val132 => p_read131,
        input_ptr_132_val133 => p_read132,
        input_ptr_133_val134 => p_read133,
        input_ptr_134_val135 => p_read134,
        input_ptr_135_val136 => p_read135,
        input_ptr_136_val137 => p_read136,
        input_ptr_137_val138 => p_read137,
        input_ptr_138_val139 => p_read138,
        input_ptr_139_val140 => p_read139,
        input_ptr_140_val141 => p_read140,
        input_ptr_141_val142 => p_read141,
        input_ptr_142_val143 => p_read142,
        input_ptr_143_val144 => p_read143,
        input_ptr_144_val145 => p_read144,
        input_ptr_145_val146 => p_read145,
        input_ptr_146_val147 => p_read146,
        input_ptr_147_val148 => p_read147,
        input_ptr_148_val149 => p_read148,
        input_ptr_149_val150 => p_read149,
        input_ptr_150_val151 => p_read150,
        input_ptr_151_val152 => p_read151,
        input_ptr_152_val153 => p_read152,
        input_ptr_153_val154 => p_read153,
        input_ptr_154_val155 => p_read154,
        input_ptr_155_val156 => p_read155,
        input_ptr_156_val157 => p_read156,
        input_ptr_157_val158 => p_read157,
        input_ptr_158_val159 => p_read158,
        input_ptr_159_val160 => p_read159,
        input_ptr_160_val161 => p_read160,
        input_ptr_161_val162 => p_read161,
        input_ptr_162_val163 => p_read162,
        input_ptr_163_val164 => p_read163,
        input_ptr_164_val165 => p_read164,
        input_ptr_165_val166 => p_read165,
        input_ptr_166_val167 => p_read166,
        input_ptr_167_val168 => p_read167,
        input_ptr_168_val169 => p_read168,
        input_ptr_169_val170 => p_read169,
        input_ptr_170_val171 => p_read170,
        input_ptr_171_val172 => p_read171,
        input_ptr_172_val173 => p_read172,
        input_ptr_173_val174 => p_read173,
        input_ptr_174_val175 => p_read174,
        input_ptr_175_val176 => p_read175,
        input_ptr_176_val177 => p_read176,
        input_ptr_177_val178 => p_read177,
        input_ptr_178_val179 => p_read178,
        input_ptr_179_val180 => p_read179,
        input_ptr_180_val181 => p_read180,
        input_ptr_181_val182 => p_read181,
        input_ptr_182_val183 => p_read182,
        input_ptr_183_val184 => p_read183,
        input_ptr_184_val185 => p_read184,
        input_ptr_185_val186 => p_read185,
        input_ptr_186_val187 => p_read186,
        input_ptr_187_val188 => p_read187,
        input_ptr_188_val189 => p_read188,
        input_ptr_189_val190 => p_read189,
        input_ptr_190_val191 => p_read190,
        input_ptr_191_val192 => p_read191,
        input_ptr_192_val193 => p_read192,
        input_ptr_193_val194 => p_read193,
        input_ptr_194_val195 => p_read194,
        input_ptr_195_val196 => p_read195,
        input_ptr_196_val197 => p_read196,
        input_ptr_197_val198 => p_read197,
        input_ptr_198_val199 => p_read198,
        input_ptr_199_val200 => p_read199,
        input_ptr_200_val201 => p_read200,
        input_ptr_201_val202 => p_read201,
        input_ptr_202_val203 => p_read202,
        input_ptr_203_val204 => p_read203,
        input_ptr_204_val205 => p_read204,
        input_ptr_205_val206 => p_read205,
        input_ptr_206_val207 => p_read206,
        input_ptr_207_val208 => p_read207,
        input_ptr_208_val209 => p_read208,
        input_ptr_209_val210 => p_read209,
        input_ptr_210_val211 => p_read210,
        input_ptr_211_val212 => p_read211,
        input_ptr_212_val213 => p_read212,
        input_ptr_213_val214 => p_read213,
        input_ptr_214_val215 => p_read214,
        input_ptr_215_val216 => p_read215,
        input_ptr_216_val217 => p_read216,
        input_ptr_217_val218 => p_read217,
        input_ptr_218_val219 => p_read218,
        input_ptr_219_val220 => p_read219,
        input_ptr_220_val221 => p_read220,
        input_ptr_221_val222 => p_read221,
        input_ptr_222_val223 => p_read222,
        input_ptr_223_val224 => p_read223,
        weight_ih_0_address0 => grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_weight_ih_0_address0,
        weight_ih_0_ce0 => grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_weight_ih_0_ce0,
        weight_ih_0_q0 => weight_ih_0_q0,
        weight_ih_1_address0 => grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_weight_ih_1_address0,
        weight_ih_1_ce0 => grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_weight_ih_1_ce0,
        weight_ih_1_q0 => weight_ih_1_q0,
        weight_hh_0_address0 => grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_weight_hh_0_address0,
        weight_hh_0_ce0 => grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_weight_hh_0_ce0,
        weight_hh_0_q0 => weight_hh_0_q0,
        weight_hh_1_address0 => grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_weight_hh_1_address0,
        weight_hh_1_ce0 => grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_weight_hh_1_ce0,
        weight_hh_1_q0 => weight_hh_1_q0,
        bias_ih_0_address0 => grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bias_ih_0_address0,
        bias_ih_0_ce0 => grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bias_ih_0_ce0,
        bias_ih_0_q0 => bias_ih_0_q0,
        bias_ih_0_address1 => grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bias_ih_0_address1,
        bias_ih_0_ce1 => grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bias_ih_0_ce1,
        bias_ih_0_q1 => bias_ih_0_q1,
        bias_ih_1_address0 => grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bias_ih_1_address0,
        bias_ih_1_ce0 => grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bias_ih_1_ce0,
        bias_ih_1_q0 => bias_ih_1_q0,
        bias_ih_1_address1 => grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bias_ih_1_address1,
        bias_ih_1_ce1 => grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bias_ih_1_ce1,
        bias_ih_1_q1 => bias_ih_1_q1,
        bn_mul_0_address0 => grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bn_mul_0_address0,
        bn_mul_0_ce0 => grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bn_mul_0_ce0,
        bn_mul_0_q0 => bn_mul_0_q0,
        bn_mul_1_address0 => grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bn_mul_1_address0,
        bn_mul_1_ce0 => grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bn_mul_1_ce0,
        bn_mul_1_q0 => bn_mul_1_q0,
        bn_add_0_address0 => grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bn_add_0_address0,
        bn_add_0_ce0 => grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bn_add_0_ce0,
        bn_add_0_q0 => bn_add_0_q0,
        bn_add_1_address0 => grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bn_add_1_address0,
        bn_add_1_ce0 => grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bn_add_1_ce0,
        bn_add_1_q0 => bn_add_1_q0,
        hx_state_q610_0_address0 => grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_hx_state_q610_0_address0,
        hx_state_q610_0_ce0 => grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_hx_state_q610_0_ce0,
        hx_state_q610_0_q0 => hx_state_q610_0_q0,
        hx_state_q610_0_address1 => grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_hx_state_q610_0_address1,
        hx_state_q610_0_ce1 => grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_hx_state_q610_0_ce1,
        hx_state_q610_0_we1 => grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_hx_state_q610_0_we1,
        hx_state_q610_0_d1 => grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_hx_state_q610_0_d1,
        hx_state_q610_0_offset => empty_624_reg_3597,
        hx_state_q610_1_address0 => grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_hx_state_q610_1_address0,
        hx_state_q610_1_ce0 => grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_hx_state_q610_1_ce0,
        hx_state_q610_1_q0 => hx_state_q610_1_q0,
        hx_state_q610_1_address1 => grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_hx_state_q610_1_address1,
        hx_state_q610_1_ce1 => grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_hx_state_q610_1_ce1,
        hx_state_q610_1_we1 => grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_hx_state_q610_1_we1,
        hx_state_q610_1_d1 => grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_hx_state_q610_1_d1,
        hx_state_q610_1_offset => empty_623_reg_3592,
        cx_state_q610_0_address0 => grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_cx_state_q610_0_address0,
        cx_state_q610_0_ce0 => grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_cx_state_q610_0_ce0,
        cx_state_q610_0_q0 => cx_state_q610_0_q0,
        cx_state_q610_0_address1 => grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_cx_state_q610_0_address1,
        cx_state_q610_0_ce1 => grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_cx_state_q610_0_ce1,
        cx_state_q610_0_we1 => grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_cx_state_q610_0_we1,
        cx_state_q610_0_d1 => grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_cx_state_q610_0_d1,
        cx_state_q610_0_offset => empty_622_reg_3587,
        cx_state_q610_1_address0 => grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_cx_state_q610_1_address0,
        cx_state_q610_1_ce0 => grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_cx_state_q610_1_ce0,
        cx_state_q610_1_q0 => cx_state_q610_1_q0,
        cx_state_q610_1_address1 => grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_cx_state_q610_1_address1,
        cx_state_q610_1_ce1 => grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_cx_state_q610_1_ce1,
        cx_state_q610_1_we1 => grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_cx_state_q610_1_we1,
        cx_state_q610_1_d1 => grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_cx_state_q610_1_d1,
        cx_state_q610_1_offset => empty_621_reg_3582,
        output_hy_q610_0_address1 => grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_output_hy_q610_0_address1,
        output_hy_q610_0_ce1 => grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_output_hy_q610_0_ce1,
        output_hy_q610_0_we1 => grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_output_hy_q610_0_we1,
        output_hy_q610_0_d1 => grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_output_hy_q610_0_d1,
        output_hy_q610_0_offset => empty_620_reg_3577,
        output_hy_q610_0_offset1 => empty_619_reg_3572,
        output_hy_q610_1_address1 => grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_output_hy_q610_1_address1,
        output_hy_q610_1_ce1 => grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_output_hy_q610_1_ce1,
        output_hy_q610_1_we1 => grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_output_hy_q610_1_we1,
        output_hy_q610_1_d1 => grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_output_hy_q610_1_d1,
        output_hy_q610_1_offset => empty_618_reg_3567,
        output_hy_q610_1_offset2 => empty_reg_3562);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_ap_ready = ap_const_logic_1)) then 
                    grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                empty_618_reg_3567 <= empty_618_fu_2407_p1;
                empty_619_reg_3572 <= empty_619_fu_2412_p1;
                empty_620_reg_3577 <= empty_620_fu_2417_p1;
                empty_621_reg_3582 <= empty_621_fu_2422_p1;
                empty_622_reg_3587 <= empty_622_fu_2427_p1;
                empty_623_reg_3592 <= empty_623_fu_2432_p1;
                empty_624_reg_3597 <= empty_624_fu_2437_p1;
                empty_reg_3562 <= empty_fu_2402_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_ap_done, ap_CS_fsm_state2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_ap_done)
    begin
        if ((grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_ap_done, ap_CS_fsm_state2)
    begin
        if ((((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_ap_done, ap_CS_fsm_state2)
    begin
        if (((grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    bias_ih_0_address0 <= grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bias_ih_0_address0;
    bias_ih_0_address1 <= grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bias_ih_0_address1;
    bias_ih_0_ce0 <= grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bias_ih_0_ce0;
    bias_ih_0_ce1 <= grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bias_ih_0_ce1;
    bias_ih_1_address0 <= grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bias_ih_1_address0;
    bias_ih_1_address1 <= grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bias_ih_1_address1;
    bias_ih_1_ce0 <= grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bias_ih_1_ce0;
    bias_ih_1_ce1 <= grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bias_ih_1_ce1;
    bn_add_0_address0 <= grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bn_add_0_address0;
    bn_add_0_ce0 <= grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bn_add_0_ce0;
    bn_add_1_address0 <= grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bn_add_1_address0;
    bn_add_1_ce0 <= grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bn_add_1_ce0;
    bn_mul_0_address0 <= grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bn_mul_0_address0;
    bn_mul_0_ce0 <= grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bn_mul_0_ce0;
    bn_mul_1_address0 <= grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bn_mul_1_address0;
    bn_mul_1_ce0 <= grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bn_mul_1_ce0;
    cx_state_q610_0_address0 <= grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_cx_state_q610_0_address0;
    cx_state_q610_0_address1 <= grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_cx_state_q610_0_address1;
    cx_state_q610_0_ce0 <= grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_cx_state_q610_0_ce0;
    cx_state_q610_0_ce1 <= grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_cx_state_q610_0_ce1;
    cx_state_q610_0_d1 <= grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_cx_state_q610_0_d1;
    cx_state_q610_0_we1 <= grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_cx_state_q610_0_we1;
    cx_state_q610_1_address0 <= grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_cx_state_q610_1_address0;
    cx_state_q610_1_address1 <= grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_cx_state_q610_1_address1;
    cx_state_q610_1_ce0 <= grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_cx_state_q610_1_ce0;
    cx_state_q610_1_ce1 <= grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_cx_state_q610_1_ce1;
    cx_state_q610_1_d1 <= grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_cx_state_q610_1_d1;
    cx_state_q610_1_we1 <= grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_cx_state_q610_1_we1;
    empty_618_fu_2407_p1 <= output_hy_q610_1_offset(2 - 1 downto 0);
    empty_619_fu_2412_p1 <= output_hy_q610_0_offset1(3 - 1 downto 0);
    empty_620_fu_2417_p1 <= output_hy_q610_0_offset(2 - 1 downto 0);
    empty_621_fu_2422_p1 <= cx_state_q610_1_offset(4 - 1 downto 0);
    empty_622_fu_2427_p1 <= cx_state_q610_0_offset(4 - 1 downto 0);
    empty_623_fu_2432_p1 <= hx_state_q610_1_offset(4 - 1 downto 0);
    empty_624_fu_2437_p1 <= hx_state_q610_0_offset(4 - 1 downto 0);
    empty_fu_2402_p1 <= output_hy_q610_1_offset2(3 - 1 downto 0);
    grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_ap_start <= grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_ap_start_reg;
    hx_state_q610_0_address0 <= grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_hx_state_q610_0_address0;
    hx_state_q610_0_address1 <= grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_hx_state_q610_0_address1;
    hx_state_q610_0_ce0 <= grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_hx_state_q610_0_ce0;
    hx_state_q610_0_ce1 <= grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_hx_state_q610_0_ce1;
    hx_state_q610_0_d1 <= grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_hx_state_q610_0_d1;
    hx_state_q610_0_we1 <= grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_hx_state_q610_0_we1;
    hx_state_q610_1_address0 <= grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_hx_state_q610_1_address0;
    hx_state_q610_1_address1 <= grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_hx_state_q610_1_address1;
    hx_state_q610_1_ce0 <= grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_hx_state_q610_1_ce0;
    hx_state_q610_1_ce1 <= grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_hx_state_q610_1_ce1;
    hx_state_q610_1_d1 <= grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_hx_state_q610_1_d1;
    hx_state_q610_1_we1 <= grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_hx_state_q610_1_we1;
    output_hy_q610_0_address1 <= grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_output_hy_q610_0_address1;
    output_hy_q610_0_ce1 <= grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_output_hy_q610_0_ce1;
    output_hy_q610_0_d1 <= grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_output_hy_q610_0_d1;
    output_hy_q610_0_we1 <= grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_output_hy_q610_0_we1;
    output_hy_q610_1_address1 <= grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_output_hy_q610_1_address1;
    output_hy_q610_1_ce1 <= grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_output_hy_q610_1_ce1;
    output_hy_q610_1_d1 <= grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_output_hy_q610_1_d1;
    output_hy_q610_1_we1 <= grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_output_hy_q610_1_we1;
    weight_hh_0_address0 <= grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_weight_hh_0_address0;
    weight_hh_0_ce0 <= grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_weight_hh_0_ce0;
    weight_hh_1_address0 <= grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_weight_hh_1_address0;
    weight_hh_1_ce0 <= grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_weight_hh_1_ce0;
    weight_ih_0_address0 <= grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_weight_ih_0_address0;
    weight_ih_0_ce0 <= grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_weight_ih_0_ce0;
    weight_ih_1_address0 <= grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_weight_ih_1_address0;
    weight_ih_1_ce0 <= grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_weight_ih_1_ce0;
end behav;
