// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module SubbandRealtimeTopQ610Ip_p_anonymous_namespace_ReadRealtimeInputChunkQ610 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        noisy_fft_stream_TDATA,
        noisy_fft_stream_TVALID,
        noisy_fft_stream_TREADY,
        noisy_fft_stream_TKEEP,
        noisy_fft_stream_TSTRB,
        noisy_fft_stream_TLAST,
        fb_fft_stream_TDATA,
        fb_fft_stream_TVALID,
        fb_fft_stream_TREADY,
        fb_fft_stream_TKEEP,
        fb_fft_stream_TSTRB,
        fb_fft_stream_TLAST,
        num_frames,
        noisy_chunk_address1,
        noisy_chunk_ce1,
        noisy_chunk_we1,
        noisy_chunk_d1,
        fb_chunk_address1,
        fb_chunk_ce1,
        fb_chunk_we1,
        fb_chunk_d1
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_state3 = 6'd4;
parameter    ap_ST_fsm_state4 = 6'd8;
parameter    ap_ST_fsm_state5 = 6'd16;
parameter    ap_ST_fsm_state6 = 6'd32;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] noisy_fft_stream_TDATA;
input   noisy_fft_stream_TVALID;
output   noisy_fft_stream_TREADY;
input  [1:0] noisy_fft_stream_TKEEP;
input  [1:0] noisy_fft_stream_TSTRB;
input  [0:0] noisy_fft_stream_TLAST;
input  [15:0] fb_fft_stream_TDATA;
input   fb_fft_stream_TVALID;
output   fb_fft_stream_TREADY;
input  [1:0] fb_fft_stream_TKEEP;
input  [1:0] fb_fft_stream_TSTRB;
input  [0:0] fb_fft_stream_TLAST;
input  [2:0] num_frames;
output  [9:0] noisy_chunk_address1;
output   noisy_chunk_ce1;
output   noisy_chunk_we1;
output  [15:0] noisy_chunk_d1;
output  [9:0] fb_chunk_address1;
output   fb_chunk_ce1;
output   fb_chunk_we1;
output  [15:0] fb_chunk_d1;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg noisy_fft_stream_TREADY;
reg fb_fft_stream_TREADY;

(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [2:0] add_ln3370_fu_128_p2;
reg   [2:0] add_ln3370_reg_163;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln3372_fu_134_p2;
reg   [0:0] icmp_ln3372_reg_168;
wire   [1:0] trunc_ln3379_fu_139_p1;
reg   [1:0] trunc_ln3379_reg_172;
wire    grp_p_anonymous_namespace_ReadRealtimeInputChunkQ610_Pipeline_VITIS_LOOP_3373_2_fu_84_ap_start;
wire    grp_p_anonymous_namespace_ReadRealtimeInputChunkQ610_Pipeline_VITIS_LOOP_3373_2_fu_84_ap_done;
wire    grp_p_anonymous_namespace_ReadRealtimeInputChunkQ610_Pipeline_VITIS_LOOP_3373_2_fu_84_ap_idle;
wire    grp_p_anonymous_namespace_ReadRealtimeInputChunkQ610_Pipeline_VITIS_LOOP_3373_2_fu_84_ap_ready;
wire    grp_p_anonymous_namespace_ReadRealtimeInputChunkQ610_Pipeline_VITIS_LOOP_3373_2_fu_84_noisy_fft_stream_TREADY;
wire   [9:0] grp_p_anonymous_namespace_ReadRealtimeInputChunkQ610_Pipeline_VITIS_LOOP_3373_2_fu_84_noisy_chunk_address1;
wire    grp_p_anonymous_namespace_ReadRealtimeInputChunkQ610_Pipeline_VITIS_LOOP_3373_2_fu_84_noisy_chunk_ce1;
wire    grp_p_anonymous_namespace_ReadRealtimeInputChunkQ610_Pipeline_VITIS_LOOP_3373_2_fu_84_noisy_chunk_we1;
wire   [15:0] grp_p_anonymous_namespace_ReadRealtimeInputChunkQ610_Pipeline_VITIS_LOOP_3373_2_fu_84_noisy_chunk_d1;
wire    grp_p_anonymous_namespace_ReadRealtimeInputChunkQ610_Pipeline_VITIS_LOOP_3377_3_fu_99_ap_start;
wire    grp_p_anonymous_namespace_ReadRealtimeInputChunkQ610_Pipeline_VITIS_LOOP_3377_3_fu_99_ap_done;
wire    grp_p_anonymous_namespace_ReadRealtimeInputChunkQ610_Pipeline_VITIS_LOOP_3377_3_fu_99_ap_idle;
wire    grp_p_anonymous_namespace_ReadRealtimeInputChunkQ610_Pipeline_VITIS_LOOP_3377_3_fu_99_ap_ready;
wire    grp_p_anonymous_namespace_ReadRealtimeInputChunkQ610_Pipeline_VITIS_LOOP_3377_3_fu_99_fb_fft_stream_TREADY;
wire   [9:0] grp_p_anonymous_namespace_ReadRealtimeInputChunkQ610_Pipeline_VITIS_LOOP_3377_3_fu_99_fb_chunk_address1;
wire    grp_p_anonymous_namespace_ReadRealtimeInputChunkQ610_Pipeline_VITIS_LOOP_3377_3_fu_99_fb_chunk_ce1;
wire    grp_p_anonymous_namespace_ReadRealtimeInputChunkQ610_Pipeline_VITIS_LOOP_3377_3_fu_99_fb_chunk_we1;
wire   [15:0] grp_p_anonymous_namespace_ReadRealtimeInputChunkQ610_Pipeline_VITIS_LOOP_3377_3_fu_99_fb_chunk_d1;
reg    grp_p_anonymous_namespace_ReadRealtimeInputChunkQ610_Pipeline_VITIS_LOOP_3373_2_fu_84_ap_start_reg;
wire   [0:0] icmp_ln3370_fu_122_p2;
wire    ap_CS_fsm_state3;
reg    grp_p_anonymous_namespace_ReadRealtimeInputChunkQ610_Pipeline_VITIS_LOOP_3377_3_fu_99_ap_start_reg;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
reg   [2:0] frame_index_fu_74;
reg    ap_block_state6_on_subcall_done;
reg   [5:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 6'd1;
#0 grp_p_anonymous_namespace_ReadRealtimeInputChunkQ610_Pipeline_VITIS_LOOP_3373_2_fu_84_ap_start_reg = 1'b0;
#0 grp_p_anonymous_namespace_ReadRealtimeInputChunkQ610_Pipeline_VITIS_LOOP_3377_3_fu_99_ap_start_reg = 1'b0;
#0 frame_index_fu_74 = 3'd0;
end

SubbandRealtimeTopQ610Ip_p_anonymous_namespace_ReadRealtimeInputChunkQ610_Pipeline_VITIS_LOOP_3373_2 grp_p_anonymous_namespace_ReadRealtimeInputChunkQ610_Pipeline_VITIS_LOOP_3373_2_fu_84(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_p_anonymous_namespace_ReadRealtimeInputChunkQ610_Pipeline_VITIS_LOOP_3373_2_fu_84_ap_start),
    .ap_done(grp_p_anonymous_namespace_ReadRealtimeInputChunkQ610_Pipeline_VITIS_LOOP_3373_2_fu_84_ap_done),
    .ap_idle(grp_p_anonymous_namespace_ReadRealtimeInputChunkQ610_Pipeline_VITIS_LOOP_3373_2_fu_84_ap_idle),
    .ap_ready(grp_p_anonymous_namespace_ReadRealtimeInputChunkQ610_Pipeline_VITIS_LOOP_3373_2_fu_84_ap_ready),
    .noisy_fft_stream_TVALID(noisy_fft_stream_TVALID),
    .noisy_fft_stream_TDATA(noisy_fft_stream_TDATA),
    .noisy_fft_stream_TREADY(grp_p_anonymous_namespace_ReadRealtimeInputChunkQ610_Pipeline_VITIS_LOOP_3373_2_fu_84_noisy_fft_stream_TREADY),
    .noisy_fft_stream_TKEEP(noisy_fft_stream_TKEEP),
    .noisy_fft_stream_TSTRB(noisy_fft_stream_TSTRB),
    .noisy_fft_stream_TLAST(noisy_fft_stream_TLAST),
    .empty(trunc_ln3379_reg_172),
    .noisy_chunk_address1(grp_p_anonymous_namespace_ReadRealtimeInputChunkQ610_Pipeline_VITIS_LOOP_3373_2_fu_84_noisy_chunk_address1),
    .noisy_chunk_ce1(grp_p_anonymous_namespace_ReadRealtimeInputChunkQ610_Pipeline_VITIS_LOOP_3373_2_fu_84_noisy_chunk_ce1),
    .noisy_chunk_we1(grp_p_anonymous_namespace_ReadRealtimeInputChunkQ610_Pipeline_VITIS_LOOP_3373_2_fu_84_noisy_chunk_we1),
    .noisy_chunk_d1(grp_p_anonymous_namespace_ReadRealtimeInputChunkQ610_Pipeline_VITIS_LOOP_3373_2_fu_84_noisy_chunk_d1)
);

SubbandRealtimeTopQ610Ip_p_anonymous_namespace_ReadRealtimeInputChunkQ610_Pipeline_VITIS_LOOP_3377_3 grp_p_anonymous_namespace_ReadRealtimeInputChunkQ610_Pipeline_VITIS_LOOP_3377_3_fu_99(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_p_anonymous_namespace_ReadRealtimeInputChunkQ610_Pipeline_VITIS_LOOP_3377_3_fu_99_ap_start),
    .ap_done(grp_p_anonymous_namespace_ReadRealtimeInputChunkQ610_Pipeline_VITIS_LOOP_3377_3_fu_99_ap_done),
    .ap_idle(grp_p_anonymous_namespace_ReadRealtimeInputChunkQ610_Pipeline_VITIS_LOOP_3377_3_fu_99_ap_idle),
    .ap_ready(grp_p_anonymous_namespace_ReadRealtimeInputChunkQ610_Pipeline_VITIS_LOOP_3377_3_fu_99_ap_ready),
    .fb_fft_stream_TVALID(fb_fft_stream_TVALID),
    .fb_fft_stream_TDATA(fb_fft_stream_TDATA),
    .fb_fft_stream_TREADY(grp_p_anonymous_namespace_ReadRealtimeInputChunkQ610_Pipeline_VITIS_LOOP_3377_3_fu_99_fb_fft_stream_TREADY),
    .fb_fft_stream_TKEEP(fb_fft_stream_TKEEP),
    .fb_fft_stream_TSTRB(fb_fft_stream_TSTRB),
    .fb_fft_stream_TLAST(fb_fft_stream_TLAST),
    .empty(trunc_ln3379_reg_172),
    .fb_chunk_address1(grp_p_anonymous_namespace_ReadRealtimeInputChunkQ610_Pipeline_VITIS_LOOP_3377_3_fu_99_fb_chunk_address1),
    .fb_chunk_ce1(grp_p_anonymous_namespace_ReadRealtimeInputChunkQ610_Pipeline_VITIS_LOOP_3377_3_fu_99_fb_chunk_ce1),
    .fb_chunk_we1(grp_p_anonymous_namespace_ReadRealtimeInputChunkQ610_Pipeline_VITIS_LOOP_3377_3_fu_99_fb_chunk_we1),
    .fb_chunk_d1(grp_p_anonymous_namespace_ReadRealtimeInputChunkQ610_Pipeline_VITIS_LOOP_3377_3_fu_99_fb_chunk_d1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_p_anonymous_namespace_ReadRealtimeInputChunkQ610_Pipeline_VITIS_LOOP_3373_2_fu_84_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln3372_fu_134_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln3370_fu_122_p2 == 1'd0))) begin
            grp_p_anonymous_namespace_ReadRealtimeInputChunkQ610_Pipeline_VITIS_LOOP_3373_2_fu_84_ap_start_reg <= 1'b1;
        end else if ((grp_p_anonymous_namespace_ReadRealtimeInputChunkQ610_Pipeline_VITIS_LOOP_3373_2_fu_84_ap_ready == 1'b1)) begin
            grp_p_anonymous_namespace_ReadRealtimeInputChunkQ610_Pipeline_VITIS_LOOP_3373_2_fu_84_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_p_anonymous_namespace_ReadRealtimeInputChunkQ610_Pipeline_VITIS_LOOP_3377_3_fu_99_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_p_anonymous_namespace_ReadRealtimeInputChunkQ610_Pipeline_VITIS_LOOP_3377_3_fu_99_ap_start_reg <= 1'b1;
        end else if ((grp_p_anonymous_namespace_ReadRealtimeInputChunkQ610_Pipeline_VITIS_LOOP_3377_3_fu_99_ap_ready == 1'b1)) begin
            grp_p_anonymous_namespace_ReadRealtimeInputChunkQ610_Pipeline_VITIS_LOOP_3377_3_fu_99_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        frame_index_fu_74 <= 3'd0;
    end else if (((1'b1 == ap_CS_fsm_state6) & (1'b0 == ap_block_state6_on_subcall_done))) begin
        frame_index_fu_74 <= add_ln3370_reg_163;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln3370_reg_163 <= add_ln3370_fu_128_p2;
        icmp_ln3372_reg_168 <= icmp_ln3372_fu_134_p2;
        trunc_ln3379_reg_172 <= trunc_ln3379_fu_139_p1;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_p_anonymous_namespace_ReadRealtimeInputChunkQ610_Pipeline_VITIS_LOOP_3373_2_fu_84_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state6_on_subcall_done)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state2) & (icmp_ln3370_fu_122_p2 == 1'd1)) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln3370_fu_122_p2 == 1'd1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln3372_reg_168 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
        fb_fft_stream_TREADY = grp_p_anonymous_namespace_ReadRealtimeInputChunkQ610_Pipeline_VITIS_LOOP_3377_3_fu_99_fb_fft_stream_TREADY;
    end else begin
        fb_fft_stream_TREADY = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        noisy_fft_stream_TREADY = grp_p_anonymous_namespace_ReadRealtimeInputChunkQ610_Pipeline_VITIS_LOOP_3373_2_fu_84_noisy_fft_stream_TREADY;
    end else begin
        noisy_fft_stream_TREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln3370_fu_122_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if (((icmp_ln3372_fu_134_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln3370_fu_122_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((grp_p_anonymous_namespace_ReadRealtimeInputChunkQ610_Pipeline_VITIS_LOOP_3373_2_fu_84_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (1'b0 == ap_block_state6_on_subcall_done))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln3370_fu_128_p2 = (frame_index_fu_74 + 3'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

always @ (*) begin
    ap_block_state6_on_subcall_done = ((grp_p_anonymous_namespace_ReadRealtimeInputChunkQ610_Pipeline_VITIS_LOOP_3377_3_fu_99_ap_done == 1'b0) & (icmp_ln3372_reg_168 == 1'd1));
end

assign fb_chunk_address1 = grp_p_anonymous_namespace_ReadRealtimeInputChunkQ610_Pipeline_VITIS_LOOP_3377_3_fu_99_fb_chunk_address1;

assign fb_chunk_ce1 = grp_p_anonymous_namespace_ReadRealtimeInputChunkQ610_Pipeline_VITIS_LOOP_3377_3_fu_99_fb_chunk_ce1;

assign fb_chunk_d1 = grp_p_anonymous_namespace_ReadRealtimeInputChunkQ610_Pipeline_VITIS_LOOP_3377_3_fu_99_fb_chunk_d1;

assign fb_chunk_we1 = grp_p_anonymous_namespace_ReadRealtimeInputChunkQ610_Pipeline_VITIS_LOOP_3377_3_fu_99_fb_chunk_we1;

assign grp_p_anonymous_namespace_ReadRealtimeInputChunkQ610_Pipeline_VITIS_LOOP_3373_2_fu_84_ap_start = grp_p_anonymous_namespace_ReadRealtimeInputChunkQ610_Pipeline_VITIS_LOOP_3373_2_fu_84_ap_start_reg;

assign grp_p_anonymous_namespace_ReadRealtimeInputChunkQ610_Pipeline_VITIS_LOOP_3377_3_fu_99_ap_start = grp_p_anonymous_namespace_ReadRealtimeInputChunkQ610_Pipeline_VITIS_LOOP_3377_3_fu_99_ap_start_reg;

assign icmp_ln3370_fu_122_p2 = ((frame_index_fu_74 == 3'd4) ? 1'b1 : 1'b0);

assign icmp_ln3372_fu_134_p2 = ((frame_index_fu_74 < num_frames) ? 1'b1 : 1'b0);

assign noisy_chunk_address1 = grp_p_anonymous_namespace_ReadRealtimeInputChunkQ610_Pipeline_VITIS_LOOP_3373_2_fu_84_noisy_chunk_address1;

assign noisy_chunk_ce1 = grp_p_anonymous_namespace_ReadRealtimeInputChunkQ610_Pipeline_VITIS_LOOP_3373_2_fu_84_noisy_chunk_ce1;

assign noisy_chunk_d1 = grp_p_anonymous_namespace_ReadRealtimeInputChunkQ610_Pipeline_VITIS_LOOP_3373_2_fu_84_noisy_chunk_d1;

assign noisy_chunk_we1 = grp_p_anonymous_namespace_ReadRealtimeInputChunkQ610_Pipeline_VITIS_LOOP_3373_2_fu_84_noisy_chunk_we1;

assign trunc_ln3379_fu_139_p1 = frame_index_fu_74[1:0];

endmodule //SubbandRealtimeTopQ610Ip_p_anonymous_namespace_ReadRealtimeInputChunkQ610
