// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module SubbandRealtimeTopQ610Ip_p_anonymous_namespace_CallExternalProjectionIpQ610 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_tiles_0_val,
        input_tiles_1_val,
        input_tiles_2_val,
        input_tiles_3_val,
        input_tiles_4_val,
        input_tiles_5_val,
        input_tiles_6_val,
        proj_row_0_val,
        proj_row_1_val,
        proj_row_2_val,
        proj_row_3_val,
        proj_row_4_val,
        proj_row_5_val,
        proj_row_6_val,
        proj_row_7_val,
        proj_row_8_val,
        proj_row_9_val,
        proj_row_10_val,
        proj_row_11_val,
        proj_row_12_val,
        proj_row_13_val,
        proj_row_14_val,
        proj_row_15_val,
        proj_row_16_val,
        proj_row_17_val,
        proj_row_18_val,
        proj_row_19_val,
        proj_row_20_val,
        proj_row_21_val,
        proj_row_22_val,
        proj_row_23_val,
        proj_row_24_val,
        proj_row_25_val,
        proj_row_26_val,
        proj_row_27_val,
        proj_row_28_val,
        proj_row_29_val,
        proj_row_30_val,
        proj_row_31_val,
        proj_row_32_val,
        proj_row_33_val,
        proj_row_34_val,
        proj_row_35_val,
        proj_row_36_val,
        proj_row_37_val,
        proj_row_38_val,
        proj_row_39_val,
        proj_row_40_val,
        proj_row_41_val,
        proj_row_42_val,
        proj_row_43_val,
        proj_row_44_val,
        proj_row_45_val,
        proj_row_46_val,
        proj_row_47_val,
        proj_row_48_val,
        proj_row_49_val,
        proj_row_50_val,
        proj_row_51_val,
        proj_row_52_val,
        proj_row_53_val,
        proj_row_54_val,
        proj_row_55_val,
        proj_row_56_val,
        proj_row_57_val,
        proj_row_58_val,
        proj_row_59_val,
        proj_row_60_val,
        proj_row_61_val,
        proj_row_62_val,
        proj_row_63_val,
        proj_row_64_val,
        proj_row_65_val,
        proj_row_66_val,
        proj_row_67_val,
        proj_row_68_val,
        proj_row_69_val,
        proj_row_70_val,
        proj_row_71_val,
        proj_row_72_val,
        proj_row_73_val,
        proj_row_74_val,
        proj_row_75_val,
        proj_row_76_val,
        proj_row_77_val,
        proj_row_78_val,
        proj_row_79_val,
        proj_row_80_val,
        proj_row_81_val,
        proj_row_82_val,
        proj_row_83_val,
        proj_row_84_val,
        proj_row_85_val,
        proj_row_86_val,
        proj_row_87_val,
        proj_row_88_val,
        proj_row_89_val,
        proj_row_90_val,
        proj_row_91_val,
        proj_row_92_val,
        proj_row_93_val,
        proj_row_94_val,
        proj_row_95_val,
        proj_row_96_val,
        proj_row_97_val,
        proj_row_98_val,
        proj_row_99_val,
        proj_row_100_val,
        proj_row_101_val,
        proj_row_102_val,
        proj_row_103_val,
        proj_row_104_val,
        proj_row_105_val,
        proj_row_106_val,
        proj_row_107_val,
        proj_row_108_val,
        proj_row_109_val,
        proj_row_110_val,
        proj_row_111_val,
        proj_row_112_val,
        proj_row_113_val,
        proj_row_114_val,
        proj_row_115_val,
        proj_row_116_val,
        proj_row_117_val,
        proj_row_118_val,
        proj_row_119_val,
        proj_row_120_val,
        proj_row_121_val,
        proj_row_122_val,
        proj_row_123_val,
        proj_row_124_val,
        proj_row_125_val,
        proj_row_126_val,
        proj_row_127_val,
        proj_row_128_val,
        proj_row_129_val,
        proj_row_130_val,
        proj_row_131_val,
        proj_row_132_val,
        proj_row_133_val,
        proj_row_134_val,
        proj_row_135_val,
        proj_row_136_val,
        proj_row_137_val,
        proj_row_138_val,
        proj_row_139_val,
        proj_row_140_val,
        proj_row_141_val,
        proj_row_142_val,
        proj_row_143_val,
        proj_row_144_val,
        proj_row_145_val,
        proj_row_146_val,
        proj_row_147_val,
        proj_row_148_val,
        proj_row_149_val,
        proj_row_150_val,
        proj_row_151_val,
        proj_row_152_val,
        proj_row_153_val,
        proj_row_154_val,
        proj_row_155_val,
        proj_row_156_val,
        proj_row_157_val,
        proj_row_158_val,
        proj_row_159_val,
        proj_row_160_val,
        proj_row_161_val,
        proj_row_162_val,
        proj_row_163_val,
        proj_row_164_val,
        proj_row_165_val,
        proj_row_166_val,
        proj_row_167_val,
        proj_row_168_val,
        proj_row_169_val,
        proj_row_170_val,
        proj_row_171_val,
        proj_row_172_val,
        proj_row_173_val,
        proj_row_174_val,
        proj_row_175_val,
        proj_row_176_val,
        proj_row_177_val,
        proj_row_178_val,
        proj_row_179_val,
        proj_row_180_val,
        proj_row_181_val,
        proj_row_182_val,
        proj_row_183_val,
        proj_row_184_val,
        proj_row_185_val,
        proj_row_186_val,
        proj_row_187_val,
        proj_row_188_val,
        proj_row_189_val,
        proj_row_190_val,
        proj_row_191_val,
        proj_row_192_val,
        proj_row_193_val,
        proj_row_194_val,
        proj_row_195_val,
        proj_row_196_val,
        proj_row_197_val,
        proj_row_198_val,
        proj_row_199_val,
        proj_row_200_val,
        proj_row_201_val,
        proj_row_202_val,
        proj_row_203_val,
        proj_row_204_val,
        proj_row_205_val,
        proj_row_206_val,
        proj_row_207_val,
        proj_row_208_val,
        proj_row_209_val,
        proj_row_210_val,
        proj_row_211_val,
        proj_row_212_val,
        proj_row_213_val,
        proj_row_214_val,
        proj_row_215_val,
        proj_row_216_val,
        proj_row_217_val,
        proj_row_218_val,
        proj_row_219_val,
        proj_row_220_val,
        proj_row_221_val,
        proj_row_222_val,
        proj_row_223_val,
        projection_request_stream_TDATA,
        projection_request_stream_TVALID,
        projection_request_stream_TREADY,
        projection_request_stream_TKEEP,
        projection_request_stream_TSTRB,
        projection_request_stream_TLAST,
        projection_response_stream_TDATA,
        projection_response_stream_TVALID,
        projection_response_stream_TREADY,
        projection_response_stream_TKEEP,
        projection_response_stream_TSTRB,
        projection_response_stream_TLAST,
        ap_return
);

parameter    ap_ST_fsm_state1 = 9'd1;
parameter    ap_ST_fsm_state2 = 9'd2;
parameter    ap_ST_fsm_state3 = 9'd4;
parameter    ap_ST_fsm_state4 = 9'd8;
parameter    ap_ST_fsm_state5 = 9'd16;
parameter    ap_ST_fsm_state6 = 9'd32;
parameter    ap_ST_fsm_state7 = 9'd64;
parameter    ap_ST_fsm_state8 = 9'd128;
parameter    ap_ST_fsm_state9 = 9'd256;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [511:0] input_tiles_0_val;
input  [511:0] input_tiles_1_val;
input  [511:0] input_tiles_2_val;
input  [511:0] input_tiles_3_val;
input  [511:0] input_tiles_4_val;
input  [511:0] input_tiles_5_val;
input  [511:0] input_tiles_6_val;
input  [15:0] proj_row_0_val;
input  [15:0] proj_row_1_val;
input  [15:0] proj_row_2_val;
input  [15:0] proj_row_3_val;
input  [15:0] proj_row_4_val;
input  [15:0] proj_row_5_val;
input  [15:0] proj_row_6_val;
input  [15:0] proj_row_7_val;
input  [15:0] proj_row_8_val;
input  [15:0] proj_row_9_val;
input  [15:0] proj_row_10_val;
input  [15:0] proj_row_11_val;
input  [15:0] proj_row_12_val;
input  [15:0] proj_row_13_val;
input  [15:0] proj_row_14_val;
input  [15:0] proj_row_15_val;
input  [15:0] proj_row_16_val;
input  [15:0] proj_row_17_val;
input  [15:0] proj_row_18_val;
input  [15:0] proj_row_19_val;
input  [15:0] proj_row_20_val;
input  [15:0] proj_row_21_val;
input  [15:0] proj_row_22_val;
input  [15:0] proj_row_23_val;
input  [15:0] proj_row_24_val;
input  [15:0] proj_row_25_val;
input  [15:0] proj_row_26_val;
input  [15:0] proj_row_27_val;
input  [15:0] proj_row_28_val;
input  [15:0] proj_row_29_val;
input  [15:0] proj_row_30_val;
input  [15:0] proj_row_31_val;
input  [15:0] proj_row_32_val;
input  [15:0] proj_row_33_val;
input  [15:0] proj_row_34_val;
input  [15:0] proj_row_35_val;
input  [15:0] proj_row_36_val;
input  [15:0] proj_row_37_val;
input  [15:0] proj_row_38_val;
input  [15:0] proj_row_39_val;
input  [15:0] proj_row_40_val;
input  [15:0] proj_row_41_val;
input  [15:0] proj_row_42_val;
input  [15:0] proj_row_43_val;
input  [15:0] proj_row_44_val;
input  [15:0] proj_row_45_val;
input  [15:0] proj_row_46_val;
input  [15:0] proj_row_47_val;
input  [15:0] proj_row_48_val;
input  [15:0] proj_row_49_val;
input  [15:0] proj_row_50_val;
input  [15:0] proj_row_51_val;
input  [15:0] proj_row_52_val;
input  [15:0] proj_row_53_val;
input  [15:0] proj_row_54_val;
input  [15:0] proj_row_55_val;
input  [15:0] proj_row_56_val;
input  [15:0] proj_row_57_val;
input  [15:0] proj_row_58_val;
input  [15:0] proj_row_59_val;
input  [15:0] proj_row_60_val;
input  [15:0] proj_row_61_val;
input  [15:0] proj_row_62_val;
input  [15:0] proj_row_63_val;
input  [15:0] proj_row_64_val;
input  [15:0] proj_row_65_val;
input  [15:0] proj_row_66_val;
input  [15:0] proj_row_67_val;
input  [15:0] proj_row_68_val;
input  [15:0] proj_row_69_val;
input  [15:0] proj_row_70_val;
input  [15:0] proj_row_71_val;
input  [15:0] proj_row_72_val;
input  [15:0] proj_row_73_val;
input  [15:0] proj_row_74_val;
input  [15:0] proj_row_75_val;
input  [15:0] proj_row_76_val;
input  [15:0] proj_row_77_val;
input  [15:0] proj_row_78_val;
input  [15:0] proj_row_79_val;
input  [15:0] proj_row_80_val;
input  [15:0] proj_row_81_val;
input  [15:0] proj_row_82_val;
input  [15:0] proj_row_83_val;
input  [15:0] proj_row_84_val;
input  [15:0] proj_row_85_val;
input  [15:0] proj_row_86_val;
input  [15:0] proj_row_87_val;
input  [15:0] proj_row_88_val;
input  [15:0] proj_row_89_val;
input  [15:0] proj_row_90_val;
input  [15:0] proj_row_91_val;
input  [15:0] proj_row_92_val;
input  [15:0] proj_row_93_val;
input  [15:0] proj_row_94_val;
input  [15:0] proj_row_95_val;
input  [15:0] proj_row_96_val;
input  [15:0] proj_row_97_val;
input  [15:0] proj_row_98_val;
input  [15:0] proj_row_99_val;
input  [15:0] proj_row_100_val;
input  [15:0] proj_row_101_val;
input  [15:0] proj_row_102_val;
input  [15:0] proj_row_103_val;
input  [15:0] proj_row_104_val;
input  [15:0] proj_row_105_val;
input  [15:0] proj_row_106_val;
input  [15:0] proj_row_107_val;
input  [15:0] proj_row_108_val;
input  [15:0] proj_row_109_val;
input  [15:0] proj_row_110_val;
input  [15:0] proj_row_111_val;
input  [15:0] proj_row_112_val;
input  [15:0] proj_row_113_val;
input  [15:0] proj_row_114_val;
input  [15:0] proj_row_115_val;
input  [15:0] proj_row_116_val;
input  [15:0] proj_row_117_val;
input  [15:0] proj_row_118_val;
input  [15:0] proj_row_119_val;
input  [15:0] proj_row_120_val;
input  [15:0] proj_row_121_val;
input  [15:0] proj_row_122_val;
input  [15:0] proj_row_123_val;
input  [15:0] proj_row_124_val;
input  [15:0] proj_row_125_val;
input  [15:0] proj_row_126_val;
input  [15:0] proj_row_127_val;
input  [15:0] proj_row_128_val;
input  [15:0] proj_row_129_val;
input  [15:0] proj_row_130_val;
input  [15:0] proj_row_131_val;
input  [15:0] proj_row_132_val;
input  [15:0] proj_row_133_val;
input  [15:0] proj_row_134_val;
input  [15:0] proj_row_135_val;
input  [15:0] proj_row_136_val;
input  [15:0] proj_row_137_val;
input  [15:0] proj_row_138_val;
input  [15:0] proj_row_139_val;
input  [15:0] proj_row_140_val;
input  [15:0] proj_row_141_val;
input  [15:0] proj_row_142_val;
input  [15:0] proj_row_143_val;
input  [15:0] proj_row_144_val;
input  [15:0] proj_row_145_val;
input  [15:0] proj_row_146_val;
input  [15:0] proj_row_147_val;
input  [15:0] proj_row_148_val;
input  [15:0] proj_row_149_val;
input  [15:0] proj_row_150_val;
input  [15:0] proj_row_151_val;
input  [15:0] proj_row_152_val;
input  [15:0] proj_row_153_val;
input  [15:0] proj_row_154_val;
input  [15:0] proj_row_155_val;
input  [15:0] proj_row_156_val;
input  [15:0] proj_row_157_val;
input  [15:0] proj_row_158_val;
input  [15:0] proj_row_159_val;
input  [15:0] proj_row_160_val;
input  [15:0] proj_row_161_val;
input  [15:0] proj_row_162_val;
input  [15:0] proj_row_163_val;
input  [15:0] proj_row_164_val;
input  [15:0] proj_row_165_val;
input  [15:0] proj_row_166_val;
input  [15:0] proj_row_167_val;
input  [15:0] proj_row_168_val;
input  [15:0] proj_row_169_val;
input  [15:0] proj_row_170_val;
input  [15:0] proj_row_171_val;
input  [15:0] proj_row_172_val;
input  [15:0] proj_row_173_val;
input  [15:0] proj_row_174_val;
input  [15:0] proj_row_175_val;
input  [15:0] proj_row_176_val;
input  [15:0] proj_row_177_val;
input  [15:0] proj_row_178_val;
input  [15:0] proj_row_179_val;
input  [15:0] proj_row_180_val;
input  [15:0] proj_row_181_val;
input  [15:0] proj_row_182_val;
input  [15:0] proj_row_183_val;
input  [15:0] proj_row_184_val;
input  [15:0] proj_row_185_val;
input  [15:0] proj_row_186_val;
input  [15:0] proj_row_187_val;
input  [15:0] proj_row_188_val;
input  [15:0] proj_row_189_val;
input  [15:0] proj_row_190_val;
input  [15:0] proj_row_191_val;
input  [15:0] proj_row_192_val;
input  [15:0] proj_row_193_val;
input  [15:0] proj_row_194_val;
input  [15:0] proj_row_195_val;
input  [15:0] proj_row_196_val;
input  [15:0] proj_row_197_val;
input  [15:0] proj_row_198_val;
input  [15:0] proj_row_199_val;
input  [15:0] proj_row_200_val;
input  [15:0] proj_row_201_val;
input  [15:0] proj_row_202_val;
input  [15:0] proj_row_203_val;
input  [15:0] proj_row_204_val;
input  [15:0] proj_row_205_val;
input  [15:0] proj_row_206_val;
input  [15:0] proj_row_207_val;
input  [15:0] proj_row_208_val;
input  [15:0] proj_row_209_val;
input  [15:0] proj_row_210_val;
input  [15:0] proj_row_211_val;
input  [15:0] proj_row_212_val;
input  [15:0] proj_row_213_val;
input  [15:0] proj_row_214_val;
input  [15:0] proj_row_215_val;
input  [15:0] proj_row_216_val;
input  [15:0] proj_row_217_val;
input  [15:0] proj_row_218_val;
input  [15:0] proj_row_219_val;
input  [15:0] proj_row_220_val;
input  [15:0] proj_row_221_val;
input  [15:0] proj_row_222_val;
input  [15:0] proj_row_223_val;
output  [15:0] projection_request_stream_TDATA;
output   projection_request_stream_TVALID;
input   projection_request_stream_TREADY;
output  [1:0] projection_request_stream_TKEEP;
output  [1:0] projection_request_stream_TSTRB;
output  [0:0] projection_request_stream_TLAST;
input  [15:0] projection_response_stream_TDATA;
input   projection_response_stream_TVALID;
output   projection_response_stream_TREADY;
input  [1:0] projection_response_stream_TKEEP;
input  [1:0] projection_response_stream_TSTRB;
input  [0:0] projection_response_stream_TLAST;
output  [47:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[15:0] projection_request_stream_TDATA;
reg projection_request_stream_TVALID;
reg[1:0] projection_request_stream_TKEEP;
reg[1:0] projection_request_stream_TSTRB;
reg[0:0] projection_request_stream_TLAST;
reg projection_response_stream_TREADY;
reg[47:0] ap_return;

(* fsm_encoding = "none" *) reg   [8:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    projection_response_stream_TDATA_blk_n;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state9;
reg   [15:0] p_0_reg_3332;
reg   [15:0] p_s_reg_3337;
wire    grp_p_anonymous_namespace_CallExternalProjectionIpQ610_Pipeline_VITIS_LOOP_4558_1_VIT_fu_1910_ap_start;
wire    grp_p_anonymous_namespace_CallExternalProjectionIpQ610_Pipeline_VITIS_LOOP_4558_1_VIT_fu_1910_ap_done;
wire    grp_p_anonymous_namespace_CallExternalProjectionIpQ610_Pipeline_VITIS_LOOP_4558_1_VIT_fu_1910_ap_idle;
wire    grp_p_anonymous_namespace_CallExternalProjectionIpQ610_Pipeline_VITIS_LOOP_4558_1_VIT_fu_1910_ap_ready;
wire    grp_p_anonymous_namespace_CallExternalProjectionIpQ610_Pipeline_VITIS_LOOP_4558_1_VIT_fu_1910_projection_request_stream_TREADY;
wire   [15:0] grp_p_anonymous_namespace_CallExternalProjectionIpQ610_Pipeline_VITIS_LOOP_4558_1_VIT_fu_1910_projection_request_stream_TDATA;
wire    grp_p_anonymous_namespace_CallExternalProjectionIpQ610_Pipeline_VITIS_LOOP_4558_1_VIT_fu_1910_projection_request_stream_TVALID;
wire   [1:0] grp_p_anonymous_namespace_CallExternalProjectionIpQ610_Pipeline_VITIS_LOOP_4558_1_VIT_fu_1910_projection_request_stream_TKEEP;
wire   [1:0] grp_p_anonymous_namespace_CallExternalProjectionIpQ610_Pipeline_VITIS_LOOP_4558_1_VIT_fu_1910_projection_request_stream_TSTRB;
wire   [0:0] grp_p_anonymous_namespace_CallExternalProjectionIpQ610_Pipeline_VITIS_LOOP_4558_1_VIT_fu_1910_projection_request_stream_TLAST;
wire    grp_p_anonymous_namespace_CallExternalProjectionIpQ610_Pipeline_VITIS_LOOP_4565_3_fu_1929_ap_start;
wire    grp_p_anonymous_namespace_CallExternalProjectionIpQ610_Pipeline_VITIS_LOOP_4565_3_fu_1929_ap_done;
wire    grp_p_anonymous_namespace_CallExternalProjectionIpQ610_Pipeline_VITIS_LOOP_4565_3_fu_1929_ap_idle;
wire    grp_p_anonymous_namespace_CallExternalProjectionIpQ610_Pipeline_VITIS_LOOP_4565_3_fu_1929_ap_ready;
wire    grp_p_anonymous_namespace_CallExternalProjectionIpQ610_Pipeline_VITIS_LOOP_4565_3_fu_1929_projection_request_stream_TREADY;
wire   [15:0] grp_p_anonymous_namespace_CallExternalProjectionIpQ610_Pipeline_VITIS_LOOP_4565_3_fu_1929_projection_request_stream_TDATA;
wire    grp_p_anonymous_namespace_CallExternalProjectionIpQ610_Pipeline_VITIS_LOOP_4565_3_fu_1929_projection_request_stream_TVALID;
wire   [1:0] grp_p_anonymous_namespace_CallExternalProjectionIpQ610_Pipeline_VITIS_LOOP_4565_3_fu_1929_projection_request_stream_TKEEP;
wire   [1:0] grp_p_anonymous_namespace_CallExternalProjectionIpQ610_Pipeline_VITIS_LOOP_4565_3_fu_1929_projection_request_stream_TSTRB;
wire   [0:0] grp_p_anonymous_namespace_CallExternalProjectionIpQ610_Pipeline_VITIS_LOOP_4565_3_fu_1929_projection_request_stream_TLAST;
reg    grp_p_anonymous_namespace_CallExternalProjectionIpQ610_Pipeline_VITIS_LOOP_4558_1_VIT_fu_1910_ap_start_reg;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
reg    grp_p_anonymous_namespace_CallExternalProjectionIpQ610_Pipeline_VITIS_LOOP_4565_3_fu_1929_ap_start_reg;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
wire   [47:0] agg_result_fu_2169_p4;
reg   [47:0] ap_return_preg;
reg   [8:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 9'd1;
#0 grp_p_anonymous_namespace_CallExternalProjectionIpQ610_Pipeline_VITIS_LOOP_4558_1_VIT_fu_1910_ap_start_reg = 1'b0;
#0 grp_p_anonymous_namespace_CallExternalProjectionIpQ610_Pipeline_VITIS_LOOP_4565_3_fu_1929_ap_start_reg = 1'b0;
#0 ap_return_preg = 48'd0;
end

SubbandRealtimeTopQ610Ip_p_anonymous_namespace_CallExternalProjectionIpQ610_Pipeline_VITIS_LOOP_4558_1_VIT grp_p_anonymous_namespace_CallExternalProjectionIpQ610_Pipeline_VITIS_LOOP_4558_1_VIT_fu_1910(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_p_anonymous_namespace_CallExternalProjectionIpQ610_Pipeline_VITIS_LOOP_4558_1_VIT_fu_1910_ap_start),
    .ap_done(grp_p_anonymous_namespace_CallExternalProjectionIpQ610_Pipeline_VITIS_LOOP_4558_1_VIT_fu_1910_ap_done),
    .ap_idle(grp_p_anonymous_namespace_CallExternalProjectionIpQ610_Pipeline_VITIS_LOOP_4558_1_VIT_fu_1910_ap_idle),
    .ap_ready(grp_p_anonymous_namespace_CallExternalProjectionIpQ610_Pipeline_VITIS_LOOP_4558_1_VIT_fu_1910_ap_ready),
    .projection_request_stream_TREADY(grp_p_anonymous_namespace_CallExternalProjectionIpQ610_Pipeline_VITIS_LOOP_4558_1_VIT_fu_1910_projection_request_stream_TREADY),
    .input_tiles_0_val(input_tiles_0_val),
    .input_tiles_1_val(input_tiles_1_val),
    .input_tiles_2_val(input_tiles_2_val),
    .input_tiles_3_val(input_tiles_3_val),
    .input_tiles_4_val(input_tiles_4_val),
    .input_tiles_5_val(input_tiles_5_val),
    .input_tiles_6_val(input_tiles_6_val),
    .projection_request_stream_TDATA(grp_p_anonymous_namespace_CallExternalProjectionIpQ610_Pipeline_VITIS_LOOP_4558_1_VIT_fu_1910_projection_request_stream_TDATA),
    .projection_request_stream_TVALID(grp_p_anonymous_namespace_CallExternalProjectionIpQ610_Pipeline_VITIS_LOOP_4558_1_VIT_fu_1910_projection_request_stream_TVALID),
    .projection_request_stream_TKEEP(grp_p_anonymous_namespace_CallExternalProjectionIpQ610_Pipeline_VITIS_LOOP_4558_1_VIT_fu_1910_projection_request_stream_TKEEP),
    .projection_request_stream_TSTRB(grp_p_anonymous_namespace_CallExternalProjectionIpQ610_Pipeline_VITIS_LOOP_4558_1_VIT_fu_1910_projection_request_stream_TSTRB),
    .projection_request_stream_TLAST(grp_p_anonymous_namespace_CallExternalProjectionIpQ610_Pipeline_VITIS_LOOP_4558_1_VIT_fu_1910_projection_request_stream_TLAST)
);

SubbandRealtimeTopQ610Ip_p_anonymous_namespace_CallExternalProjectionIpQ610_Pipeline_VITIS_LOOP_4565_3 grp_p_anonymous_namespace_CallExternalProjectionIpQ610_Pipeline_VITIS_LOOP_4565_3_fu_1929(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_p_anonymous_namespace_CallExternalProjectionIpQ610_Pipeline_VITIS_LOOP_4565_3_fu_1929_ap_start),
    .ap_done(grp_p_anonymous_namespace_CallExternalProjectionIpQ610_Pipeline_VITIS_LOOP_4565_3_fu_1929_ap_done),
    .ap_idle(grp_p_anonymous_namespace_CallExternalProjectionIpQ610_Pipeline_VITIS_LOOP_4565_3_fu_1929_ap_idle),
    .ap_ready(grp_p_anonymous_namespace_CallExternalProjectionIpQ610_Pipeline_VITIS_LOOP_4565_3_fu_1929_ap_ready),
    .projection_request_stream_TREADY(grp_p_anonymous_namespace_CallExternalProjectionIpQ610_Pipeline_VITIS_LOOP_4565_3_fu_1929_projection_request_stream_TREADY),
    .proj_row_0_val(proj_row_0_val),
    .proj_row_1_val(proj_row_1_val),
    .proj_row_2_val(proj_row_2_val),
    .proj_row_3_val(proj_row_3_val),
    .proj_row_4_val(proj_row_4_val),
    .proj_row_5_val(proj_row_5_val),
    .proj_row_6_val(proj_row_6_val),
    .proj_row_7_val(proj_row_7_val),
    .proj_row_8_val(proj_row_8_val),
    .proj_row_9_val(proj_row_9_val),
    .proj_row_10_val(proj_row_10_val),
    .proj_row_11_val(proj_row_11_val),
    .proj_row_12_val(proj_row_12_val),
    .proj_row_13_val(proj_row_13_val),
    .proj_row_14_val(proj_row_14_val),
    .proj_row_15_val(proj_row_15_val),
    .proj_row_16_val(proj_row_16_val),
    .proj_row_17_val(proj_row_17_val),
    .proj_row_18_val(proj_row_18_val),
    .proj_row_19_val(proj_row_19_val),
    .proj_row_20_val(proj_row_20_val),
    .proj_row_21_val(proj_row_21_val),
    .proj_row_22_val(proj_row_22_val),
    .proj_row_23_val(proj_row_23_val),
    .proj_row_24_val(proj_row_24_val),
    .proj_row_25_val(proj_row_25_val),
    .proj_row_26_val(proj_row_26_val),
    .proj_row_27_val(proj_row_27_val),
    .proj_row_28_val(proj_row_28_val),
    .proj_row_29_val(proj_row_29_val),
    .proj_row_30_val(proj_row_30_val),
    .proj_row_31_val(proj_row_31_val),
    .proj_row_32_val(proj_row_32_val),
    .proj_row_33_val(proj_row_33_val),
    .proj_row_34_val(proj_row_34_val),
    .proj_row_35_val(proj_row_35_val),
    .proj_row_36_val(proj_row_36_val),
    .proj_row_37_val(proj_row_37_val),
    .proj_row_38_val(proj_row_38_val),
    .proj_row_39_val(proj_row_39_val),
    .proj_row_40_val(proj_row_40_val),
    .proj_row_41_val(proj_row_41_val),
    .proj_row_42_val(proj_row_42_val),
    .proj_row_43_val(proj_row_43_val),
    .proj_row_44_val(proj_row_44_val),
    .proj_row_45_val(proj_row_45_val),
    .proj_row_46_val(proj_row_46_val),
    .proj_row_47_val(proj_row_47_val),
    .proj_row_48_val(proj_row_48_val),
    .proj_row_49_val(proj_row_49_val),
    .proj_row_50_val(proj_row_50_val),
    .proj_row_51_val(proj_row_51_val),
    .proj_row_52_val(proj_row_52_val),
    .proj_row_53_val(proj_row_53_val),
    .proj_row_54_val(proj_row_54_val),
    .proj_row_55_val(proj_row_55_val),
    .proj_row_56_val(proj_row_56_val),
    .proj_row_57_val(proj_row_57_val),
    .proj_row_58_val(proj_row_58_val),
    .proj_row_59_val(proj_row_59_val),
    .proj_row_60_val(proj_row_60_val),
    .proj_row_61_val(proj_row_61_val),
    .proj_row_62_val(proj_row_62_val),
    .proj_row_63_val(proj_row_63_val),
    .proj_row_64_val(proj_row_64_val),
    .proj_row_65_val(proj_row_65_val),
    .proj_row_66_val(proj_row_66_val),
    .proj_row_67_val(proj_row_67_val),
    .proj_row_68_val(proj_row_68_val),
    .proj_row_69_val(proj_row_69_val),
    .proj_row_70_val(proj_row_70_val),
    .proj_row_71_val(proj_row_71_val),
    .proj_row_72_val(proj_row_72_val),
    .proj_row_73_val(proj_row_73_val),
    .proj_row_74_val(proj_row_74_val),
    .proj_row_75_val(proj_row_75_val),
    .proj_row_76_val(proj_row_76_val),
    .proj_row_77_val(proj_row_77_val),
    .proj_row_78_val(proj_row_78_val),
    .proj_row_79_val(proj_row_79_val),
    .proj_row_80_val(proj_row_80_val),
    .proj_row_81_val(proj_row_81_val),
    .proj_row_82_val(proj_row_82_val),
    .proj_row_83_val(proj_row_83_val),
    .proj_row_84_val(proj_row_84_val),
    .proj_row_85_val(proj_row_85_val),
    .proj_row_86_val(proj_row_86_val),
    .proj_row_87_val(proj_row_87_val),
    .proj_row_88_val(proj_row_88_val),
    .proj_row_89_val(proj_row_89_val),
    .proj_row_90_val(proj_row_90_val),
    .proj_row_91_val(proj_row_91_val),
    .proj_row_92_val(proj_row_92_val),
    .proj_row_93_val(proj_row_93_val),
    .proj_row_94_val(proj_row_94_val),
    .proj_row_95_val(proj_row_95_val),
    .proj_row_96_val(proj_row_96_val),
    .proj_row_97_val(proj_row_97_val),
    .proj_row_98_val(proj_row_98_val),
    .proj_row_99_val(proj_row_99_val),
    .proj_row_100_val(proj_row_100_val),
    .proj_row_101_val(proj_row_101_val),
    .proj_row_102_val(proj_row_102_val),
    .proj_row_103_val(proj_row_103_val),
    .proj_row_104_val(proj_row_104_val),
    .proj_row_105_val(proj_row_105_val),
    .proj_row_106_val(proj_row_106_val),
    .proj_row_107_val(proj_row_107_val),
    .proj_row_108_val(proj_row_108_val),
    .proj_row_109_val(proj_row_109_val),
    .proj_row_110_val(proj_row_110_val),
    .proj_row_111_val(proj_row_111_val),
    .proj_row_112_val(proj_row_112_val),
    .proj_row_113_val(proj_row_113_val),
    .proj_row_114_val(proj_row_114_val),
    .proj_row_115_val(proj_row_115_val),
    .proj_row_116_val(proj_row_116_val),
    .proj_row_117_val(proj_row_117_val),
    .proj_row_118_val(proj_row_118_val),
    .proj_row_119_val(proj_row_119_val),
    .proj_row_120_val(proj_row_120_val),
    .proj_row_121_val(proj_row_121_val),
    .proj_row_122_val(proj_row_122_val),
    .proj_row_123_val(proj_row_123_val),
    .proj_row_124_val(proj_row_124_val),
    .proj_row_125_val(proj_row_125_val),
    .proj_row_126_val(proj_row_126_val),
    .proj_row_127_val(proj_row_127_val),
    .proj_row_128_val(proj_row_128_val),
    .proj_row_129_val(proj_row_129_val),
    .proj_row_130_val(proj_row_130_val),
    .proj_row_131_val(proj_row_131_val),
    .proj_row_132_val(proj_row_132_val),
    .proj_row_133_val(proj_row_133_val),
    .proj_row_134_val(proj_row_134_val),
    .proj_row_135_val(proj_row_135_val),
    .proj_row_136_val(proj_row_136_val),
    .proj_row_137_val(proj_row_137_val),
    .proj_row_138_val(proj_row_138_val),
    .proj_row_139_val(proj_row_139_val),
    .proj_row_140_val(proj_row_140_val),
    .proj_row_141_val(proj_row_141_val),
    .proj_row_142_val(proj_row_142_val),
    .proj_row_143_val(proj_row_143_val),
    .proj_row_144_val(proj_row_144_val),
    .proj_row_145_val(proj_row_145_val),
    .proj_row_146_val(proj_row_146_val),
    .proj_row_147_val(proj_row_147_val),
    .proj_row_148_val(proj_row_148_val),
    .proj_row_149_val(proj_row_149_val),
    .proj_row_150_val(proj_row_150_val),
    .proj_row_151_val(proj_row_151_val),
    .proj_row_152_val(proj_row_152_val),
    .proj_row_153_val(proj_row_153_val),
    .proj_row_154_val(proj_row_154_val),
    .proj_row_155_val(proj_row_155_val),
    .proj_row_156_val(proj_row_156_val),
    .proj_row_157_val(proj_row_157_val),
    .proj_row_158_val(proj_row_158_val),
    .proj_row_159_val(proj_row_159_val),
    .proj_row_160_val(proj_row_160_val),
    .proj_row_161_val(proj_row_161_val),
    .proj_row_162_val(proj_row_162_val),
    .proj_row_163_val(proj_row_163_val),
    .proj_row_164_val(proj_row_164_val),
    .proj_row_165_val(proj_row_165_val),
    .proj_row_166_val(proj_row_166_val),
    .proj_row_167_val(proj_row_167_val),
    .proj_row_168_val(proj_row_168_val),
    .proj_row_169_val(proj_row_169_val),
    .proj_row_170_val(proj_row_170_val),
    .proj_row_171_val(proj_row_171_val),
    .proj_row_172_val(proj_row_172_val),
    .proj_row_173_val(proj_row_173_val),
    .proj_row_174_val(proj_row_174_val),
    .proj_row_175_val(proj_row_175_val),
    .proj_row_176_val(proj_row_176_val),
    .proj_row_177_val(proj_row_177_val),
    .proj_row_178_val(proj_row_178_val),
    .proj_row_179_val(proj_row_179_val),
    .proj_row_180_val(proj_row_180_val),
    .proj_row_181_val(proj_row_181_val),
    .proj_row_182_val(proj_row_182_val),
    .proj_row_183_val(proj_row_183_val),
    .proj_row_184_val(proj_row_184_val),
    .proj_row_185_val(proj_row_185_val),
    .proj_row_186_val(proj_row_186_val),
    .proj_row_187_val(proj_row_187_val),
    .proj_row_188_val(proj_row_188_val),
    .proj_row_189_val(proj_row_189_val),
    .proj_row_190_val(proj_row_190_val),
    .proj_row_191_val(proj_row_191_val),
    .proj_row_192_val(proj_row_192_val),
    .proj_row_193_val(proj_row_193_val),
    .proj_row_194_val(proj_row_194_val),
    .proj_row_195_val(proj_row_195_val),
    .proj_row_196_val(proj_row_196_val),
    .proj_row_197_val(proj_row_197_val),
    .proj_row_198_val(proj_row_198_val),
    .proj_row_199_val(proj_row_199_val),
    .proj_row_200_val(proj_row_200_val),
    .proj_row_201_val(proj_row_201_val),
    .proj_row_202_val(proj_row_202_val),
    .proj_row_203_val(proj_row_203_val),
    .proj_row_204_val(proj_row_204_val),
    .proj_row_205_val(proj_row_205_val),
    .proj_row_206_val(proj_row_206_val),
    .proj_row_207_val(proj_row_207_val),
    .proj_row_208_val(proj_row_208_val),
    .proj_row_209_val(proj_row_209_val),
    .proj_row_210_val(proj_row_210_val),
    .proj_row_211_val(proj_row_211_val),
    .proj_row_212_val(proj_row_212_val),
    .proj_row_213_val(proj_row_213_val),
    .proj_row_214_val(proj_row_214_val),
    .proj_row_215_val(proj_row_215_val),
    .proj_row_216_val(proj_row_216_val),
    .proj_row_217_val(proj_row_217_val),
    .proj_row_218_val(proj_row_218_val),
    .proj_row_219_val(proj_row_219_val),
    .proj_row_220_val(proj_row_220_val),
    .proj_row_221_val(proj_row_221_val),
    .proj_row_222_val(proj_row_222_val),
    .proj_row_223_val(proj_row_223_val),
    .projection_request_stream_TDATA(grp_p_anonymous_namespace_CallExternalProjectionIpQ610_Pipeline_VITIS_LOOP_4565_3_fu_1929_projection_request_stream_TDATA),
    .projection_request_stream_TVALID(grp_p_anonymous_namespace_CallExternalProjectionIpQ610_Pipeline_VITIS_LOOP_4565_3_fu_1929_projection_request_stream_TVALID),
    .projection_request_stream_TKEEP(grp_p_anonymous_namespace_CallExternalProjectionIpQ610_Pipeline_VITIS_LOOP_4565_3_fu_1929_projection_request_stream_TKEEP),
    .projection_request_stream_TSTRB(grp_p_anonymous_namespace_CallExternalProjectionIpQ610_Pipeline_VITIS_LOOP_4565_3_fu_1929_projection_request_stream_TSTRB),
    .projection_request_stream_TLAST(grp_p_anonymous_namespace_CallExternalProjectionIpQ610_Pipeline_VITIS_LOOP_4565_3_fu_1929_projection_request_stream_TLAST)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_preg <= 48'd0;
    end else begin
        if (((projection_response_stream_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
            ap_return_preg <= agg_result_fu_2169_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_p_anonymous_namespace_CallExternalProjectionIpQ610_Pipeline_VITIS_LOOP_4558_1_VIT_fu_1910_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_p_anonymous_namespace_CallExternalProjectionIpQ610_Pipeline_VITIS_LOOP_4558_1_VIT_fu_1910_ap_start_reg <= 1'b1;
        end else if ((grp_p_anonymous_namespace_CallExternalProjectionIpQ610_Pipeline_VITIS_LOOP_4558_1_VIT_fu_1910_ap_ready == 1'b1)) begin
            grp_p_anonymous_namespace_CallExternalProjectionIpQ610_Pipeline_VITIS_LOOP_4558_1_VIT_fu_1910_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_p_anonymous_namespace_CallExternalProjectionIpQ610_Pipeline_VITIS_LOOP_4565_3_fu_1929_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_p_anonymous_namespace_CallExternalProjectionIpQ610_Pipeline_VITIS_LOOP_4565_3_fu_1929_ap_start_reg <= 1'b1;
        end else if ((grp_p_anonymous_namespace_CallExternalProjectionIpQ610_Pipeline_VITIS_LOOP_4565_3_fu_1929_ap_ready == 1'b1)) begin
            grp_p_anonymous_namespace_CallExternalProjectionIpQ610_Pipeline_VITIS_LOOP_4565_3_fu_1929_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        p_0_reg_3332 <= projection_response_stream_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        p_s_reg_3337 <= projection_response_stream_TDATA;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_p_anonymous_namespace_CallExternalProjectionIpQ610_Pipeline_VITIS_LOOP_4558_1_VIT_fu_1910_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_p_anonymous_namespace_CallExternalProjectionIpQ610_Pipeline_VITIS_LOOP_4565_3_fu_1929_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

always @ (*) begin
    if ((projection_response_stream_TVALID == 1'b0)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

always @ (*) begin
    if ((projection_response_stream_TVALID == 1'b0)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

always @ (*) begin
    if ((projection_response_stream_TVALID == 1'b0)) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)) | ((projection_response_stream_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state9)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((projection_response_stream_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((projection_response_stream_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        ap_return = agg_result_fu_2169_p4;
    end else begin
        ap_return = ap_return_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (grp_p_anonymous_namespace_CallExternalProjectionIpQ610_Pipeline_VITIS_LOOP_4565_3_fu_1929_projection_request_stream_TVALID == 1'b1))) begin
        projection_request_stream_TDATA = grp_p_anonymous_namespace_CallExternalProjectionIpQ610_Pipeline_VITIS_LOOP_4565_3_fu_1929_projection_request_stream_TDATA;
    end else if (((grp_p_anonymous_namespace_CallExternalProjectionIpQ610_Pipeline_VITIS_LOOP_4558_1_VIT_fu_1910_projection_request_stream_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        projection_request_stream_TDATA = grp_p_anonymous_namespace_CallExternalProjectionIpQ610_Pipeline_VITIS_LOOP_4558_1_VIT_fu_1910_projection_request_stream_TDATA;
    end else begin
        projection_request_stream_TDATA = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (grp_p_anonymous_namespace_CallExternalProjectionIpQ610_Pipeline_VITIS_LOOP_4565_3_fu_1929_projection_request_stream_TVALID == 1'b1))) begin
        projection_request_stream_TKEEP = grp_p_anonymous_namespace_CallExternalProjectionIpQ610_Pipeline_VITIS_LOOP_4565_3_fu_1929_projection_request_stream_TKEEP;
    end else if (((grp_p_anonymous_namespace_CallExternalProjectionIpQ610_Pipeline_VITIS_LOOP_4558_1_VIT_fu_1910_projection_request_stream_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        projection_request_stream_TKEEP = grp_p_anonymous_namespace_CallExternalProjectionIpQ610_Pipeline_VITIS_LOOP_4558_1_VIT_fu_1910_projection_request_stream_TKEEP;
    end else begin
        projection_request_stream_TKEEP = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (grp_p_anonymous_namespace_CallExternalProjectionIpQ610_Pipeline_VITIS_LOOP_4565_3_fu_1929_projection_request_stream_TVALID == 1'b1))) begin
        projection_request_stream_TLAST = grp_p_anonymous_namespace_CallExternalProjectionIpQ610_Pipeline_VITIS_LOOP_4565_3_fu_1929_projection_request_stream_TLAST;
    end else if (((grp_p_anonymous_namespace_CallExternalProjectionIpQ610_Pipeline_VITIS_LOOP_4558_1_VIT_fu_1910_projection_request_stream_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        projection_request_stream_TLAST = grp_p_anonymous_namespace_CallExternalProjectionIpQ610_Pipeline_VITIS_LOOP_4558_1_VIT_fu_1910_projection_request_stream_TLAST;
    end else begin
        projection_request_stream_TLAST = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (grp_p_anonymous_namespace_CallExternalProjectionIpQ610_Pipeline_VITIS_LOOP_4565_3_fu_1929_projection_request_stream_TVALID == 1'b1))) begin
        projection_request_stream_TSTRB = grp_p_anonymous_namespace_CallExternalProjectionIpQ610_Pipeline_VITIS_LOOP_4565_3_fu_1929_projection_request_stream_TSTRB;
    end else if (((grp_p_anonymous_namespace_CallExternalProjectionIpQ610_Pipeline_VITIS_LOOP_4558_1_VIT_fu_1910_projection_request_stream_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        projection_request_stream_TSTRB = grp_p_anonymous_namespace_CallExternalProjectionIpQ610_Pipeline_VITIS_LOOP_4558_1_VIT_fu_1910_projection_request_stream_TSTRB;
    end else begin
        projection_request_stream_TSTRB = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        projection_request_stream_TVALID = grp_p_anonymous_namespace_CallExternalProjectionIpQ610_Pipeline_VITIS_LOOP_4565_3_fu_1929_projection_request_stream_TVALID;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        projection_request_stream_TVALID = grp_p_anonymous_namespace_CallExternalProjectionIpQ610_Pipeline_VITIS_LOOP_4558_1_VIT_fu_1910_projection_request_stream_TVALID;
    end else begin
        projection_request_stream_TVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7))) begin
        projection_response_stream_TDATA_blk_n = projection_response_stream_TVALID;
    end else begin
        projection_response_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((projection_response_stream_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state9)) | ((projection_response_stream_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state8)) | ((projection_response_stream_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state7)))) begin
        projection_response_stream_TREADY = 1'b1;
    end else begin
        projection_response_stream_TREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_p_anonymous_namespace_CallExternalProjectionIpQ610_Pipeline_VITIS_LOOP_4558_1_VIT_fu_1910_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((grp_p_anonymous_namespace_CallExternalProjectionIpQ610_Pipeline_VITIS_LOOP_4565_3_fu_1929_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            if (((projection_response_stream_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            if (((projection_response_stream_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            if (((projection_response_stream_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign agg_result_fu_2169_p4 = {{{projection_response_stream_TDATA}, {p_s_reg_3337}}, {p_0_reg_3332}};

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign grp_p_anonymous_namespace_CallExternalProjectionIpQ610_Pipeline_VITIS_LOOP_4558_1_VIT_fu_1910_ap_start = grp_p_anonymous_namespace_CallExternalProjectionIpQ610_Pipeline_VITIS_LOOP_4558_1_VIT_fu_1910_ap_start_reg;

assign grp_p_anonymous_namespace_CallExternalProjectionIpQ610_Pipeline_VITIS_LOOP_4558_1_VIT_fu_1910_projection_request_stream_TREADY = (projection_request_stream_TREADY & ap_CS_fsm_state3);

assign grp_p_anonymous_namespace_CallExternalProjectionIpQ610_Pipeline_VITIS_LOOP_4565_3_fu_1929_ap_start = grp_p_anonymous_namespace_CallExternalProjectionIpQ610_Pipeline_VITIS_LOOP_4565_3_fu_1929_ap_start_reg;

assign grp_p_anonymous_namespace_CallExternalProjectionIpQ610_Pipeline_VITIS_LOOP_4565_3_fu_1929_projection_request_stream_TREADY = (projection_request_stream_TREADY & ap_CS_fsm_state6);

endmodule //SubbandRealtimeTopQ610Ip_p_anonymous_namespace_CallExternalProjectionIpQ610
