// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module SubbandRealtimeTopQ610Ip_p_anonymous_namespace_CallExternalProjectionIpQ610_Pipeline_VITIS_LOOP_4558_1_VIT (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        projection_request_stream_TREADY,
        input_tiles_0_val,
        input_tiles_1_val,
        input_tiles_2_val,
        input_tiles_3_val,
        input_tiles_4_val,
        input_tiles_5_val,
        input_tiles_6_val,
        projection_request_stream_TDATA,
        projection_request_stream_TVALID,
        projection_request_stream_TKEEP,
        projection_request_stream_TSTRB,
        projection_request_stream_TLAST
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   projection_request_stream_TREADY;
input  [511:0] input_tiles_0_val;
input  [511:0] input_tiles_1_val;
input  [511:0] input_tiles_2_val;
input  [511:0] input_tiles_3_val;
input  [511:0] input_tiles_4_val;
input  [511:0] input_tiles_5_val;
input  [511:0] input_tiles_6_val;
output  [15:0] projection_request_stream_TDATA;
output   projection_request_stream_TVALID;
output  [1:0] projection_request_stream_TKEEP;
output  [1:0] projection_request_stream_TSTRB;
output  [0:0] projection_request_stream_TLAST;

reg ap_idle;
reg projection_request_stream_TVALID;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln4558_fu_185_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    projection_request_stream_TDATA_blk_n;
wire    ap_block_pp0_stage0;
wire   [511:0] tmp_fu_231_p17;
reg   [511:0] tmp_reg_337;
reg    ap_block_pp0_stage0_11001;
wire   [4:0] trunc_ln22_fu_267_p1;
reg   [4:0] trunc_ln22_reg_342;
reg   [5:0] lane_fu_94;
wire   [5:0] lane_1_fu_271_p2;
wire    ap_loop_init;
reg   [5:0] ap_sig_allocacmp_lane_load;
reg   [2:0] tile_index_fu_98;
wire   [2:0] select_ln4558_1_fu_223_p3;
reg   [2:0] ap_sig_allocacmp_tile_index_load;
reg   [7:0] indvar_flatten_fu_102;
wire   [7:0] add_ln4558_1_fu_191_p2;
reg   [7:0] ap_sig_allocacmp_indvar_flatten_load;
reg    ap_block_pp0_stage0_01001;
wire   [0:0] icmp_ln4559_fu_209_p2;
wire   [2:0] add_ln4558_fu_203_p2;
wire   [511:0] tmp_fu_231_p15;
wire   [2:0] tmp_fu_231_p16;
wire   [5:0] select_ln4558_fu_215_p3;
wire   [8:0] shl_ln_fu_292_p3;
wire   [511:0] zext_ln22_fu_299_p1;
wire   [511:0] lshr_ln22_fu_303_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [2:0] tmp_fu_231_p1;
wire   [2:0] tmp_fu_231_p3;
wire   [2:0] tmp_fu_231_p5;
wire   [2:0] tmp_fu_231_p7;
wire  signed [2:0] tmp_fu_231_p9;
wire  signed [2:0] tmp_fu_231_p11;
wire  signed [2:0] tmp_fu_231_p13;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 lane_fu_94 = 6'd0;
#0 tile_index_fu_98 = 3'd0;
#0 indvar_flatten_fu_102 = 8'd0;
#0 ap_done_reg = 1'b0;
end

SubbandRealtimeTopQ610Ip_sparsemux_15_3_512_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 512 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 512 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 512 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 512 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 512 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 512 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 512 ),
    .def_WIDTH( 512 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 512 ))
sparsemux_15_3_512_1_1_U556(
    .din0(input_tiles_0_val),
    .din1(input_tiles_1_val),
    .din2(input_tiles_2_val),
    .din3(input_tiles_3_val),
    .din4(input_tiles_4_val),
    .din5(input_tiles_5_val),
    .din6(input_tiles_6_val),
    .def(tmp_fu_231_p15),
    .sel(tmp_fu_231_p16),
    .dout(tmp_fu_231_p17)
);

SubbandRealtimeTopQ610Ip_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln4558_fu_185_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten_fu_102 <= add_ln4558_1_fu_191_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_102 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln4558_fu_185_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            lane_fu_94 <= lane_1_fu_271_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            lane_fu_94 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln4558_fu_185_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            tile_index_fu_98 <= select_ln4558_1_fu_223_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            tile_index_fu_98 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_reg_337 <= tmp_fu_231_p17;
        trunc_ln22_reg_342 <= trunc_ln22_fu_267_p1;
    end
end

always @ (*) begin
    if (((icmp_ln4558_fu_185_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten_load = 8'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_102;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_lane_load = 6'd0;
    end else begin
        ap_sig_allocacmp_lane_load = lane_fu_94;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_tile_index_load = 3'd0;
    end else begin
        ap_sig_allocacmp_tile_index_load = tile_index_fu_98;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        projection_request_stream_TDATA_blk_n = projection_request_stream_TREADY;
    end else begin
        projection_request_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        projection_request_stream_TVALID = 1'b1;
    end else begin
        projection_request_stream_TVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln4558_1_fu_191_p2 = (ap_sig_allocacmp_indvar_flatten_load + 8'd1);

assign add_ln4558_fu_203_p2 = (ap_sig_allocacmp_tile_index_load + 3'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & ((projection_request_stream_TREADY == 1'b0) | (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & ((projection_request_stream_TREADY == 1'b0) | (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (projection_request_stream_TREADY == 1'b0);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln4558_fu_185_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 8'd224) ? 1'b1 : 1'b0);

assign icmp_ln4559_fu_209_p2 = ((ap_sig_allocacmp_lane_load == 6'd32) ? 1'b1 : 1'b0);

assign lane_1_fu_271_p2 = (select_ln4558_fu_215_p3 + 6'd1);

assign lshr_ln22_fu_303_p2 = tmp_reg_337 >> zext_ln22_fu_299_p1;

assign projection_request_stream_TDATA = lshr_ln22_fu_303_p2[15:0];

assign projection_request_stream_TKEEP = 2'd3;

assign projection_request_stream_TLAST = 1'd0;

assign projection_request_stream_TSTRB = 2'd3;

assign select_ln4558_1_fu_223_p3 = ((icmp_ln4559_fu_209_p2[0:0] == 1'b1) ? add_ln4558_fu_203_p2 : ap_sig_allocacmp_tile_index_load);

assign select_ln4558_fu_215_p3 = ((icmp_ln4559_fu_209_p2[0:0] == 1'b1) ? 6'd0 : ap_sig_allocacmp_lane_load);

assign shl_ln_fu_292_p3 = {{trunc_ln22_reg_342}, {4'd0}};

assign tmp_fu_231_p15 = 'bx;

assign tmp_fu_231_p16 = ((icmp_ln4559_fu_209_p2[0:0] == 1'b1) ? add_ln4558_fu_203_p2 : ap_sig_allocacmp_tile_index_load);

assign trunc_ln22_fu_267_p1 = select_ln4558_fu_215_p3[4:0];

assign zext_ln22_fu_299_p1 = shl_ln_fu_292_p3;

endmodule //SubbandRealtimeTopQ610Ip_p_anonymous_namespace_CallExternalProjectionIpQ610_Pipeline_VITIS_LOOP_4558_1_VIT
