// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module SubbandRealtimeTopQ610Ip_p_anonymous_namespace_ClearRealtimePackedStatesQ610 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        sv_layer0_hx_state_tiles_address1,
        sv_layer0_hx_state_tiles_ce1,
        sv_layer0_hx_state_tiles_we1,
        sv_layer0_hx_state_tiles_d1,
        sv_layer0_cx_state_tiles_address1,
        sv_layer0_cx_state_tiles_ce1,
        sv_layer0_cx_state_tiles_we1,
        sv_layer0_cx_state_tiles_d1,
        sv_layer1_hx_state_tiles_address1,
        sv_layer1_hx_state_tiles_ce1,
        sv_layer1_hx_state_tiles_we1,
        sv_layer1_hx_state_tiles_d1,
        sv_layer1_cx_state_tiles_address1,
        sv_layer1_cx_state_tiles_ce1,
        sv_layer1_cx_state_tiles_we1,
        sv_layer1_cx_state_tiles_d1
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [6:0] sv_layer0_hx_state_tiles_address1;
output   sv_layer0_hx_state_tiles_ce1;
output   sv_layer0_hx_state_tiles_we1;
output  [511:0] sv_layer0_hx_state_tiles_d1;
output  [6:0] sv_layer0_cx_state_tiles_address1;
output   sv_layer0_cx_state_tiles_ce1;
output   sv_layer0_cx_state_tiles_we1;
output  [511:0] sv_layer0_cx_state_tiles_d1;
output  [6:0] sv_layer1_hx_state_tiles_address1;
output   sv_layer1_hx_state_tiles_ce1;
output   sv_layer1_hx_state_tiles_we1;
output  [511:0] sv_layer1_hx_state_tiles_d1;
output  [6:0] sv_layer1_cx_state_tiles_address1;
output   sv_layer1_cx_state_tiles_ce1;
output   sv_layer1_cx_state_tiles_we1;
output  [511:0] sv_layer1_cx_state_tiles_d1;

reg ap_idle;
reg sv_layer0_hx_state_tiles_ce1;
reg sv_layer0_hx_state_tiles_we1;
reg sv_layer0_cx_state_tiles_ce1;
reg sv_layer0_cx_state_tiles_we1;
reg sv_layer1_hx_state_tiles_ce1;
reg sv_layer1_hx_state_tiles_we1;
reg sv_layer1_cx_state_tiles_ce1;
reg sv_layer1_cx_state_tiles_we1;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln3481_fu_124_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [31:0] zext_ln3483_fu_136_p1;
reg   [6:0] tile_index_fu_40;
wire   [6:0] add_ln3481_fu_130_p2;
wire    ap_loop_init;
reg   [6:0] ap_sig_allocacmp_tile_index_3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 tile_index_fu_40 = 7'd0;
#0 ap_done_reg = 1'b0;
end

SubbandRealtimeTopQ610Ip_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((icmp_ln3481_fu_124_p2 == 1'd0)) begin
            tile_index_fu_40 <= add_ln3481_fu_130_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            tile_index_fu_40 <= 7'd0;
        end
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln3481_fu_124_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_tile_index_3 = 7'd0;
    end else begin
        ap_sig_allocacmp_tile_index_3 = tile_index_fu_40;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        sv_layer0_cx_state_tiles_ce1 = 1'b1;
    end else begin
        sv_layer0_cx_state_tiles_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln3481_fu_124_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        sv_layer0_cx_state_tiles_we1 = 1'b1;
    end else begin
        sv_layer0_cx_state_tiles_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        sv_layer0_hx_state_tiles_ce1 = 1'b1;
    end else begin
        sv_layer0_hx_state_tiles_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln3481_fu_124_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        sv_layer0_hx_state_tiles_we1 = 1'b1;
    end else begin
        sv_layer0_hx_state_tiles_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        sv_layer1_cx_state_tiles_ce1 = 1'b1;
    end else begin
        sv_layer1_cx_state_tiles_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln3481_fu_124_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        sv_layer1_cx_state_tiles_we1 = 1'b1;
    end else begin
        sv_layer1_cx_state_tiles_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        sv_layer1_hx_state_tiles_ce1 = 1'b1;
    end else begin
        sv_layer1_hx_state_tiles_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln3481_fu_124_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        sv_layer1_hx_state_tiles_we1 = 1'b1;
    end else begin
        sv_layer1_hx_state_tiles_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln3481_fu_130_p2 = (ap_sig_allocacmp_tile_index_3 + 7'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln3481_fu_124_p2 = ((ap_sig_allocacmp_tile_index_3 == 7'd91) ? 1'b1 : 1'b0);

assign sv_layer0_cx_state_tiles_address1 = zext_ln3483_fu_136_p1;

assign sv_layer0_cx_state_tiles_d1 = 512'd0;

assign sv_layer0_hx_state_tiles_address1 = zext_ln3483_fu_136_p1;

assign sv_layer0_hx_state_tiles_d1 = 512'd0;

assign sv_layer1_cx_state_tiles_address1 = zext_ln3483_fu_136_p1;

assign sv_layer1_cx_state_tiles_d1 = 512'd0;

assign sv_layer1_hx_state_tiles_address1 = zext_ln3483_fu_136_p1;

assign sv_layer1_hx_state_tiles_d1 = 512'd0;

assign zext_ln3483_fu_136_p1 = ap_sig_allocacmp_tile_index_3;

endmodule //SubbandRealtimeTopQ610Ip_p_anonymous_namespace_ClearRealtimePackedStatesQ610
