// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module SubbandRealtimeTopQ610Ip_p_anonymous_namespace_CallExternalProjectionIpQ610_Pipeline_VITIS_LOOP_4565_3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        projection_request_stream_TREADY,
        proj_row_0_val,
        proj_row_1_val,
        proj_row_2_val,
        proj_row_3_val,
        proj_row_4_val,
        proj_row_5_val,
        proj_row_6_val,
        proj_row_7_val,
        proj_row_8_val,
        proj_row_9_val,
        proj_row_10_val,
        proj_row_11_val,
        proj_row_12_val,
        proj_row_13_val,
        proj_row_14_val,
        proj_row_15_val,
        proj_row_16_val,
        proj_row_17_val,
        proj_row_18_val,
        proj_row_19_val,
        proj_row_20_val,
        proj_row_21_val,
        proj_row_22_val,
        proj_row_23_val,
        proj_row_24_val,
        proj_row_25_val,
        proj_row_26_val,
        proj_row_27_val,
        proj_row_28_val,
        proj_row_29_val,
        proj_row_30_val,
        proj_row_31_val,
        proj_row_32_val,
        proj_row_33_val,
        proj_row_34_val,
        proj_row_35_val,
        proj_row_36_val,
        proj_row_37_val,
        proj_row_38_val,
        proj_row_39_val,
        proj_row_40_val,
        proj_row_41_val,
        proj_row_42_val,
        proj_row_43_val,
        proj_row_44_val,
        proj_row_45_val,
        proj_row_46_val,
        proj_row_47_val,
        proj_row_48_val,
        proj_row_49_val,
        proj_row_50_val,
        proj_row_51_val,
        proj_row_52_val,
        proj_row_53_val,
        proj_row_54_val,
        proj_row_55_val,
        proj_row_56_val,
        proj_row_57_val,
        proj_row_58_val,
        proj_row_59_val,
        proj_row_60_val,
        proj_row_61_val,
        proj_row_62_val,
        proj_row_63_val,
        proj_row_64_val,
        proj_row_65_val,
        proj_row_66_val,
        proj_row_67_val,
        proj_row_68_val,
        proj_row_69_val,
        proj_row_70_val,
        proj_row_71_val,
        proj_row_72_val,
        proj_row_73_val,
        proj_row_74_val,
        proj_row_75_val,
        proj_row_76_val,
        proj_row_77_val,
        proj_row_78_val,
        proj_row_79_val,
        proj_row_80_val,
        proj_row_81_val,
        proj_row_82_val,
        proj_row_83_val,
        proj_row_84_val,
        proj_row_85_val,
        proj_row_86_val,
        proj_row_87_val,
        proj_row_88_val,
        proj_row_89_val,
        proj_row_90_val,
        proj_row_91_val,
        proj_row_92_val,
        proj_row_93_val,
        proj_row_94_val,
        proj_row_95_val,
        proj_row_96_val,
        proj_row_97_val,
        proj_row_98_val,
        proj_row_99_val,
        proj_row_100_val,
        proj_row_101_val,
        proj_row_102_val,
        proj_row_103_val,
        proj_row_104_val,
        proj_row_105_val,
        proj_row_106_val,
        proj_row_107_val,
        proj_row_108_val,
        proj_row_109_val,
        proj_row_110_val,
        proj_row_111_val,
        proj_row_112_val,
        proj_row_113_val,
        proj_row_114_val,
        proj_row_115_val,
        proj_row_116_val,
        proj_row_117_val,
        proj_row_118_val,
        proj_row_119_val,
        proj_row_120_val,
        proj_row_121_val,
        proj_row_122_val,
        proj_row_123_val,
        proj_row_124_val,
        proj_row_125_val,
        proj_row_126_val,
        proj_row_127_val,
        proj_row_128_val,
        proj_row_129_val,
        proj_row_130_val,
        proj_row_131_val,
        proj_row_132_val,
        proj_row_133_val,
        proj_row_134_val,
        proj_row_135_val,
        proj_row_136_val,
        proj_row_137_val,
        proj_row_138_val,
        proj_row_139_val,
        proj_row_140_val,
        proj_row_141_val,
        proj_row_142_val,
        proj_row_143_val,
        proj_row_144_val,
        proj_row_145_val,
        proj_row_146_val,
        proj_row_147_val,
        proj_row_148_val,
        proj_row_149_val,
        proj_row_150_val,
        proj_row_151_val,
        proj_row_152_val,
        proj_row_153_val,
        proj_row_154_val,
        proj_row_155_val,
        proj_row_156_val,
        proj_row_157_val,
        proj_row_158_val,
        proj_row_159_val,
        proj_row_160_val,
        proj_row_161_val,
        proj_row_162_val,
        proj_row_163_val,
        proj_row_164_val,
        proj_row_165_val,
        proj_row_166_val,
        proj_row_167_val,
        proj_row_168_val,
        proj_row_169_val,
        proj_row_170_val,
        proj_row_171_val,
        proj_row_172_val,
        proj_row_173_val,
        proj_row_174_val,
        proj_row_175_val,
        proj_row_176_val,
        proj_row_177_val,
        proj_row_178_val,
        proj_row_179_val,
        proj_row_180_val,
        proj_row_181_val,
        proj_row_182_val,
        proj_row_183_val,
        proj_row_184_val,
        proj_row_185_val,
        proj_row_186_val,
        proj_row_187_val,
        proj_row_188_val,
        proj_row_189_val,
        proj_row_190_val,
        proj_row_191_val,
        proj_row_192_val,
        proj_row_193_val,
        proj_row_194_val,
        proj_row_195_val,
        proj_row_196_val,
        proj_row_197_val,
        proj_row_198_val,
        proj_row_199_val,
        proj_row_200_val,
        proj_row_201_val,
        proj_row_202_val,
        proj_row_203_val,
        proj_row_204_val,
        proj_row_205_val,
        proj_row_206_val,
        proj_row_207_val,
        proj_row_208_val,
        proj_row_209_val,
        proj_row_210_val,
        proj_row_211_val,
        proj_row_212_val,
        proj_row_213_val,
        proj_row_214_val,
        proj_row_215_val,
        proj_row_216_val,
        proj_row_217_val,
        proj_row_218_val,
        proj_row_219_val,
        proj_row_220_val,
        proj_row_221_val,
        proj_row_222_val,
        proj_row_223_val,
        projection_request_stream_TDATA,
        projection_request_stream_TVALID,
        projection_request_stream_TKEEP,
        projection_request_stream_TSTRB,
        projection_request_stream_TLAST
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   projection_request_stream_TREADY;
input  [15:0] proj_row_0_val;
input  [15:0] proj_row_1_val;
input  [15:0] proj_row_2_val;
input  [15:0] proj_row_3_val;
input  [15:0] proj_row_4_val;
input  [15:0] proj_row_5_val;
input  [15:0] proj_row_6_val;
input  [15:0] proj_row_7_val;
input  [15:0] proj_row_8_val;
input  [15:0] proj_row_9_val;
input  [15:0] proj_row_10_val;
input  [15:0] proj_row_11_val;
input  [15:0] proj_row_12_val;
input  [15:0] proj_row_13_val;
input  [15:0] proj_row_14_val;
input  [15:0] proj_row_15_val;
input  [15:0] proj_row_16_val;
input  [15:0] proj_row_17_val;
input  [15:0] proj_row_18_val;
input  [15:0] proj_row_19_val;
input  [15:0] proj_row_20_val;
input  [15:0] proj_row_21_val;
input  [15:0] proj_row_22_val;
input  [15:0] proj_row_23_val;
input  [15:0] proj_row_24_val;
input  [15:0] proj_row_25_val;
input  [15:0] proj_row_26_val;
input  [15:0] proj_row_27_val;
input  [15:0] proj_row_28_val;
input  [15:0] proj_row_29_val;
input  [15:0] proj_row_30_val;
input  [15:0] proj_row_31_val;
input  [15:0] proj_row_32_val;
input  [15:0] proj_row_33_val;
input  [15:0] proj_row_34_val;
input  [15:0] proj_row_35_val;
input  [15:0] proj_row_36_val;
input  [15:0] proj_row_37_val;
input  [15:0] proj_row_38_val;
input  [15:0] proj_row_39_val;
input  [15:0] proj_row_40_val;
input  [15:0] proj_row_41_val;
input  [15:0] proj_row_42_val;
input  [15:0] proj_row_43_val;
input  [15:0] proj_row_44_val;
input  [15:0] proj_row_45_val;
input  [15:0] proj_row_46_val;
input  [15:0] proj_row_47_val;
input  [15:0] proj_row_48_val;
input  [15:0] proj_row_49_val;
input  [15:0] proj_row_50_val;
input  [15:0] proj_row_51_val;
input  [15:0] proj_row_52_val;
input  [15:0] proj_row_53_val;
input  [15:0] proj_row_54_val;
input  [15:0] proj_row_55_val;
input  [15:0] proj_row_56_val;
input  [15:0] proj_row_57_val;
input  [15:0] proj_row_58_val;
input  [15:0] proj_row_59_val;
input  [15:0] proj_row_60_val;
input  [15:0] proj_row_61_val;
input  [15:0] proj_row_62_val;
input  [15:0] proj_row_63_val;
input  [15:0] proj_row_64_val;
input  [15:0] proj_row_65_val;
input  [15:0] proj_row_66_val;
input  [15:0] proj_row_67_val;
input  [15:0] proj_row_68_val;
input  [15:0] proj_row_69_val;
input  [15:0] proj_row_70_val;
input  [15:0] proj_row_71_val;
input  [15:0] proj_row_72_val;
input  [15:0] proj_row_73_val;
input  [15:0] proj_row_74_val;
input  [15:0] proj_row_75_val;
input  [15:0] proj_row_76_val;
input  [15:0] proj_row_77_val;
input  [15:0] proj_row_78_val;
input  [15:0] proj_row_79_val;
input  [15:0] proj_row_80_val;
input  [15:0] proj_row_81_val;
input  [15:0] proj_row_82_val;
input  [15:0] proj_row_83_val;
input  [15:0] proj_row_84_val;
input  [15:0] proj_row_85_val;
input  [15:0] proj_row_86_val;
input  [15:0] proj_row_87_val;
input  [15:0] proj_row_88_val;
input  [15:0] proj_row_89_val;
input  [15:0] proj_row_90_val;
input  [15:0] proj_row_91_val;
input  [15:0] proj_row_92_val;
input  [15:0] proj_row_93_val;
input  [15:0] proj_row_94_val;
input  [15:0] proj_row_95_val;
input  [15:0] proj_row_96_val;
input  [15:0] proj_row_97_val;
input  [15:0] proj_row_98_val;
input  [15:0] proj_row_99_val;
input  [15:0] proj_row_100_val;
input  [15:0] proj_row_101_val;
input  [15:0] proj_row_102_val;
input  [15:0] proj_row_103_val;
input  [15:0] proj_row_104_val;
input  [15:0] proj_row_105_val;
input  [15:0] proj_row_106_val;
input  [15:0] proj_row_107_val;
input  [15:0] proj_row_108_val;
input  [15:0] proj_row_109_val;
input  [15:0] proj_row_110_val;
input  [15:0] proj_row_111_val;
input  [15:0] proj_row_112_val;
input  [15:0] proj_row_113_val;
input  [15:0] proj_row_114_val;
input  [15:0] proj_row_115_val;
input  [15:0] proj_row_116_val;
input  [15:0] proj_row_117_val;
input  [15:0] proj_row_118_val;
input  [15:0] proj_row_119_val;
input  [15:0] proj_row_120_val;
input  [15:0] proj_row_121_val;
input  [15:0] proj_row_122_val;
input  [15:0] proj_row_123_val;
input  [15:0] proj_row_124_val;
input  [15:0] proj_row_125_val;
input  [15:0] proj_row_126_val;
input  [15:0] proj_row_127_val;
input  [15:0] proj_row_128_val;
input  [15:0] proj_row_129_val;
input  [15:0] proj_row_130_val;
input  [15:0] proj_row_131_val;
input  [15:0] proj_row_132_val;
input  [15:0] proj_row_133_val;
input  [15:0] proj_row_134_val;
input  [15:0] proj_row_135_val;
input  [15:0] proj_row_136_val;
input  [15:0] proj_row_137_val;
input  [15:0] proj_row_138_val;
input  [15:0] proj_row_139_val;
input  [15:0] proj_row_140_val;
input  [15:0] proj_row_141_val;
input  [15:0] proj_row_142_val;
input  [15:0] proj_row_143_val;
input  [15:0] proj_row_144_val;
input  [15:0] proj_row_145_val;
input  [15:0] proj_row_146_val;
input  [15:0] proj_row_147_val;
input  [15:0] proj_row_148_val;
input  [15:0] proj_row_149_val;
input  [15:0] proj_row_150_val;
input  [15:0] proj_row_151_val;
input  [15:0] proj_row_152_val;
input  [15:0] proj_row_153_val;
input  [15:0] proj_row_154_val;
input  [15:0] proj_row_155_val;
input  [15:0] proj_row_156_val;
input  [15:0] proj_row_157_val;
input  [15:0] proj_row_158_val;
input  [15:0] proj_row_159_val;
input  [15:0] proj_row_160_val;
input  [15:0] proj_row_161_val;
input  [15:0] proj_row_162_val;
input  [15:0] proj_row_163_val;
input  [15:0] proj_row_164_val;
input  [15:0] proj_row_165_val;
input  [15:0] proj_row_166_val;
input  [15:0] proj_row_167_val;
input  [15:0] proj_row_168_val;
input  [15:0] proj_row_169_val;
input  [15:0] proj_row_170_val;
input  [15:0] proj_row_171_val;
input  [15:0] proj_row_172_val;
input  [15:0] proj_row_173_val;
input  [15:0] proj_row_174_val;
input  [15:0] proj_row_175_val;
input  [15:0] proj_row_176_val;
input  [15:0] proj_row_177_val;
input  [15:0] proj_row_178_val;
input  [15:0] proj_row_179_val;
input  [15:0] proj_row_180_val;
input  [15:0] proj_row_181_val;
input  [15:0] proj_row_182_val;
input  [15:0] proj_row_183_val;
input  [15:0] proj_row_184_val;
input  [15:0] proj_row_185_val;
input  [15:0] proj_row_186_val;
input  [15:0] proj_row_187_val;
input  [15:0] proj_row_188_val;
input  [15:0] proj_row_189_val;
input  [15:0] proj_row_190_val;
input  [15:0] proj_row_191_val;
input  [15:0] proj_row_192_val;
input  [15:0] proj_row_193_val;
input  [15:0] proj_row_194_val;
input  [15:0] proj_row_195_val;
input  [15:0] proj_row_196_val;
input  [15:0] proj_row_197_val;
input  [15:0] proj_row_198_val;
input  [15:0] proj_row_199_val;
input  [15:0] proj_row_200_val;
input  [15:0] proj_row_201_val;
input  [15:0] proj_row_202_val;
input  [15:0] proj_row_203_val;
input  [15:0] proj_row_204_val;
input  [15:0] proj_row_205_val;
input  [15:0] proj_row_206_val;
input  [15:0] proj_row_207_val;
input  [15:0] proj_row_208_val;
input  [15:0] proj_row_209_val;
input  [15:0] proj_row_210_val;
input  [15:0] proj_row_211_val;
input  [15:0] proj_row_212_val;
input  [15:0] proj_row_213_val;
input  [15:0] proj_row_214_val;
input  [15:0] proj_row_215_val;
input  [15:0] proj_row_216_val;
input  [15:0] proj_row_217_val;
input  [15:0] proj_row_218_val;
input  [15:0] proj_row_219_val;
input  [15:0] proj_row_220_val;
input  [15:0] proj_row_221_val;
input  [15:0] proj_row_222_val;
input  [15:0] proj_row_223_val;
output  [15:0] projection_request_stream_TDATA;
output   projection_request_stream_TVALID;
output  [1:0] projection_request_stream_TKEEP;
output  [1:0] projection_request_stream_TSTRB;
output  [0:0] projection_request_stream_TLAST;

reg ap_idle;
reg projection_request_stream_TVALID;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln4565_fu_2320_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    projection_request_stream_TDATA_blk_n;
wire    ap_block_pp0_stage0;
wire   [0:0] is_last_fu_2332_p2;
reg   [0:0] is_last_reg_3257;
reg    ap_block_pp0_stage0_11001;
wire   [15:0] value_fu_2338_p451;
reg   [15:0] value_reg_3262;
reg   [7:0] hidden_index_fu_946;
wire   [7:0] add_ln4565_fu_2326_p2;
wire    ap_loop_init;
reg   [7:0] ap_sig_allocacmp_hidden_index_1;
reg    ap_block_pp0_stage0_01001;
wire   [15:0] value_fu_2338_p449;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [7:0] value_fu_2338_p1;
wire   [7:0] value_fu_2338_p3;
wire   [7:0] value_fu_2338_p5;
wire   [7:0] value_fu_2338_p7;
wire   [7:0] value_fu_2338_p9;
wire   [7:0] value_fu_2338_p11;
wire   [7:0] value_fu_2338_p13;
wire   [7:0] value_fu_2338_p15;
wire   [7:0] value_fu_2338_p17;
wire   [7:0] value_fu_2338_p19;
wire   [7:0] value_fu_2338_p21;
wire   [7:0] value_fu_2338_p23;
wire   [7:0] value_fu_2338_p25;
wire   [7:0] value_fu_2338_p27;
wire   [7:0] value_fu_2338_p29;
wire   [7:0] value_fu_2338_p31;
wire   [7:0] value_fu_2338_p33;
wire   [7:0] value_fu_2338_p35;
wire   [7:0] value_fu_2338_p37;
wire   [7:0] value_fu_2338_p39;
wire   [7:0] value_fu_2338_p41;
wire   [7:0] value_fu_2338_p43;
wire   [7:0] value_fu_2338_p45;
wire   [7:0] value_fu_2338_p47;
wire   [7:0] value_fu_2338_p49;
wire   [7:0] value_fu_2338_p51;
wire   [7:0] value_fu_2338_p53;
wire   [7:0] value_fu_2338_p55;
wire   [7:0] value_fu_2338_p57;
wire   [7:0] value_fu_2338_p59;
wire   [7:0] value_fu_2338_p61;
wire   [7:0] value_fu_2338_p63;
wire   [7:0] value_fu_2338_p65;
wire   [7:0] value_fu_2338_p67;
wire   [7:0] value_fu_2338_p69;
wire   [7:0] value_fu_2338_p71;
wire   [7:0] value_fu_2338_p73;
wire   [7:0] value_fu_2338_p75;
wire   [7:0] value_fu_2338_p77;
wire   [7:0] value_fu_2338_p79;
wire   [7:0] value_fu_2338_p81;
wire   [7:0] value_fu_2338_p83;
wire   [7:0] value_fu_2338_p85;
wire   [7:0] value_fu_2338_p87;
wire   [7:0] value_fu_2338_p89;
wire   [7:0] value_fu_2338_p91;
wire   [7:0] value_fu_2338_p93;
wire   [7:0] value_fu_2338_p95;
wire   [7:0] value_fu_2338_p97;
wire   [7:0] value_fu_2338_p99;
wire   [7:0] value_fu_2338_p101;
wire   [7:0] value_fu_2338_p103;
wire   [7:0] value_fu_2338_p105;
wire   [7:0] value_fu_2338_p107;
wire   [7:0] value_fu_2338_p109;
wire   [7:0] value_fu_2338_p111;
wire   [7:0] value_fu_2338_p113;
wire   [7:0] value_fu_2338_p115;
wire   [7:0] value_fu_2338_p117;
wire   [7:0] value_fu_2338_p119;
wire   [7:0] value_fu_2338_p121;
wire   [7:0] value_fu_2338_p123;
wire   [7:0] value_fu_2338_p125;
wire   [7:0] value_fu_2338_p127;
wire   [7:0] value_fu_2338_p129;
wire   [7:0] value_fu_2338_p131;
wire   [7:0] value_fu_2338_p133;
wire   [7:0] value_fu_2338_p135;
wire   [7:0] value_fu_2338_p137;
wire   [7:0] value_fu_2338_p139;
wire   [7:0] value_fu_2338_p141;
wire   [7:0] value_fu_2338_p143;
wire   [7:0] value_fu_2338_p145;
wire   [7:0] value_fu_2338_p147;
wire   [7:0] value_fu_2338_p149;
wire   [7:0] value_fu_2338_p151;
wire   [7:0] value_fu_2338_p153;
wire   [7:0] value_fu_2338_p155;
wire   [7:0] value_fu_2338_p157;
wire   [7:0] value_fu_2338_p159;
wire   [7:0] value_fu_2338_p161;
wire   [7:0] value_fu_2338_p163;
wire   [7:0] value_fu_2338_p165;
wire   [7:0] value_fu_2338_p167;
wire   [7:0] value_fu_2338_p169;
wire   [7:0] value_fu_2338_p171;
wire   [7:0] value_fu_2338_p173;
wire   [7:0] value_fu_2338_p175;
wire   [7:0] value_fu_2338_p177;
wire   [7:0] value_fu_2338_p179;
wire   [7:0] value_fu_2338_p181;
wire   [7:0] value_fu_2338_p183;
wire   [7:0] value_fu_2338_p185;
wire   [7:0] value_fu_2338_p187;
wire   [7:0] value_fu_2338_p189;
wire   [7:0] value_fu_2338_p191;
wire   [7:0] value_fu_2338_p193;
wire   [7:0] value_fu_2338_p195;
wire   [7:0] value_fu_2338_p197;
wire   [7:0] value_fu_2338_p199;
wire   [7:0] value_fu_2338_p201;
wire   [7:0] value_fu_2338_p203;
wire   [7:0] value_fu_2338_p205;
wire   [7:0] value_fu_2338_p207;
wire   [7:0] value_fu_2338_p209;
wire   [7:0] value_fu_2338_p211;
wire   [7:0] value_fu_2338_p213;
wire   [7:0] value_fu_2338_p215;
wire   [7:0] value_fu_2338_p217;
wire   [7:0] value_fu_2338_p219;
wire   [7:0] value_fu_2338_p221;
wire   [7:0] value_fu_2338_p223;
wire   [7:0] value_fu_2338_p225;
wire   [7:0] value_fu_2338_p227;
wire   [7:0] value_fu_2338_p229;
wire   [7:0] value_fu_2338_p231;
wire   [7:0] value_fu_2338_p233;
wire   [7:0] value_fu_2338_p235;
wire   [7:0] value_fu_2338_p237;
wire   [7:0] value_fu_2338_p239;
wire   [7:0] value_fu_2338_p241;
wire   [7:0] value_fu_2338_p243;
wire   [7:0] value_fu_2338_p245;
wire   [7:0] value_fu_2338_p247;
wire   [7:0] value_fu_2338_p249;
wire   [7:0] value_fu_2338_p251;
wire   [7:0] value_fu_2338_p253;
wire   [7:0] value_fu_2338_p255;
wire  signed [7:0] value_fu_2338_p257;
wire  signed [7:0] value_fu_2338_p259;
wire  signed [7:0] value_fu_2338_p261;
wire  signed [7:0] value_fu_2338_p263;
wire  signed [7:0] value_fu_2338_p265;
wire  signed [7:0] value_fu_2338_p267;
wire  signed [7:0] value_fu_2338_p269;
wire  signed [7:0] value_fu_2338_p271;
wire  signed [7:0] value_fu_2338_p273;
wire  signed [7:0] value_fu_2338_p275;
wire  signed [7:0] value_fu_2338_p277;
wire  signed [7:0] value_fu_2338_p279;
wire  signed [7:0] value_fu_2338_p281;
wire  signed [7:0] value_fu_2338_p283;
wire  signed [7:0] value_fu_2338_p285;
wire  signed [7:0] value_fu_2338_p287;
wire  signed [7:0] value_fu_2338_p289;
wire  signed [7:0] value_fu_2338_p291;
wire  signed [7:0] value_fu_2338_p293;
wire  signed [7:0] value_fu_2338_p295;
wire  signed [7:0] value_fu_2338_p297;
wire  signed [7:0] value_fu_2338_p299;
wire  signed [7:0] value_fu_2338_p301;
wire  signed [7:0] value_fu_2338_p303;
wire  signed [7:0] value_fu_2338_p305;
wire  signed [7:0] value_fu_2338_p307;
wire  signed [7:0] value_fu_2338_p309;
wire  signed [7:0] value_fu_2338_p311;
wire  signed [7:0] value_fu_2338_p313;
wire  signed [7:0] value_fu_2338_p315;
wire  signed [7:0] value_fu_2338_p317;
wire  signed [7:0] value_fu_2338_p319;
wire  signed [7:0] value_fu_2338_p321;
wire  signed [7:0] value_fu_2338_p323;
wire  signed [7:0] value_fu_2338_p325;
wire  signed [7:0] value_fu_2338_p327;
wire  signed [7:0] value_fu_2338_p329;
wire  signed [7:0] value_fu_2338_p331;
wire  signed [7:0] value_fu_2338_p333;
wire  signed [7:0] value_fu_2338_p335;
wire  signed [7:0] value_fu_2338_p337;
wire  signed [7:0] value_fu_2338_p339;
wire  signed [7:0] value_fu_2338_p341;
wire  signed [7:0] value_fu_2338_p343;
wire  signed [7:0] value_fu_2338_p345;
wire  signed [7:0] value_fu_2338_p347;
wire  signed [7:0] value_fu_2338_p349;
wire  signed [7:0] value_fu_2338_p351;
wire  signed [7:0] value_fu_2338_p353;
wire  signed [7:0] value_fu_2338_p355;
wire  signed [7:0] value_fu_2338_p357;
wire  signed [7:0] value_fu_2338_p359;
wire  signed [7:0] value_fu_2338_p361;
wire  signed [7:0] value_fu_2338_p363;
wire  signed [7:0] value_fu_2338_p365;
wire  signed [7:0] value_fu_2338_p367;
wire  signed [7:0] value_fu_2338_p369;
wire  signed [7:0] value_fu_2338_p371;
wire  signed [7:0] value_fu_2338_p373;
wire  signed [7:0] value_fu_2338_p375;
wire  signed [7:0] value_fu_2338_p377;
wire  signed [7:0] value_fu_2338_p379;
wire  signed [7:0] value_fu_2338_p381;
wire  signed [7:0] value_fu_2338_p383;
wire  signed [7:0] value_fu_2338_p385;
wire  signed [7:0] value_fu_2338_p387;
wire  signed [7:0] value_fu_2338_p389;
wire  signed [7:0] value_fu_2338_p391;
wire  signed [7:0] value_fu_2338_p393;
wire  signed [7:0] value_fu_2338_p395;
wire  signed [7:0] value_fu_2338_p397;
wire  signed [7:0] value_fu_2338_p399;
wire  signed [7:0] value_fu_2338_p401;
wire  signed [7:0] value_fu_2338_p403;
wire  signed [7:0] value_fu_2338_p405;
wire  signed [7:0] value_fu_2338_p407;
wire  signed [7:0] value_fu_2338_p409;
wire  signed [7:0] value_fu_2338_p411;
wire  signed [7:0] value_fu_2338_p413;
wire  signed [7:0] value_fu_2338_p415;
wire  signed [7:0] value_fu_2338_p417;
wire  signed [7:0] value_fu_2338_p419;
wire  signed [7:0] value_fu_2338_p421;
wire  signed [7:0] value_fu_2338_p423;
wire  signed [7:0] value_fu_2338_p425;
wire  signed [7:0] value_fu_2338_p427;
wire  signed [7:0] value_fu_2338_p429;
wire  signed [7:0] value_fu_2338_p431;
wire  signed [7:0] value_fu_2338_p433;
wire  signed [7:0] value_fu_2338_p435;
wire  signed [7:0] value_fu_2338_p437;
wire  signed [7:0] value_fu_2338_p439;
wire  signed [7:0] value_fu_2338_p441;
wire  signed [7:0] value_fu_2338_p443;
wire  signed [7:0] value_fu_2338_p445;
wire  signed [7:0] value_fu_2338_p447;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 hidden_index_fu_946 = 8'd0;
#0 ap_done_reg = 1'b0;
end

SubbandRealtimeTopQ610Ip_sparsemux_449_8_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 8'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 8'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 8'h2 ),
    .din2_WIDTH( 16 ),
    .CASE3( 8'h3 ),
    .din3_WIDTH( 16 ),
    .CASE4( 8'h4 ),
    .din4_WIDTH( 16 ),
    .CASE5( 8'h5 ),
    .din5_WIDTH( 16 ),
    .CASE6( 8'h6 ),
    .din6_WIDTH( 16 ),
    .CASE7( 8'h7 ),
    .din7_WIDTH( 16 ),
    .CASE8( 8'h8 ),
    .din8_WIDTH( 16 ),
    .CASE9( 8'h9 ),
    .din9_WIDTH( 16 ),
    .CASE10( 8'hA ),
    .din10_WIDTH( 16 ),
    .CASE11( 8'hB ),
    .din11_WIDTH( 16 ),
    .CASE12( 8'hC ),
    .din12_WIDTH( 16 ),
    .CASE13( 8'hD ),
    .din13_WIDTH( 16 ),
    .CASE14( 8'hE ),
    .din14_WIDTH( 16 ),
    .CASE15( 8'hF ),
    .din15_WIDTH( 16 ),
    .CASE16( 8'h10 ),
    .din16_WIDTH( 16 ),
    .CASE17( 8'h11 ),
    .din17_WIDTH( 16 ),
    .CASE18( 8'h12 ),
    .din18_WIDTH( 16 ),
    .CASE19( 8'h13 ),
    .din19_WIDTH( 16 ),
    .CASE20( 8'h14 ),
    .din20_WIDTH( 16 ),
    .CASE21( 8'h15 ),
    .din21_WIDTH( 16 ),
    .CASE22( 8'h16 ),
    .din22_WIDTH( 16 ),
    .CASE23( 8'h17 ),
    .din23_WIDTH( 16 ),
    .CASE24( 8'h18 ),
    .din24_WIDTH( 16 ),
    .CASE25( 8'h19 ),
    .din25_WIDTH( 16 ),
    .CASE26( 8'h1A ),
    .din26_WIDTH( 16 ),
    .CASE27( 8'h1B ),
    .din27_WIDTH( 16 ),
    .CASE28( 8'h1C ),
    .din28_WIDTH( 16 ),
    .CASE29( 8'h1D ),
    .din29_WIDTH( 16 ),
    .CASE30( 8'h1E ),
    .din30_WIDTH( 16 ),
    .CASE31( 8'h1F ),
    .din31_WIDTH( 16 ),
    .CASE32( 8'h20 ),
    .din32_WIDTH( 16 ),
    .CASE33( 8'h21 ),
    .din33_WIDTH( 16 ),
    .CASE34( 8'h22 ),
    .din34_WIDTH( 16 ),
    .CASE35( 8'h23 ),
    .din35_WIDTH( 16 ),
    .CASE36( 8'h24 ),
    .din36_WIDTH( 16 ),
    .CASE37( 8'h25 ),
    .din37_WIDTH( 16 ),
    .CASE38( 8'h26 ),
    .din38_WIDTH( 16 ),
    .CASE39( 8'h27 ),
    .din39_WIDTH( 16 ),
    .CASE40( 8'h28 ),
    .din40_WIDTH( 16 ),
    .CASE41( 8'h29 ),
    .din41_WIDTH( 16 ),
    .CASE42( 8'h2A ),
    .din42_WIDTH( 16 ),
    .CASE43( 8'h2B ),
    .din43_WIDTH( 16 ),
    .CASE44( 8'h2C ),
    .din44_WIDTH( 16 ),
    .CASE45( 8'h2D ),
    .din45_WIDTH( 16 ),
    .CASE46( 8'h2E ),
    .din46_WIDTH( 16 ),
    .CASE47( 8'h2F ),
    .din47_WIDTH( 16 ),
    .CASE48( 8'h30 ),
    .din48_WIDTH( 16 ),
    .CASE49( 8'h31 ),
    .din49_WIDTH( 16 ),
    .CASE50( 8'h32 ),
    .din50_WIDTH( 16 ),
    .CASE51( 8'h33 ),
    .din51_WIDTH( 16 ),
    .CASE52( 8'h34 ),
    .din52_WIDTH( 16 ),
    .CASE53( 8'h35 ),
    .din53_WIDTH( 16 ),
    .CASE54( 8'h36 ),
    .din54_WIDTH( 16 ),
    .CASE55( 8'h37 ),
    .din55_WIDTH( 16 ),
    .CASE56( 8'h38 ),
    .din56_WIDTH( 16 ),
    .CASE57( 8'h39 ),
    .din57_WIDTH( 16 ),
    .CASE58( 8'h3A ),
    .din58_WIDTH( 16 ),
    .CASE59( 8'h3B ),
    .din59_WIDTH( 16 ),
    .CASE60( 8'h3C ),
    .din60_WIDTH( 16 ),
    .CASE61( 8'h3D ),
    .din61_WIDTH( 16 ),
    .CASE62( 8'h3E ),
    .din62_WIDTH( 16 ),
    .CASE63( 8'h3F ),
    .din63_WIDTH( 16 ),
    .CASE64( 8'h40 ),
    .din64_WIDTH( 16 ),
    .CASE65( 8'h41 ),
    .din65_WIDTH( 16 ),
    .CASE66( 8'h42 ),
    .din66_WIDTH( 16 ),
    .CASE67( 8'h43 ),
    .din67_WIDTH( 16 ),
    .CASE68( 8'h44 ),
    .din68_WIDTH( 16 ),
    .CASE69( 8'h45 ),
    .din69_WIDTH( 16 ),
    .CASE70( 8'h46 ),
    .din70_WIDTH( 16 ),
    .CASE71( 8'h47 ),
    .din71_WIDTH( 16 ),
    .CASE72( 8'h48 ),
    .din72_WIDTH( 16 ),
    .CASE73( 8'h49 ),
    .din73_WIDTH( 16 ),
    .CASE74( 8'h4A ),
    .din74_WIDTH( 16 ),
    .CASE75( 8'h4B ),
    .din75_WIDTH( 16 ),
    .CASE76( 8'h4C ),
    .din76_WIDTH( 16 ),
    .CASE77( 8'h4D ),
    .din77_WIDTH( 16 ),
    .CASE78( 8'h4E ),
    .din78_WIDTH( 16 ),
    .CASE79( 8'h4F ),
    .din79_WIDTH( 16 ),
    .CASE80( 8'h50 ),
    .din80_WIDTH( 16 ),
    .CASE81( 8'h51 ),
    .din81_WIDTH( 16 ),
    .CASE82( 8'h52 ),
    .din82_WIDTH( 16 ),
    .CASE83( 8'h53 ),
    .din83_WIDTH( 16 ),
    .CASE84( 8'h54 ),
    .din84_WIDTH( 16 ),
    .CASE85( 8'h55 ),
    .din85_WIDTH( 16 ),
    .CASE86( 8'h56 ),
    .din86_WIDTH( 16 ),
    .CASE87( 8'h57 ),
    .din87_WIDTH( 16 ),
    .CASE88( 8'h58 ),
    .din88_WIDTH( 16 ),
    .CASE89( 8'h59 ),
    .din89_WIDTH( 16 ),
    .CASE90( 8'h5A ),
    .din90_WIDTH( 16 ),
    .CASE91( 8'h5B ),
    .din91_WIDTH( 16 ),
    .CASE92( 8'h5C ),
    .din92_WIDTH( 16 ),
    .CASE93( 8'h5D ),
    .din93_WIDTH( 16 ),
    .CASE94( 8'h5E ),
    .din94_WIDTH( 16 ),
    .CASE95( 8'h5F ),
    .din95_WIDTH( 16 ),
    .CASE96( 8'h60 ),
    .din96_WIDTH( 16 ),
    .CASE97( 8'h61 ),
    .din97_WIDTH( 16 ),
    .CASE98( 8'h62 ),
    .din98_WIDTH( 16 ),
    .CASE99( 8'h63 ),
    .din99_WIDTH( 16 ),
    .CASE100( 8'h64 ),
    .din100_WIDTH( 16 ),
    .CASE101( 8'h65 ),
    .din101_WIDTH( 16 ),
    .CASE102( 8'h66 ),
    .din102_WIDTH( 16 ),
    .CASE103( 8'h67 ),
    .din103_WIDTH( 16 ),
    .CASE104( 8'h68 ),
    .din104_WIDTH( 16 ),
    .CASE105( 8'h69 ),
    .din105_WIDTH( 16 ),
    .CASE106( 8'h6A ),
    .din106_WIDTH( 16 ),
    .CASE107( 8'h6B ),
    .din107_WIDTH( 16 ),
    .CASE108( 8'h6C ),
    .din108_WIDTH( 16 ),
    .CASE109( 8'h6D ),
    .din109_WIDTH( 16 ),
    .CASE110( 8'h6E ),
    .din110_WIDTH( 16 ),
    .CASE111( 8'h6F ),
    .din111_WIDTH( 16 ),
    .CASE112( 8'h70 ),
    .din112_WIDTH( 16 ),
    .CASE113( 8'h71 ),
    .din113_WIDTH( 16 ),
    .CASE114( 8'h72 ),
    .din114_WIDTH( 16 ),
    .CASE115( 8'h73 ),
    .din115_WIDTH( 16 ),
    .CASE116( 8'h74 ),
    .din116_WIDTH( 16 ),
    .CASE117( 8'h75 ),
    .din117_WIDTH( 16 ),
    .CASE118( 8'h76 ),
    .din118_WIDTH( 16 ),
    .CASE119( 8'h77 ),
    .din119_WIDTH( 16 ),
    .CASE120( 8'h78 ),
    .din120_WIDTH( 16 ),
    .CASE121( 8'h79 ),
    .din121_WIDTH( 16 ),
    .CASE122( 8'h7A ),
    .din122_WIDTH( 16 ),
    .CASE123( 8'h7B ),
    .din123_WIDTH( 16 ),
    .CASE124( 8'h7C ),
    .din124_WIDTH( 16 ),
    .CASE125( 8'h7D ),
    .din125_WIDTH( 16 ),
    .CASE126( 8'h7E ),
    .din126_WIDTH( 16 ),
    .CASE127( 8'h7F ),
    .din127_WIDTH( 16 ),
    .CASE128( 8'h80 ),
    .din128_WIDTH( 16 ),
    .CASE129( 8'h81 ),
    .din129_WIDTH( 16 ),
    .CASE130( 8'h82 ),
    .din130_WIDTH( 16 ),
    .CASE131( 8'h83 ),
    .din131_WIDTH( 16 ),
    .CASE132( 8'h84 ),
    .din132_WIDTH( 16 ),
    .CASE133( 8'h85 ),
    .din133_WIDTH( 16 ),
    .CASE134( 8'h86 ),
    .din134_WIDTH( 16 ),
    .CASE135( 8'h87 ),
    .din135_WIDTH( 16 ),
    .CASE136( 8'h88 ),
    .din136_WIDTH( 16 ),
    .CASE137( 8'h89 ),
    .din137_WIDTH( 16 ),
    .CASE138( 8'h8A ),
    .din138_WIDTH( 16 ),
    .CASE139( 8'h8B ),
    .din139_WIDTH( 16 ),
    .CASE140( 8'h8C ),
    .din140_WIDTH( 16 ),
    .CASE141( 8'h8D ),
    .din141_WIDTH( 16 ),
    .CASE142( 8'h8E ),
    .din142_WIDTH( 16 ),
    .CASE143( 8'h8F ),
    .din143_WIDTH( 16 ),
    .CASE144( 8'h90 ),
    .din144_WIDTH( 16 ),
    .CASE145( 8'h91 ),
    .din145_WIDTH( 16 ),
    .CASE146( 8'h92 ),
    .din146_WIDTH( 16 ),
    .CASE147( 8'h93 ),
    .din147_WIDTH( 16 ),
    .CASE148( 8'h94 ),
    .din148_WIDTH( 16 ),
    .CASE149( 8'h95 ),
    .din149_WIDTH( 16 ),
    .CASE150( 8'h96 ),
    .din150_WIDTH( 16 ),
    .CASE151( 8'h97 ),
    .din151_WIDTH( 16 ),
    .CASE152( 8'h98 ),
    .din152_WIDTH( 16 ),
    .CASE153( 8'h99 ),
    .din153_WIDTH( 16 ),
    .CASE154( 8'h9A ),
    .din154_WIDTH( 16 ),
    .CASE155( 8'h9B ),
    .din155_WIDTH( 16 ),
    .CASE156( 8'h9C ),
    .din156_WIDTH( 16 ),
    .CASE157( 8'h9D ),
    .din157_WIDTH( 16 ),
    .CASE158( 8'h9E ),
    .din158_WIDTH( 16 ),
    .CASE159( 8'h9F ),
    .din159_WIDTH( 16 ),
    .CASE160( 8'hA0 ),
    .din160_WIDTH( 16 ),
    .CASE161( 8'hA1 ),
    .din161_WIDTH( 16 ),
    .CASE162( 8'hA2 ),
    .din162_WIDTH( 16 ),
    .CASE163( 8'hA3 ),
    .din163_WIDTH( 16 ),
    .CASE164( 8'hA4 ),
    .din164_WIDTH( 16 ),
    .CASE165( 8'hA5 ),
    .din165_WIDTH( 16 ),
    .CASE166( 8'hA6 ),
    .din166_WIDTH( 16 ),
    .CASE167( 8'hA7 ),
    .din167_WIDTH( 16 ),
    .CASE168( 8'hA8 ),
    .din168_WIDTH( 16 ),
    .CASE169( 8'hA9 ),
    .din169_WIDTH( 16 ),
    .CASE170( 8'hAA ),
    .din170_WIDTH( 16 ),
    .CASE171( 8'hAB ),
    .din171_WIDTH( 16 ),
    .CASE172( 8'hAC ),
    .din172_WIDTH( 16 ),
    .CASE173( 8'hAD ),
    .din173_WIDTH( 16 ),
    .CASE174( 8'hAE ),
    .din174_WIDTH( 16 ),
    .CASE175( 8'hAF ),
    .din175_WIDTH( 16 ),
    .CASE176( 8'hB0 ),
    .din176_WIDTH( 16 ),
    .CASE177( 8'hB1 ),
    .din177_WIDTH( 16 ),
    .CASE178( 8'hB2 ),
    .din178_WIDTH( 16 ),
    .CASE179( 8'hB3 ),
    .din179_WIDTH( 16 ),
    .CASE180( 8'hB4 ),
    .din180_WIDTH( 16 ),
    .CASE181( 8'hB5 ),
    .din181_WIDTH( 16 ),
    .CASE182( 8'hB6 ),
    .din182_WIDTH( 16 ),
    .CASE183( 8'hB7 ),
    .din183_WIDTH( 16 ),
    .CASE184( 8'hB8 ),
    .din184_WIDTH( 16 ),
    .CASE185( 8'hB9 ),
    .din185_WIDTH( 16 ),
    .CASE186( 8'hBA ),
    .din186_WIDTH( 16 ),
    .CASE187( 8'hBB ),
    .din187_WIDTH( 16 ),
    .CASE188( 8'hBC ),
    .din188_WIDTH( 16 ),
    .CASE189( 8'hBD ),
    .din189_WIDTH( 16 ),
    .CASE190( 8'hBE ),
    .din190_WIDTH( 16 ),
    .CASE191( 8'hBF ),
    .din191_WIDTH( 16 ),
    .CASE192( 8'hC0 ),
    .din192_WIDTH( 16 ),
    .CASE193( 8'hC1 ),
    .din193_WIDTH( 16 ),
    .CASE194( 8'hC2 ),
    .din194_WIDTH( 16 ),
    .CASE195( 8'hC3 ),
    .din195_WIDTH( 16 ),
    .CASE196( 8'hC4 ),
    .din196_WIDTH( 16 ),
    .CASE197( 8'hC5 ),
    .din197_WIDTH( 16 ),
    .CASE198( 8'hC6 ),
    .din198_WIDTH( 16 ),
    .CASE199( 8'hC7 ),
    .din199_WIDTH( 16 ),
    .CASE200( 8'hC8 ),
    .din200_WIDTH( 16 ),
    .CASE201( 8'hC9 ),
    .din201_WIDTH( 16 ),
    .CASE202( 8'hCA ),
    .din202_WIDTH( 16 ),
    .CASE203( 8'hCB ),
    .din203_WIDTH( 16 ),
    .CASE204( 8'hCC ),
    .din204_WIDTH( 16 ),
    .CASE205( 8'hCD ),
    .din205_WIDTH( 16 ),
    .CASE206( 8'hCE ),
    .din206_WIDTH( 16 ),
    .CASE207( 8'hCF ),
    .din207_WIDTH( 16 ),
    .CASE208( 8'hD0 ),
    .din208_WIDTH( 16 ),
    .CASE209( 8'hD1 ),
    .din209_WIDTH( 16 ),
    .CASE210( 8'hD2 ),
    .din210_WIDTH( 16 ),
    .CASE211( 8'hD3 ),
    .din211_WIDTH( 16 ),
    .CASE212( 8'hD4 ),
    .din212_WIDTH( 16 ),
    .CASE213( 8'hD5 ),
    .din213_WIDTH( 16 ),
    .CASE214( 8'hD6 ),
    .din214_WIDTH( 16 ),
    .CASE215( 8'hD7 ),
    .din215_WIDTH( 16 ),
    .CASE216( 8'hD8 ),
    .din216_WIDTH( 16 ),
    .CASE217( 8'hD9 ),
    .din217_WIDTH( 16 ),
    .CASE218( 8'hDA ),
    .din218_WIDTH( 16 ),
    .CASE219( 8'hDB ),
    .din219_WIDTH( 16 ),
    .CASE220( 8'hDC ),
    .din220_WIDTH( 16 ),
    .CASE221( 8'hDD ),
    .din221_WIDTH( 16 ),
    .CASE222( 8'hDE ),
    .din222_WIDTH( 16 ),
    .CASE223( 8'hDF ),
    .din223_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
sparsemux_449_8_16_1_1_U569(
    .din0(proj_row_0_val),
    .din1(proj_row_1_val),
    .din2(proj_row_2_val),
    .din3(proj_row_3_val),
    .din4(proj_row_4_val),
    .din5(proj_row_5_val),
    .din6(proj_row_6_val),
    .din7(proj_row_7_val),
    .din8(proj_row_8_val),
    .din9(proj_row_9_val),
    .din10(proj_row_10_val),
    .din11(proj_row_11_val),
    .din12(proj_row_12_val),
    .din13(proj_row_13_val),
    .din14(proj_row_14_val),
    .din15(proj_row_15_val),
    .din16(proj_row_16_val),
    .din17(proj_row_17_val),
    .din18(proj_row_18_val),
    .din19(proj_row_19_val),
    .din20(proj_row_20_val),
    .din21(proj_row_21_val),
    .din22(proj_row_22_val),
    .din23(proj_row_23_val),
    .din24(proj_row_24_val),
    .din25(proj_row_25_val),
    .din26(proj_row_26_val),
    .din27(proj_row_27_val),
    .din28(proj_row_28_val),
    .din29(proj_row_29_val),
    .din30(proj_row_30_val),
    .din31(proj_row_31_val),
    .din32(proj_row_32_val),
    .din33(proj_row_33_val),
    .din34(proj_row_34_val),
    .din35(proj_row_35_val),
    .din36(proj_row_36_val),
    .din37(proj_row_37_val),
    .din38(proj_row_38_val),
    .din39(proj_row_39_val),
    .din40(proj_row_40_val),
    .din41(proj_row_41_val),
    .din42(proj_row_42_val),
    .din43(proj_row_43_val),
    .din44(proj_row_44_val),
    .din45(proj_row_45_val),
    .din46(proj_row_46_val),
    .din47(proj_row_47_val),
    .din48(proj_row_48_val),
    .din49(proj_row_49_val),
    .din50(proj_row_50_val),
    .din51(proj_row_51_val),
    .din52(proj_row_52_val),
    .din53(proj_row_53_val),
    .din54(proj_row_54_val),
    .din55(proj_row_55_val),
    .din56(proj_row_56_val),
    .din57(proj_row_57_val),
    .din58(proj_row_58_val),
    .din59(proj_row_59_val),
    .din60(proj_row_60_val),
    .din61(proj_row_61_val),
    .din62(proj_row_62_val),
    .din63(proj_row_63_val),
    .din64(proj_row_64_val),
    .din65(proj_row_65_val),
    .din66(proj_row_66_val),
    .din67(proj_row_67_val),
    .din68(proj_row_68_val),
    .din69(proj_row_69_val),
    .din70(proj_row_70_val),
    .din71(proj_row_71_val),
    .din72(proj_row_72_val),
    .din73(proj_row_73_val),
    .din74(proj_row_74_val),
    .din75(proj_row_75_val),
    .din76(proj_row_76_val),
    .din77(proj_row_77_val),
    .din78(proj_row_78_val),
    .din79(proj_row_79_val),
    .din80(proj_row_80_val),
    .din81(proj_row_81_val),
    .din82(proj_row_82_val),
    .din83(proj_row_83_val),
    .din84(proj_row_84_val),
    .din85(proj_row_85_val),
    .din86(proj_row_86_val),
    .din87(proj_row_87_val),
    .din88(proj_row_88_val),
    .din89(proj_row_89_val),
    .din90(proj_row_90_val),
    .din91(proj_row_91_val),
    .din92(proj_row_92_val),
    .din93(proj_row_93_val),
    .din94(proj_row_94_val),
    .din95(proj_row_95_val),
    .din96(proj_row_96_val),
    .din97(proj_row_97_val),
    .din98(proj_row_98_val),
    .din99(proj_row_99_val),
    .din100(proj_row_100_val),
    .din101(proj_row_101_val),
    .din102(proj_row_102_val),
    .din103(proj_row_103_val),
    .din104(proj_row_104_val),
    .din105(proj_row_105_val),
    .din106(proj_row_106_val),
    .din107(proj_row_107_val),
    .din108(proj_row_108_val),
    .din109(proj_row_109_val),
    .din110(proj_row_110_val),
    .din111(proj_row_111_val),
    .din112(proj_row_112_val),
    .din113(proj_row_113_val),
    .din114(proj_row_114_val),
    .din115(proj_row_115_val),
    .din116(proj_row_116_val),
    .din117(proj_row_117_val),
    .din118(proj_row_118_val),
    .din119(proj_row_119_val),
    .din120(proj_row_120_val),
    .din121(proj_row_121_val),
    .din122(proj_row_122_val),
    .din123(proj_row_123_val),
    .din124(proj_row_124_val),
    .din125(proj_row_125_val),
    .din126(proj_row_126_val),
    .din127(proj_row_127_val),
    .din128(proj_row_128_val),
    .din129(proj_row_129_val),
    .din130(proj_row_130_val),
    .din131(proj_row_131_val),
    .din132(proj_row_132_val),
    .din133(proj_row_133_val),
    .din134(proj_row_134_val),
    .din135(proj_row_135_val),
    .din136(proj_row_136_val),
    .din137(proj_row_137_val),
    .din138(proj_row_138_val),
    .din139(proj_row_139_val),
    .din140(proj_row_140_val),
    .din141(proj_row_141_val),
    .din142(proj_row_142_val),
    .din143(proj_row_143_val),
    .din144(proj_row_144_val),
    .din145(proj_row_145_val),
    .din146(proj_row_146_val),
    .din147(proj_row_147_val),
    .din148(proj_row_148_val),
    .din149(proj_row_149_val),
    .din150(proj_row_150_val),
    .din151(proj_row_151_val),
    .din152(proj_row_152_val),
    .din153(proj_row_153_val),
    .din154(proj_row_154_val),
    .din155(proj_row_155_val),
    .din156(proj_row_156_val),
    .din157(proj_row_157_val),
    .din158(proj_row_158_val),
    .din159(proj_row_159_val),
    .din160(proj_row_160_val),
    .din161(proj_row_161_val),
    .din162(proj_row_162_val),
    .din163(proj_row_163_val),
    .din164(proj_row_164_val),
    .din165(proj_row_165_val),
    .din166(proj_row_166_val),
    .din167(proj_row_167_val),
    .din168(proj_row_168_val),
    .din169(proj_row_169_val),
    .din170(proj_row_170_val),
    .din171(proj_row_171_val),
    .din172(proj_row_172_val),
    .din173(proj_row_173_val),
    .din174(proj_row_174_val),
    .din175(proj_row_175_val),
    .din176(proj_row_176_val),
    .din177(proj_row_177_val),
    .din178(proj_row_178_val),
    .din179(proj_row_179_val),
    .din180(proj_row_180_val),
    .din181(proj_row_181_val),
    .din182(proj_row_182_val),
    .din183(proj_row_183_val),
    .din184(proj_row_184_val),
    .din185(proj_row_185_val),
    .din186(proj_row_186_val),
    .din187(proj_row_187_val),
    .din188(proj_row_188_val),
    .din189(proj_row_189_val),
    .din190(proj_row_190_val),
    .din191(proj_row_191_val),
    .din192(proj_row_192_val),
    .din193(proj_row_193_val),
    .din194(proj_row_194_val),
    .din195(proj_row_195_val),
    .din196(proj_row_196_val),
    .din197(proj_row_197_val),
    .din198(proj_row_198_val),
    .din199(proj_row_199_val),
    .din200(proj_row_200_val),
    .din201(proj_row_201_val),
    .din202(proj_row_202_val),
    .din203(proj_row_203_val),
    .din204(proj_row_204_val),
    .din205(proj_row_205_val),
    .din206(proj_row_206_val),
    .din207(proj_row_207_val),
    .din208(proj_row_208_val),
    .din209(proj_row_209_val),
    .din210(proj_row_210_val),
    .din211(proj_row_211_val),
    .din212(proj_row_212_val),
    .din213(proj_row_213_val),
    .din214(proj_row_214_val),
    .din215(proj_row_215_val),
    .din216(proj_row_216_val),
    .din217(proj_row_217_val),
    .din218(proj_row_218_val),
    .din219(proj_row_219_val),
    .din220(proj_row_220_val),
    .din221(proj_row_221_val),
    .din222(proj_row_222_val),
    .din223(proj_row_223_val),
    .def(value_fu_2338_p449),
    .sel(ap_sig_allocacmp_hidden_index_1),
    .dout(value_fu_2338_p451)
);

SubbandRealtimeTopQ610Ip_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln4565_fu_2320_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            hidden_index_fu_946 <= add_ln4565_fu_2326_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            hidden_index_fu_946 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        is_last_reg_3257 <= is_last_fu_2332_p2;
        value_reg_3262 <= value_fu_2338_p451;
    end
end

always @ (*) begin
    if (((icmp_ln4565_fu_2320_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_hidden_index_1 = 8'd0;
    end else begin
        ap_sig_allocacmp_hidden_index_1 = hidden_index_fu_946;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        projection_request_stream_TDATA_blk_n = projection_request_stream_TREADY;
    end else begin
        projection_request_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        projection_request_stream_TVALID = 1'b1;
    end else begin
        projection_request_stream_TVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln4565_fu_2326_p2 = (ap_sig_allocacmp_hidden_index_1 + 8'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & ((projection_request_stream_TREADY == 1'b0) | (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & ((projection_request_stream_TREADY == 1'b0) | (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (projection_request_stream_TREADY == 1'b0);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln4565_fu_2320_p2 = ((ap_sig_allocacmp_hidden_index_1 == 8'd224) ? 1'b1 : 1'b0);

assign is_last_fu_2332_p2 = ((ap_sig_allocacmp_hidden_index_1 == 8'd223) ? 1'b1 : 1'b0);

assign projection_request_stream_TDATA = value_reg_3262;

assign projection_request_stream_TKEEP = 2'd3;

assign projection_request_stream_TLAST = is_last_reg_3257;

assign projection_request_stream_TSTRB = 2'd3;

assign value_fu_2338_p449 = 'bx;

endmodule //SubbandRealtimeTopQ610Ip_p_anonymous_namespace_CallExternalProjectionIpQ610_Pipeline_VITIS_LOOP_4565_3
