// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module SubbandRealtimeTopQ610Ip_p_anonymous_namespace_RunRealtimeGSUCellSharedQ610 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        p_read,
        p_read1,
        p_read2,
        p_read3,
        p_read4,
        p_read5,
        p_read6,
        p_read7,
        p_read8,
        p_read9,
        p_read10,
        p_read11,
        p_read12,
        p_read13,
        p_read14,
        p_read15,
        p_read16,
        p_read17,
        p_read18,
        p_read19,
        p_read20,
        p_read21,
        p_read22,
        p_read23,
        p_read24,
        p_read25,
        p_read26,
        p_read27,
        p_read28,
        p_read29,
        p_read30,
        p_read31,
        p_read32,
        p_read33,
        p_read34,
        p_read35,
        p_read36,
        p_read37,
        p_read38,
        p_read39,
        p_read40,
        p_read41,
        p_read42,
        p_read43,
        p_read44,
        p_read45,
        p_read46,
        p_read47,
        p_read48,
        p_read49,
        p_read50,
        p_read51,
        p_read52,
        p_read53,
        p_read54,
        p_read55,
        p_read56,
        p_read57,
        p_read58,
        p_read59,
        p_read60,
        p_read61,
        p_read62,
        p_read63,
        p_read64,
        p_read65,
        p_read66,
        p_read67,
        p_read68,
        p_read69,
        p_read70,
        p_read71,
        p_read72,
        p_read73,
        p_read74,
        p_read75,
        p_read76,
        p_read77,
        p_read78,
        p_read79,
        p_read80,
        p_read81,
        p_read82,
        p_read83,
        p_read84,
        p_read85,
        p_read86,
        p_read87,
        p_read88,
        p_read89,
        p_read90,
        p_read91,
        p_read92,
        p_read93,
        p_read94,
        p_read95,
        p_read96,
        p_read97,
        p_read98,
        p_read99,
        p_read100,
        p_read101,
        p_read102,
        p_read103,
        p_read104,
        p_read105,
        p_read106,
        p_read107,
        p_read108,
        p_read109,
        p_read110,
        p_read111,
        p_read112,
        p_read113,
        p_read114,
        p_read115,
        p_read116,
        p_read117,
        p_read118,
        p_read119,
        p_read120,
        p_read121,
        p_read122,
        p_read123,
        p_read124,
        p_read125,
        p_read126,
        p_read127,
        p_read128,
        p_read129,
        p_read130,
        p_read131,
        p_read132,
        p_read133,
        p_read134,
        p_read135,
        p_read136,
        p_read137,
        p_read138,
        p_read139,
        p_read140,
        p_read141,
        p_read142,
        p_read143,
        p_read144,
        p_read145,
        p_read146,
        p_read147,
        p_read148,
        p_read149,
        p_read150,
        p_read151,
        p_read152,
        p_read153,
        p_read154,
        p_read155,
        p_read156,
        p_read157,
        p_read158,
        p_read159,
        p_read160,
        p_read161,
        p_read162,
        p_read163,
        p_read164,
        p_read165,
        p_read166,
        p_read167,
        p_read168,
        p_read169,
        p_read170,
        p_read171,
        p_read172,
        p_read173,
        p_read174,
        p_read175,
        p_read176,
        p_read177,
        p_read178,
        p_read179,
        p_read180,
        p_read181,
        p_read182,
        p_read183,
        p_read184,
        p_read185,
        p_read186,
        p_read187,
        p_read188,
        p_read189,
        p_read190,
        p_read191,
        p_read192,
        p_read193,
        p_read194,
        p_read195,
        p_read196,
        p_read197,
        p_read198,
        p_read199,
        p_read200,
        p_read201,
        p_read202,
        p_read203,
        p_read204,
        p_read205,
        p_read206,
        p_read207,
        p_read208,
        p_read209,
        p_read210,
        p_read211,
        p_read212,
        p_read213,
        p_read214,
        p_read215,
        p_read216,
        p_read217,
        p_read218,
        p_read219,
        p_read220,
        p_read221,
        p_read222,
        p_read223,
        weight_ih_0_address0,
        weight_ih_0_ce0,
        weight_ih_0_q0,
        weight_ih_1_address0,
        weight_ih_1_ce0,
        weight_ih_1_q0,
        weight_hh_0_address0,
        weight_hh_0_ce0,
        weight_hh_0_q0,
        weight_hh_1_address0,
        weight_hh_1_ce0,
        weight_hh_1_q0,
        bias_ih_0_address0,
        bias_ih_0_ce0,
        bias_ih_0_q0,
        bias_ih_0_address1,
        bias_ih_0_ce1,
        bias_ih_0_q1,
        bias_ih_1_address0,
        bias_ih_1_ce0,
        bias_ih_1_q0,
        bias_ih_1_address1,
        bias_ih_1_ce1,
        bias_ih_1_q1,
        bn_mul_0_address0,
        bn_mul_0_ce0,
        bn_mul_0_q0,
        bn_mul_1_address0,
        bn_mul_1_ce0,
        bn_mul_1_q0,
        bn_add_0_address0,
        bn_add_0_ce0,
        bn_add_0_q0,
        bn_add_1_address0,
        bn_add_1_ce0,
        bn_add_1_q0,
        hx_state_q610_0_address0,
        hx_state_q610_0_ce0,
        hx_state_q610_0_q0,
        hx_state_q610_0_address1,
        hx_state_q610_0_ce1,
        hx_state_q610_0_we1,
        hx_state_q610_0_d1,
        hx_state_q610_0_offset,
        hx_state_q610_1_address0,
        hx_state_q610_1_ce0,
        hx_state_q610_1_q0,
        hx_state_q610_1_address1,
        hx_state_q610_1_ce1,
        hx_state_q610_1_we1,
        hx_state_q610_1_d1,
        hx_state_q610_1_offset,
        cx_state_q610_0_address0,
        cx_state_q610_0_ce0,
        cx_state_q610_0_q0,
        cx_state_q610_0_address1,
        cx_state_q610_0_ce1,
        cx_state_q610_0_we1,
        cx_state_q610_0_d1,
        cx_state_q610_0_offset,
        cx_state_q610_1_address0,
        cx_state_q610_1_ce0,
        cx_state_q610_1_q0,
        cx_state_q610_1_address1,
        cx_state_q610_1_ce1,
        cx_state_q610_1_we1,
        cx_state_q610_1_d1,
        cx_state_q610_1_offset,
        output_hy_q610_0_address1,
        output_hy_q610_0_ce1,
        output_hy_q610_0_we1,
        output_hy_q610_0_d1,
        output_hy_q610_0_offset,
        output_hy_q610_0_offset1,
        output_hy_q610_1_address1,
        output_hy_q610_1_ce1,
        output_hy_q610_1_we1,
        output_hy_q610_1_d1,
        output_hy_q610_1_offset,
        output_hy_q610_1_offset2
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] p_read;
input  [15:0] p_read1;
input  [15:0] p_read2;
input  [15:0] p_read3;
input  [15:0] p_read4;
input  [15:0] p_read5;
input  [15:0] p_read6;
input  [15:0] p_read7;
input  [15:0] p_read8;
input  [15:0] p_read9;
input  [15:0] p_read10;
input  [15:0] p_read11;
input  [15:0] p_read12;
input  [15:0] p_read13;
input  [15:0] p_read14;
input  [15:0] p_read15;
input  [15:0] p_read16;
input  [15:0] p_read17;
input  [15:0] p_read18;
input  [15:0] p_read19;
input  [15:0] p_read20;
input  [15:0] p_read21;
input  [15:0] p_read22;
input  [15:0] p_read23;
input  [15:0] p_read24;
input  [15:0] p_read25;
input  [15:0] p_read26;
input  [15:0] p_read27;
input  [15:0] p_read28;
input  [15:0] p_read29;
input  [15:0] p_read30;
input  [15:0] p_read31;
input  [15:0] p_read32;
input  [15:0] p_read33;
input  [15:0] p_read34;
input  [15:0] p_read35;
input  [15:0] p_read36;
input  [15:0] p_read37;
input  [15:0] p_read38;
input  [15:0] p_read39;
input  [15:0] p_read40;
input  [15:0] p_read41;
input  [15:0] p_read42;
input  [15:0] p_read43;
input  [15:0] p_read44;
input  [15:0] p_read45;
input  [15:0] p_read46;
input  [15:0] p_read47;
input  [15:0] p_read48;
input  [15:0] p_read49;
input  [15:0] p_read50;
input  [15:0] p_read51;
input  [15:0] p_read52;
input  [15:0] p_read53;
input  [15:0] p_read54;
input  [15:0] p_read55;
input  [15:0] p_read56;
input  [15:0] p_read57;
input  [15:0] p_read58;
input  [15:0] p_read59;
input  [15:0] p_read60;
input  [15:0] p_read61;
input  [15:0] p_read62;
input  [15:0] p_read63;
input  [15:0] p_read64;
input  [15:0] p_read65;
input  [15:0] p_read66;
input  [15:0] p_read67;
input  [15:0] p_read68;
input  [15:0] p_read69;
input  [15:0] p_read70;
input  [15:0] p_read71;
input  [15:0] p_read72;
input  [15:0] p_read73;
input  [15:0] p_read74;
input  [15:0] p_read75;
input  [15:0] p_read76;
input  [15:0] p_read77;
input  [15:0] p_read78;
input  [15:0] p_read79;
input  [15:0] p_read80;
input  [15:0] p_read81;
input  [15:0] p_read82;
input  [15:0] p_read83;
input  [15:0] p_read84;
input  [15:0] p_read85;
input  [15:0] p_read86;
input  [15:0] p_read87;
input  [15:0] p_read88;
input  [15:0] p_read89;
input  [15:0] p_read90;
input  [15:0] p_read91;
input  [15:0] p_read92;
input  [15:0] p_read93;
input  [15:0] p_read94;
input  [15:0] p_read95;
input  [15:0] p_read96;
input  [15:0] p_read97;
input  [15:0] p_read98;
input  [15:0] p_read99;
input  [15:0] p_read100;
input  [15:0] p_read101;
input  [15:0] p_read102;
input  [15:0] p_read103;
input  [15:0] p_read104;
input  [15:0] p_read105;
input  [15:0] p_read106;
input  [15:0] p_read107;
input  [15:0] p_read108;
input  [15:0] p_read109;
input  [15:0] p_read110;
input  [15:0] p_read111;
input  [15:0] p_read112;
input  [15:0] p_read113;
input  [15:0] p_read114;
input  [15:0] p_read115;
input  [15:0] p_read116;
input  [15:0] p_read117;
input  [15:0] p_read118;
input  [15:0] p_read119;
input  [15:0] p_read120;
input  [15:0] p_read121;
input  [15:0] p_read122;
input  [15:0] p_read123;
input  [15:0] p_read124;
input  [15:0] p_read125;
input  [15:0] p_read126;
input  [15:0] p_read127;
input  [15:0] p_read128;
input  [15:0] p_read129;
input  [15:0] p_read130;
input  [15:0] p_read131;
input  [15:0] p_read132;
input  [15:0] p_read133;
input  [15:0] p_read134;
input  [15:0] p_read135;
input  [15:0] p_read136;
input  [15:0] p_read137;
input  [15:0] p_read138;
input  [15:0] p_read139;
input  [15:0] p_read140;
input  [15:0] p_read141;
input  [15:0] p_read142;
input  [15:0] p_read143;
input  [15:0] p_read144;
input  [15:0] p_read145;
input  [15:0] p_read146;
input  [15:0] p_read147;
input  [15:0] p_read148;
input  [15:0] p_read149;
input  [15:0] p_read150;
input  [15:0] p_read151;
input  [15:0] p_read152;
input  [15:0] p_read153;
input  [15:0] p_read154;
input  [15:0] p_read155;
input  [15:0] p_read156;
input  [15:0] p_read157;
input  [15:0] p_read158;
input  [15:0] p_read159;
input  [15:0] p_read160;
input  [15:0] p_read161;
input  [15:0] p_read162;
input  [15:0] p_read163;
input  [15:0] p_read164;
input  [15:0] p_read165;
input  [15:0] p_read166;
input  [15:0] p_read167;
input  [15:0] p_read168;
input  [15:0] p_read169;
input  [15:0] p_read170;
input  [15:0] p_read171;
input  [15:0] p_read172;
input  [15:0] p_read173;
input  [15:0] p_read174;
input  [15:0] p_read175;
input  [15:0] p_read176;
input  [15:0] p_read177;
input  [15:0] p_read178;
input  [15:0] p_read179;
input  [15:0] p_read180;
input  [15:0] p_read181;
input  [15:0] p_read182;
input  [15:0] p_read183;
input  [15:0] p_read184;
input  [15:0] p_read185;
input  [15:0] p_read186;
input  [15:0] p_read187;
input  [15:0] p_read188;
input  [15:0] p_read189;
input  [15:0] p_read190;
input  [15:0] p_read191;
input  [15:0] p_read192;
input  [15:0] p_read193;
input  [15:0] p_read194;
input  [15:0] p_read195;
input  [15:0] p_read196;
input  [15:0] p_read197;
input  [15:0] p_read198;
input  [15:0] p_read199;
input  [15:0] p_read200;
input  [15:0] p_read201;
input  [15:0] p_read202;
input  [15:0] p_read203;
input  [15:0] p_read204;
input  [15:0] p_read205;
input  [15:0] p_read206;
input  [15:0] p_read207;
input  [15:0] p_read208;
input  [15:0] p_read209;
input  [15:0] p_read210;
input  [15:0] p_read211;
input  [15:0] p_read212;
input  [15:0] p_read213;
input  [15:0] p_read214;
input  [15:0] p_read215;
input  [15:0] p_read216;
input  [15:0] p_read217;
input  [15:0] p_read218;
input  [15:0] p_read219;
input  [15:0] p_read220;
input  [15:0] p_read221;
input  [15:0] p_read222;
input  [15:0] p_read223;
output  [9:0] weight_ih_0_address0;
output   weight_ih_0_ce0;
input  [511:0] weight_ih_0_q0;
output  [9:0] weight_ih_1_address0;
output   weight_ih_1_ce0;
input  [511:0] weight_ih_1_q0;
output  [9:0] weight_hh_0_address0;
output   weight_hh_0_ce0;
input  [511:0] weight_hh_0_q0;
output  [9:0] weight_hh_1_address0;
output   weight_hh_1_ce0;
input  [511:0] weight_hh_1_q0;
output  [7:0] bias_ih_0_address0;
output   bias_ih_0_ce0;
input  [15:0] bias_ih_0_q0;
output  [7:0] bias_ih_0_address1;
output   bias_ih_0_ce1;
input  [15:0] bias_ih_0_q1;
output  [7:0] bias_ih_1_address0;
output   bias_ih_1_ce0;
input  [15:0] bias_ih_1_q0;
output  [7:0] bias_ih_1_address1;
output   bias_ih_1_ce1;
input  [15:0] bias_ih_1_q1;
output  [6:0] bn_mul_0_address0;
output   bn_mul_0_ce0;
input  [15:0] bn_mul_0_q0;
output  [6:0] bn_mul_1_address0;
output   bn_mul_1_ce0;
input  [15:0] bn_mul_1_q0;
output  [6:0] bn_add_0_address0;
output   bn_add_0_ce0;
input  [15:0] bn_add_0_q0;
output  [6:0] bn_add_1_address0;
output   bn_add_1_ce0;
input  [15:0] bn_add_1_q0;
output  [10:0] hx_state_q610_0_address0;
output   hx_state_q610_0_ce0;
input  [15:0] hx_state_q610_0_q0;
output  [10:0] hx_state_q610_0_address1;
output   hx_state_q610_0_ce1;
output   hx_state_q610_0_we1;
output  [15:0] hx_state_q610_0_d1;
input  [31:0] hx_state_q610_0_offset;
output  [10:0] hx_state_q610_1_address0;
output   hx_state_q610_1_ce0;
input  [15:0] hx_state_q610_1_q0;
output  [10:0] hx_state_q610_1_address1;
output   hx_state_q610_1_ce1;
output   hx_state_q610_1_we1;
output  [15:0] hx_state_q610_1_d1;
input  [31:0] hx_state_q610_1_offset;
output  [10:0] cx_state_q610_0_address0;
output   cx_state_q610_0_ce0;
input  [15:0] cx_state_q610_0_q0;
output  [10:0] cx_state_q610_0_address1;
output   cx_state_q610_0_ce1;
output   cx_state_q610_0_we1;
output  [15:0] cx_state_q610_0_d1;
input  [31:0] cx_state_q610_0_offset;
output  [10:0] cx_state_q610_1_address0;
output   cx_state_q610_1_ce0;
input  [15:0] cx_state_q610_1_q0;
output  [10:0] cx_state_q610_1_address1;
output   cx_state_q610_1_ce1;
output   cx_state_q610_1_we1;
output  [15:0] cx_state_q610_1_d1;
input  [31:0] cx_state_q610_1_offset;
output  [11:0] output_hy_q610_0_address1;
output   output_hy_q610_0_ce1;
output   output_hy_q610_0_we1;
output  [15:0] output_hy_q610_0_d1;
input  [31:0] output_hy_q610_0_offset;
input  [31:0] output_hy_q610_0_offset1;
output  [11:0] output_hy_q610_1_address1;
output   output_hy_q610_1_ce1;
output   output_hy_q610_1_we1;
output  [15:0] output_hy_q610_1_d1;
input  [31:0] output_hy_q610_1_offset;
input  [31:0] output_hy_q610_1_offset2;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [2:0] empty_fu_2402_p1;
reg   [2:0] empty_reg_3562;
wire   [1:0] empty_618_fu_2407_p1;
reg   [1:0] empty_618_reg_3567;
wire   [2:0] empty_619_fu_2412_p1;
reg   [2:0] empty_619_reg_3572;
wire   [1:0] empty_620_fu_2417_p1;
reg   [1:0] empty_620_reg_3577;
wire   [3:0] empty_621_fu_2422_p1;
reg   [3:0] empty_621_reg_3582;
wire   [3:0] empty_622_fu_2427_p1;
reg   [3:0] empty_622_reg_3587;
wire   [3:0] empty_623_fu_2432_p1;
reg   [3:0] empty_623_reg_3592;
wire   [3:0] empty_624_fu_2437_p1;
reg   [3:0] empty_624_reg_3597;
wire    grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_ap_start;
wire    grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_ap_done;
wire    grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_ap_idle;
wire    grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_ap_ready;
wire   [9:0] grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_weight_ih_0_address0;
wire    grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_weight_ih_0_ce0;
wire   [9:0] grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_weight_ih_1_address0;
wire    grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_weight_ih_1_ce0;
wire   [9:0] grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_weight_hh_0_address0;
wire    grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_weight_hh_0_ce0;
wire   [9:0] grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_weight_hh_1_address0;
wire    grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_weight_hh_1_ce0;
wire   [7:0] grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bias_ih_0_address0;
wire    grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bias_ih_0_ce0;
wire   [7:0] grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bias_ih_0_address1;
wire    grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bias_ih_0_ce1;
wire   [7:0] grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bias_ih_1_address0;
wire    grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bias_ih_1_ce0;
wire   [7:0] grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bias_ih_1_address1;
wire    grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bias_ih_1_ce1;
wire   [6:0] grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bn_mul_0_address0;
wire    grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bn_mul_0_ce0;
wire   [6:0] grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bn_mul_1_address0;
wire    grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bn_mul_1_ce0;
wire   [6:0] grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bn_add_0_address0;
wire    grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bn_add_0_ce0;
wire   [6:0] grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bn_add_1_address0;
wire    grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bn_add_1_ce0;
wire   [10:0] grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_hx_state_q610_0_address0;
wire    grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_hx_state_q610_0_ce0;
wire   [10:0] grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_hx_state_q610_0_address1;
wire    grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_hx_state_q610_0_ce1;
wire    grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_hx_state_q610_0_we1;
wire   [15:0] grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_hx_state_q610_0_d1;
wire   [10:0] grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_hx_state_q610_1_address0;
wire    grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_hx_state_q610_1_ce0;
wire   [10:0] grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_hx_state_q610_1_address1;
wire    grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_hx_state_q610_1_ce1;
wire    grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_hx_state_q610_1_we1;
wire   [15:0] grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_hx_state_q610_1_d1;
wire   [10:0] grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_cx_state_q610_0_address0;
wire    grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_cx_state_q610_0_ce0;
wire   [10:0] grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_cx_state_q610_0_address1;
wire    grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_cx_state_q610_0_ce1;
wire    grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_cx_state_q610_0_we1;
wire   [15:0] grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_cx_state_q610_0_d1;
wire   [10:0] grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_cx_state_q610_1_address0;
wire    grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_cx_state_q610_1_ce0;
wire   [10:0] grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_cx_state_q610_1_address1;
wire    grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_cx_state_q610_1_ce1;
wire    grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_cx_state_q610_1_we1;
wire   [15:0] grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_cx_state_q610_1_d1;
wire   [11:0] grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_output_hy_q610_0_address1;
wire    grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_output_hy_q610_0_ce1;
wire    grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_output_hy_q610_0_we1;
wire   [15:0] grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_output_hy_q610_0_d1;
wire   [11:0] grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_output_hy_q610_1_address1;
wire    grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_output_hy_q610_1_ce1;
wire    grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_output_hy_q610_1_we1;
wire   [15:0] grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_output_hy_q610_1_d1;
reg    grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_ap_start_reg;
wire    ap_CS_fsm_state2;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_ap_start_reg = 1'b0;
end

SubbandRealtimeTopQ610Ip_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_ap_start),
    .ap_done(grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_ap_done),
    .ap_idle(grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_ap_idle),
    .ap_ready(grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_ap_ready),
    .input_ptr_0_val1(p_read),
    .input_ptr_1_val2(p_read1),
    .input_ptr_2_val3(p_read2),
    .input_ptr_3_val4(p_read3),
    .input_ptr_4_val5(p_read4),
    .input_ptr_5_val6(p_read5),
    .input_ptr_6_val7(p_read6),
    .input_ptr_7_val8(p_read7),
    .input_ptr_8_val9(p_read8),
    .input_ptr_9_val10(p_read9),
    .input_ptr_10_val11(p_read10),
    .input_ptr_11_val12(p_read11),
    .input_ptr_12_val13(p_read12),
    .input_ptr_13_val14(p_read13),
    .input_ptr_14_val15(p_read14),
    .input_ptr_15_val16(p_read15),
    .input_ptr_16_val17(p_read16),
    .input_ptr_17_val18(p_read17),
    .input_ptr_18_val19(p_read18),
    .input_ptr_19_val20(p_read19),
    .input_ptr_20_val21(p_read20),
    .input_ptr_21_val22(p_read21),
    .input_ptr_22_val23(p_read22),
    .input_ptr_23_val24(p_read23),
    .input_ptr_24_val25(p_read24),
    .input_ptr_25_val26(p_read25),
    .input_ptr_26_val27(p_read26),
    .input_ptr_27_val28(p_read27),
    .input_ptr_28_val29(p_read28),
    .input_ptr_29_val30(p_read29),
    .input_ptr_30_val31(p_read30),
    .input_ptr_31_val32(p_read31),
    .input_ptr_32_val33(p_read32),
    .input_ptr_33_val34(p_read33),
    .input_ptr_34_val35(p_read34),
    .input_ptr_35_val36(p_read35),
    .input_ptr_36_val37(p_read36),
    .input_ptr_37_val38(p_read37),
    .input_ptr_38_val39(p_read38),
    .input_ptr_39_val40(p_read39),
    .input_ptr_40_val41(p_read40),
    .input_ptr_41_val42(p_read41),
    .input_ptr_42_val43(p_read42),
    .input_ptr_43_val44(p_read43),
    .input_ptr_44_val45(p_read44),
    .input_ptr_45_val46(p_read45),
    .input_ptr_46_val47(p_read46),
    .input_ptr_47_val48(p_read47),
    .input_ptr_48_val49(p_read48),
    .input_ptr_49_val50(p_read49),
    .input_ptr_50_val51(p_read50),
    .input_ptr_51_val52(p_read51),
    .input_ptr_52_val53(p_read52),
    .input_ptr_53_val54(p_read53),
    .input_ptr_54_val55(p_read54),
    .input_ptr_55_val56(p_read55),
    .input_ptr_56_val57(p_read56),
    .input_ptr_57_val58(p_read57),
    .input_ptr_58_val59(p_read58),
    .input_ptr_59_val60(p_read59),
    .input_ptr_60_val61(p_read60),
    .input_ptr_61_val62(p_read61),
    .input_ptr_62_val63(p_read62),
    .input_ptr_63_val64(p_read63),
    .input_ptr_64_val65(p_read64),
    .input_ptr_65_val66(p_read65),
    .input_ptr_66_val67(p_read66),
    .input_ptr_67_val68(p_read67),
    .input_ptr_68_val69(p_read68),
    .input_ptr_69_val70(p_read69),
    .input_ptr_70_val71(p_read70),
    .input_ptr_71_val72(p_read71),
    .input_ptr_72_val73(p_read72),
    .input_ptr_73_val74(p_read73),
    .input_ptr_74_val75(p_read74),
    .input_ptr_75_val76(p_read75),
    .input_ptr_76_val77(p_read76),
    .input_ptr_77_val78(p_read77),
    .input_ptr_78_val79(p_read78),
    .input_ptr_79_val80(p_read79),
    .input_ptr_80_val81(p_read80),
    .input_ptr_81_val82(p_read81),
    .input_ptr_82_val83(p_read82),
    .input_ptr_83_val84(p_read83),
    .input_ptr_84_val85(p_read84),
    .input_ptr_85_val86(p_read85),
    .input_ptr_86_val87(p_read86),
    .input_ptr_87_val88(p_read87),
    .input_ptr_88_val89(p_read88),
    .input_ptr_89_val90(p_read89),
    .input_ptr_90_val91(p_read90),
    .input_ptr_91_val92(p_read91),
    .input_ptr_92_val93(p_read92),
    .input_ptr_93_val94(p_read93),
    .input_ptr_94_val95(p_read94),
    .input_ptr_95_val96(p_read95),
    .input_ptr_96_val97(p_read96),
    .input_ptr_97_val98(p_read97),
    .input_ptr_98_val99(p_read98),
    .input_ptr_99_val100(p_read99),
    .input_ptr_100_val101(p_read100),
    .input_ptr_101_val102(p_read101),
    .input_ptr_102_val103(p_read102),
    .input_ptr_103_val104(p_read103),
    .input_ptr_104_val105(p_read104),
    .input_ptr_105_val106(p_read105),
    .input_ptr_106_val107(p_read106),
    .input_ptr_107_val108(p_read107),
    .input_ptr_108_val109(p_read108),
    .input_ptr_109_val110(p_read109),
    .input_ptr_110_val111(p_read110),
    .input_ptr_111_val112(p_read111),
    .input_ptr_112_val113(p_read112),
    .input_ptr_113_val114(p_read113),
    .input_ptr_114_val115(p_read114),
    .input_ptr_115_val116(p_read115),
    .input_ptr_116_val117(p_read116),
    .input_ptr_117_val118(p_read117),
    .input_ptr_118_val119(p_read118),
    .input_ptr_119_val120(p_read119),
    .input_ptr_120_val121(p_read120),
    .input_ptr_121_val122(p_read121),
    .input_ptr_122_val123(p_read122),
    .input_ptr_123_val124(p_read123),
    .input_ptr_124_val125(p_read124),
    .input_ptr_125_val126(p_read125),
    .input_ptr_126_val127(p_read126),
    .input_ptr_127_val128(p_read127),
    .input_ptr_128_val129(p_read128),
    .input_ptr_129_val130(p_read129),
    .input_ptr_130_val131(p_read130),
    .input_ptr_131_val132(p_read131),
    .input_ptr_132_val133(p_read132),
    .input_ptr_133_val134(p_read133),
    .input_ptr_134_val135(p_read134),
    .input_ptr_135_val136(p_read135),
    .input_ptr_136_val137(p_read136),
    .input_ptr_137_val138(p_read137),
    .input_ptr_138_val139(p_read138),
    .input_ptr_139_val140(p_read139),
    .input_ptr_140_val141(p_read140),
    .input_ptr_141_val142(p_read141),
    .input_ptr_142_val143(p_read142),
    .input_ptr_143_val144(p_read143),
    .input_ptr_144_val145(p_read144),
    .input_ptr_145_val146(p_read145),
    .input_ptr_146_val147(p_read146),
    .input_ptr_147_val148(p_read147),
    .input_ptr_148_val149(p_read148),
    .input_ptr_149_val150(p_read149),
    .input_ptr_150_val151(p_read150),
    .input_ptr_151_val152(p_read151),
    .input_ptr_152_val153(p_read152),
    .input_ptr_153_val154(p_read153),
    .input_ptr_154_val155(p_read154),
    .input_ptr_155_val156(p_read155),
    .input_ptr_156_val157(p_read156),
    .input_ptr_157_val158(p_read157),
    .input_ptr_158_val159(p_read158),
    .input_ptr_159_val160(p_read159),
    .input_ptr_160_val161(p_read160),
    .input_ptr_161_val162(p_read161),
    .input_ptr_162_val163(p_read162),
    .input_ptr_163_val164(p_read163),
    .input_ptr_164_val165(p_read164),
    .input_ptr_165_val166(p_read165),
    .input_ptr_166_val167(p_read166),
    .input_ptr_167_val168(p_read167),
    .input_ptr_168_val169(p_read168),
    .input_ptr_169_val170(p_read169),
    .input_ptr_170_val171(p_read170),
    .input_ptr_171_val172(p_read171),
    .input_ptr_172_val173(p_read172),
    .input_ptr_173_val174(p_read173),
    .input_ptr_174_val175(p_read174),
    .input_ptr_175_val176(p_read175),
    .input_ptr_176_val177(p_read176),
    .input_ptr_177_val178(p_read177),
    .input_ptr_178_val179(p_read178),
    .input_ptr_179_val180(p_read179),
    .input_ptr_180_val181(p_read180),
    .input_ptr_181_val182(p_read181),
    .input_ptr_182_val183(p_read182),
    .input_ptr_183_val184(p_read183),
    .input_ptr_184_val185(p_read184),
    .input_ptr_185_val186(p_read185),
    .input_ptr_186_val187(p_read186),
    .input_ptr_187_val188(p_read187),
    .input_ptr_188_val189(p_read188),
    .input_ptr_189_val190(p_read189),
    .input_ptr_190_val191(p_read190),
    .input_ptr_191_val192(p_read191),
    .input_ptr_192_val193(p_read192),
    .input_ptr_193_val194(p_read193),
    .input_ptr_194_val195(p_read194),
    .input_ptr_195_val196(p_read195),
    .input_ptr_196_val197(p_read196),
    .input_ptr_197_val198(p_read197),
    .input_ptr_198_val199(p_read198),
    .input_ptr_199_val200(p_read199),
    .input_ptr_200_val201(p_read200),
    .input_ptr_201_val202(p_read201),
    .input_ptr_202_val203(p_read202),
    .input_ptr_203_val204(p_read203),
    .input_ptr_204_val205(p_read204),
    .input_ptr_205_val206(p_read205),
    .input_ptr_206_val207(p_read206),
    .input_ptr_207_val208(p_read207),
    .input_ptr_208_val209(p_read208),
    .input_ptr_209_val210(p_read209),
    .input_ptr_210_val211(p_read210),
    .input_ptr_211_val212(p_read211),
    .input_ptr_212_val213(p_read212),
    .input_ptr_213_val214(p_read213),
    .input_ptr_214_val215(p_read214),
    .input_ptr_215_val216(p_read215),
    .input_ptr_216_val217(p_read216),
    .input_ptr_217_val218(p_read217),
    .input_ptr_218_val219(p_read218),
    .input_ptr_219_val220(p_read219),
    .input_ptr_220_val221(p_read220),
    .input_ptr_221_val222(p_read221),
    .input_ptr_222_val223(p_read222),
    .input_ptr_223_val224(p_read223),
    .weight_ih_0_address0(grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_weight_ih_0_address0),
    .weight_ih_0_ce0(grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_weight_ih_0_ce0),
    .weight_ih_0_q0(weight_ih_0_q0),
    .weight_ih_1_address0(grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_weight_ih_1_address0),
    .weight_ih_1_ce0(grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_weight_ih_1_ce0),
    .weight_ih_1_q0(weight_ih_1_q0),
    .weight_hh_0_address0(grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_weight_hh_0_address0),
    .weight_hh_0_ce0(grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_weight_hh_0_ce0),
    .weight_hh_0_q0(weight_hh_0_q0),
    .weight_hh_1_address0(grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_weight_hh_1_address0),
    .weight_hh_1_ce0(grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_weight_hh_1_ce0),
    .weight_hh_1_q0(weight_hh_1_q0),
    .bias_ih_0_address0(grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bias_ih_0_address0),
    .bias_ih_0_ce0(grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bias_ih_0_ce0),
    .bias_ih_0_q0(bias_ih_0_q0),
    .bias_ih_0_address1(grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bias_ih_0_address1),
    .bias_ih_0_ce1(grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bias_ih_0_ce1),
    .bias_ih_0_q1(bias_ih_0_q1),
    .bias_ih_1_address0(grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bias_ih_1_address0),
    .bias_ih_1_ce0(grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bias_ih_1_ce0),
    .bias_ih_1_q0(bias_ih_1_q0),
    .bias_ih_1_address1(grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bias_ih_1_address1),
    .bias_ih_1_ce1(grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bias_ih_1_ce1),
    .bias_ih_1_q1(bias_ih_1_q1),
    .bn_mul_0_address0(grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bn_mul_0_address0),
    .bn_mul_0_ce0(grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bn_mul_0_ce0),
    .bn_mul_0_q0(bn_mul_0_q0),
    .bn_mul_1_address0(grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bn_mul_1_address0),
    .bn_mul_1_ce0(grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bn_mul_1_ce0),
    .bn_mul_1_q0(bn_mul_1_q0),
    .bn_add_0_address0(grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bn_add_0_address0),
    .bn_add_0_ce0(grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bn_add_0_ce0),
    .bn_add_0_q0(bn_add_0_q0),
    .bn_add_1_address0(grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bn_add_1_address0),
    .bn_add_1_ce0(grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bn_add_1_ce0),
    .bn_add_1_q0(bn_add_1_q0),
    .hx_state_q610_0_address0(grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_hx_state_q610_0_address0),
    .hx_state_q610_0_ce0(grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_hx_state_q610_0_ce0),
    .hx_state_q610_0_q0(hx_state_q610_0_q0),
    .hx_state_q610_0_address1(grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_hx_state_q610_0_address1),
    .hx_state_q610_0_ce1(grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_hx_state_q610_0_ce1),
    .hx_state_q610_0_we1(grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_hx_state_q610_0_we1),
    .hx_state_q610_0_d1(grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_hx_state_q610_0_d1),
    .hx_state_q610_0_offset(empty_624_reg_3597),
    .hx_state_q610_1_address0(grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_hx_state_q610_1_address0),
    .hx_state_q610_1_ce0(grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_hx_state_q610_1_ce0),
    .hx_state_q610_1_q0(hx_state_q610_1_q0),
    .hx_state_q610_1_address1(grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_hx_state_q610_1_address1),
    .hx_state_q610_1_ce1(grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_hx_state_q610_1_ce1),
    .hx_state_q610_1_we1(grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_hx_state_q610_1_we1),
    .hx_state_q610_1_d1(grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_hx_state_q610_1_d1),
    .hx_state_q610_1_offset(empty_623_reg_3592),
    .cx_state_q610_0_address0(grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_cx_state_q610_0_address0),
    .cx_state_q610_0_ce0(grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_cx_state_q610_0_ce0),
    .cx_state_q610_0_q0(cx_state_q610_0_q0),
    .cx_state_q610_0_address1(grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_cx_state_q610_0_address1),
    .cx_state_q610_0_ce1(grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_cx_state_q610_0_ce1),
    .cx_state_q610_0_we1(grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_cx_state_q610_0_we1),
    .cx_state_q610_0_d1(grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_cx_state_q610_0_d1),
    .cx_state_q610_0_offset(empty_622_reg_3587),
    .cx_state_q610_1_address0(grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_cx_state_q610_1_address0),
    .cx_state_q610_1_ce0(grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_cx_state_q610_1_ce0),
    .cx_state_q610_1_q0(cx_state_q610_1_q0),
    .cx_state_q610_1_address1(grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_cx_state_q610_1_address1),
    .cx_state_q610_1_ce1(grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_cx_state_q610_1_ce1),
    .cx_state_q610_1_we1(grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_cx_state_q610_1_we1),
    .cx_state_q610_1_d1(grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_cx_state_q610_1_d1),
    .cx_state_q610_1_offset(empty_621_reg_3582),
    .output_hy_q610_0_address1(grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_output_hy_q610_0_address1),
    .output_hy_q610_0_ce1(grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_output_hy_q610_0_ce1),
    .output_hy_q610_0_we1(grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_output_hy_q610_0_we1),
    .output_hy_q610_0_d1(grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_output_hy_q610_0_d1),
    .output_hy_q610_0_offset(empty_620_reg_3577),
    .output_hy_q610_0_offset1(empty_619_reg_3572),
    .output_hy_q610_1_address1(grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_output_hy_q610_1_address1),
    .output_hy_q610_1_ce1(grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_output_hy_q610_1_ce1),
    .output_hy_q610_1_we1(grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_output_hy_q610_1_we1),
    .output_hy_q610_1_d1(grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_output_hy_q610_1_d1),
    .output_hy_q610_1_offset(empty_618_reg_3567),
    .output_hy_q610_1_offset2(empty_reg_3562)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_ap_start_reg <= 1'b1;
        end else if ((grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_ap_ready == 1'b1)) begin
            grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        empty_618_reg_3567 <= empty_618_fu_2407_p1;
        empty_619_reg_3572 <= empty_619_fu_2412_p1;
        empty_620_reg_3577 <= empty_620_fu_2417_p1;
        empty_621_reg_3582 <= empty_621_fu_2422_p1;
        empty_622_reg_3587 <= empty_622_fu_2427_p1;
        empty_623_reg_3592 <= empty_623_fu_2432_p1;
        empty_624_reg_3597 <= empty_624_fu_2437_p1;
        empty_reg_3562 <= empty_fu_2402_p1;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign bias_ih_0_address0 = grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bias_ih_0_address0;

assign bias_ih_0_address1 = grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bias_ih_0_address1;

assign bias_ih_0_ce0 = grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bias_ih_0_ce0;

assign bias_ih_0_ce1 = grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bias_ih_0_ce1;

assign bias_ih_1_address0 = grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bias_ih_1_address0;

assign bias_ih_1_address1 = grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bias_ih_1_address1;

assign bias_ih_1_ce0 = grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bias_ih_1_ce0;

assign bias_ih_1_ce1 = grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bias_ih_1_ce1;

assign bn_add_0_address0 = grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bn_add_0_address0;

assign bn_add_0_ce0 = grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bn_add_0_ce0;

assign bn_add_1_address0 = grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bn_add_1_address0;

assign bn_add_1_ce0 = grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bn_add_1_ce0;

assign bn_mul_0_address0 = grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bn_mul_0_address0;

assign bn_mul_0_ce0 = grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bn_mul_0_ce0;

assign bn_mul_1_address0 = grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bn_mul_1_address0;

assign bn_mul_1_ce0 = grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_bn_mul_1_ce0;

assign cx_state_q610_0_address0 = grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_cx_state_q610_0_address0;

assign cx_state_q610_0_address1 = grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_cx_state_q610_0_address1;

assign cx_state_q610_0_ce0 = grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_cx_state_q610_0_ce0;

assign cx_state_q610_0_ce1 = grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_cx_state_q610_0_ce1;

assign cx_state_q610_0_d1 = grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_cx_state_q610_0_d1;

assign cx_state_q610_0_we1 = grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_cx_state_q610_0_we1;

assign cx_state_q610_1_address0 = grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_cx_state_q610_1_address0;

assign cx_state_q610_1_address1 = grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_cx_state_q610_1_address1;

assign cx_state_q610_1_ce0 = grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_cx_state_q610_1_ce0;

assign cx_state_q610_1_ce1 = grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_cx_state_q610_1_ce1;

assign cx_state_q610_1_d1 = grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_cx_state_q610_1_d1;

assign cx_state_q610_1_we1 = grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_cx_state_q610_1_we1;

assign empty_618_fu_2407_p1 = output_hy_q610_1_offset[1:0];

assign empty_619_fu_2412_p1 = output_hy_q610_0_offset1[2:0];

assign empty_620_fu_2417_p1 = output_hy_q610_0_offset[1:0];

assign empty_621_fu_2422_p1 = cx_state_q610_1_offset[3:0];

assign empty_622_fu_2427_p1 = cx_state_q610_0_offset[3:0];

assign empty_623_fu_2432_p1 = hx_state_q610_1_offset[3:0];

assign empty_624_fu_2437_p1 = hx_state_q610_0_offset[3:0];

assign empty_fu_2402_p1 = output_hy_q610_1_offset2[2:0];

assign grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_ap_start = grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_ap_start_reg;

assign hx_state_q610_0_address0 = grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_hx_state_q610_0_address0;

assign hx_state_q610_0_address1 = grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_hx_state_q610_0_address1;

assign hx_state_q610_0_ce0 = grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_hx_state_q610_0_ce0;

assign hx_state_q610_0_ce1 = grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_hx_state_q610_0_ce1;

assign hx_state_q610_0_d1 = grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_hx_state_q610_0_d1;

assign hx_state_q610_0_we1 = grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_hx_state_q610_0_we1;

assign hx_state_q610_1_address0 = grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_hx_state_q610_1_address0;

assign hx_state_q610_1_address1 = grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_hx_state_q610_1_address1;

assign hx_state_q610_1_ce0 = grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_hx_state_q610_1_ce0;

assign hx_state_q610_1_ce1 = grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_hx_state_q610_1_ce1;

assign hx_state_q610_1_d1 = grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_hx_state_q610_1_d1;

assign hx_state_q610_1_we1 = grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_hx_state_q610_1_we1;

assign output_hy_q610_0_address1 = grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_output_hy_q610_0_address1;

assign output_hy_q610_0_ce1 = grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_output_hy_q610_0_ce1;

assign output_hy_q610_0_d1 = grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_output_hy_q610_0_d1;

assign output_hy_q610_0_we1 = grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_output_hy_q610_0_we1;

assign output_hy_q610_1_address1 = grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_output_hy_q610_1_address1;

assign output_hy_q610_1_ce1 = grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_output_hy_q610_1_ce1;

assign output_hy_q610_1_d1 = grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_output_hy_q610_1_d1;

assign output_hy_q610_1_we1 = grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_output_hy_q610_1_we1;

assign weight_hh_0_address0 = grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_weight_hh_0_address0;

assign weight_hh_0_ce0 = grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_weight_hh_0_ce0;

assign weight_hh_1_address0 = grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_weight_hh_1_address0;

assign weight_hh_1_ce0 = grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_weight_hh_1_ce0;

assign weight_ih_0_address0 = grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_weight_ih_0_address0;

assign weight_ih_0_ce0 = grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_weight_ih_0_ce0;

assign weight_ih_1_address0 = grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_weight_ih_1_address0;

assign weight_ih_1_ce0 = grp_p_anonymous_namespace_RunRealtimeGSUCellFixedQ610_224_2_32_32_true_s_fu_1906_weight_ih_1_ce0;

endmodule //SubbandRealtimeTopQ610Ip_p_anonymous_namespace_RunRealtimeGSUCellSharedQ610
