// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module SubbandRealtimeTopQ610Ip_p_anonymous_namespace_ProjectionDotProductRealtimeRowFixedDspQ610_Pipeline_VITIS_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        sub_ln4480_1,
        sub_ln4480,
        proj_row_0_val,
        proj_row_16_val,
        proj_row_32_val,
        proj_row_48_val,
        proj_row_64_val,
        proj_row_80_val,
        proj_row_96_val,
        proj_row_112_val,
        proj_row_128_val,
        proj_row_144_val,
        proj_row_160_val,
        proj_row_176_val,
        proj_row_192_val,
        proj_row_208_val,
        proj_row_1_val,
        proj_row_17_val,
        proj_row_33_val,
        proj_row_49_val,
        proj_row_65_val,
        proj_row_81_val,
        proj_row_97_val,
        proj_row_113_val,
        proj_row_129_val,
        proj_row_145_val,
        proj_row_161_val,
        proj_row_177_val,
        proj_row_193_val,
        proj_row_209_val,
        proj_row_2_val,
        proj_row_18_val,
        proj_row_34_val,
        proj_row_50_val,
        proj_row_66_val,
        proj_row_82_val,
        proj_row_98_val,
        proj_row_114_val,
        proj_row_130_val,
        proj_row_146_val,
        proj_row_162_val,
        proj_row_178_val,
        proj_row_194_val,
        proj_row_210_val,
        proj_row_3_val,
        proj_row_19_val,
        proj_row_35_val,
        proj_row_51_val,
        proj_row_67_val,
        proj_row_83_val,
        proj_row_99_val,
        proj_row_115_val,
        proj_row_131_val,
        proj_row_147_val,
        proj_row_163_val,
        proj_row_179_val,
        proj_row_195_val,
        proj_row_211_val,
        proj_row_4_val,
        proj_row_20_val,
        proj_row_36_val,
        proj_row_52_val,
        proj_row_68_val,
        proj_row_84_val,
        proj_row_100_val,
        proj_row_116_val,
        proj_row_132_val,
        proj_row_148_val,
        proj_row_164_val,
        proj_row_180_val,
        proj_row_196_val,
        proj_row_212_val,
        proj_row_5_val,
        proj_row_21_val,
        proj_row_37_val,
        proj_row_53_val,
        proj_row_69_val,
        proj_row_85_val,
        proj_row_101_val,
        proj_row_117_val,
        proj_row_133_val,
        proj_row_149_val,
        proj_row_165_val,
        proj_row_181_val,
        proj_row_197_val,
        proj_row_213_val,
        proj_row_6_val,
        proj_row_22_val,
        proj_row_38_val,
        proj_row_54_val,
        proj_row_70_val,
        proj_row_86_val,
        proj_row_102_val,
        proj_row_118_val,
        proj_row_134_val,
        proj_row_150_val,
        proj_row_166_val,
        proj_row_182_val,
        proj_row_198_val,
        proj_row_214_val,
        proj_row_7_val,
        proj_row_23_val,
        proj_row_39_val,
        proj_row_55_val,
        proj_row_71_val,
        proj_row_87_val,
        proj_row_103_val,
        proj_row_119_val,
        proj_row_135_val,
        proj_row_151_val,
        proj_row_167_val,
        proj_row_183_val,
        proj_row_199_val,
        proj_row_215_val,
        proj_row_8_val,
        proj_row_24_val,
        proj_row_40_val,
        proj_row_56_val,
        proj_row_72_val,
        proj_row_88_val,
        proj_row_104_val,
        proj_row_120_val,
        proj_row_136_val,
        proj_row_152_val,
        proj_row_168_val,
        proj_row_184_val,
        proj_row_200_val,
        proj_row_216_val,
        proj_row_9_val,
        proj_row_25_val,
        proj_row_41_val,
        proj_row_57_val,
        proj_row_73_val,
        proj_row_89_val,
        proj_row_105_val,
        proj_row_121_val,
        proj_row_137_val,
        proj_row_153_val,
        proj_row_169_val,
        proj_row_185_val,
        proj_row_201_val,
        proj_row_217_val,
        proj_row_10_val,
        proj_row_26_val,
        proj_row_42_val,
        proj_row_58_val,
        proj_row_74_val,
        proj_row_90_val,
        proj_row_106_val,
        proj_row_122_val,
        proj_row_138_val,
        proj_row_154_val,
        proj_row_170_val,
        proj_row_186_val,
        proj_row_202_val,
        proj_row_218_val,
        proj_row_11_val,
        proj_row_27_val,
        proj_row_43_val,
        proj_row_59_val,
        proj_row_75_val,
        proj_row_91_val,
        proj_row_107_val,
        proj_row_123_val,
        proj_row_139_val,
        proj_row_155_val,
        proj_row_171_val,
        proj_row_187_val,
        proj_row_203_val,
        proj_row_219_val,
        proj_row_12_val,
        proj_row_28_val,
        proj_row_44_val,
        proj_row_60_val,
        proj_row_76_val,
        proj_row_92_val,
        proj_row_108_val,
        proj_row_124_val,
        proj_row_140_val,
        proj_row_156_val,
        proj_row_172_val,
        proj_row_188_val,
        proj_row_204_val,
        proj_row_220_val,
        proj_row_13_val,
        proj_row_29_val,
        proj_row_45_val,
        proj_row_61_val,
        proj_row_77_val,
        proj_row_93_val,
        proj_row_109_val,
        proj_row_125_val,
        proj_row_141_val,
        proj_row_157_val,
        proj_row_173_val,
        proj_row_189_val,
        proj_row_205_val,
        proj_row_221_val,
        proj_row_14_val,
        proj_row_30_val,
        proj_row_46_val,
        proj_row_62_val,
        proj_row_78_val,
        proj_row_94_val,
        proj_row_110_val,
        proj_row_126_val,
        proj_row_142_val,
        proj_row_158_val,
        proj_row_174_val,
        proj_row_190_val,
        proj_row_206_val,
        proj_row_222_val,
        proj_row_15_val,
        proj_row_31_val,
        proj_row_47_val,
        proj_row_63_val,
        proj_row_79_val,
        proj_row_95_val,
        proj_row_111_val,
        proj_row_127_val,
        proj_row_143_val,
        proj_row_159_val,
        proj_row_175_val,
        proj_row_191_val,
        proj_row_207_val,
        proj_row_223_val,
        p_out,
        p_out_ap_vld,
        p_out1,
        p_out1_ap_vld,
        p_out2,
        p_out2_ap_vld,
        p_out3,
        p_out3_ap_vld,
        p_out4,
        p_out4_ap_vld,
        p_out5,
        p_out5_ap_vld,
        p_out6,
        p_out6_ap_vld,
        p_out7,
        p_out7_ap_vld,
        p_out8,
        p_out8_ap_vld,
        p_out9,
        p_out9_ap_vld,
        p_out10,
        p_out10_ap_vld,
        p_out11,
        p_out11_ap_vld,
        p_out12,
        p_out12_ap_vld,
        p_out13,
        p_out13_ap_vld,
        p_out14,
        p_out14_ap_vld,
        p_out15,
        p_out15_ap_vld,
        RunSubbandRealtimeTopCoreQ610_stream_stream_ap_uint_const_int_bool_stream_la_1_address0,
        RunSubbandRealtimeTopCoreQ610_stream_stream_ap_uint_const_int_bool_stream_la_1_ce0,
        RunSubbandRealtimeTopCoreQ610_stream_stream_ap_uint_const_int_bool_stream_la_1_q0,
        RunSubbandRealtimeTopCoreQ610_stream_stream_ap_uint_const_int_bool_stream_la_1_address1,
        RunSubbandRealtimeTopCoreQ610_stream_stream_ap_uint_const_int_bool_stream_la_1_ce1,
        RunSubbandRealtimeTopCoreQ610_stream_stream_ap_uint_const_int_bool_stream_la_1_q1,
        RunSubbandRealtimeTopCoreQ610_stream_stream_ap_uint_const_int_bool_stream_la_address0,
        RunSubbandRealtimeTopCoreQ610_stream_stream_ap_uint_const_int_bool_stream_la_ce0,
        RunSubbandRealtimeTopCoreQ610_stream_stream_ap_uint_const_int_bool_stream_la_q0,
        RunSubbandRealtimeTopCoreQ610_stream_stream_ap_uint_const_int_bool_stream_la_address1,
        RunSubbandRealtimeTopCoreQ610_stream_stream_ap_uint_const_int_bool_stream_la_ce1,
        RunSubbandRealtimeTopCoreQ610_stream_stream_ap_uint_const_int_bool_stream_la_q1
);

parameter    ap_ST_fsm_pp0_stage0 = 4'd1;
parameter    ap_ST_fsm_pp0_stage1 = 4'd2;
parameter    ap_ST_fsm_pp0_stage2 = 4'd4;
parameter    ap_ST_fsm_pp0_stage3 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [11:0] sub_ln4480_1;
input  [11:0] sub_ln4480;
input  [15:0] proj_row_0_val;
input  [15:0] proj_row_16_val;
input  [15:0] proj_row_32_val;
input  [15:0] proj_row_48_val;
input  [15:0] proj_row_64_val;
input  [15:0] proj_row_80_val;
input  [15:0] proj_row_96_val;
input  [15:0] proj_row_112_val;
input  [15:0] proj_row_128_val;
input  [15:0] proj_row_144_val;
input  [15:0] proj_row_160_val;
input  [15:0] proj_row_176_val;
input  [15:0] proj_row_192_val;
input  [15:0] proj_row_208_val;
input  [15:0] proj_row_1_val;
input  [15:0] proj_row_17_val;
input  [15:0] proj_row_33_val;
input  [15:0] proj_row_49_val;
input  [15:0] proj_row_65_val;
input  [15:0] proj_row_81_val;
input  [15:0] proj_row_97_val;
input  [15:0] proj_row_113_val;
input  [15:0] proj_row_129_val;
input  [15:0] proj_row_145_val;
input  [15:0] proj_row_161_val;
input  [15:0] proj_row_177_val;
input  [15:0] proj_row_193_val;
input  [15:0] proj_row_209_val;
input  [15:0] proj_row_2_val;
input  [15:0] proj_row_18_val;
input  [15:0] proj_row_34_val;
input  [15:0] proj_row_50_val;
input  [15:0] proj_row_66_val;
input  [15:0] proj_row_82_val;
input  [15:0] proj_row_98_val;
input  [15:0] proj_row_114_val;
input  [15:0] proj_row_130_val;
input  [15:0] proj_row_146_val;
input  [15:0] proj_row_162_val;
input  [15:0] proj_row_178_val;
input  [15:0] proj_row_194_val;
input  [15:0] proj_row_210_val;
input  [15:0] proj_row_3_val;
input  [15:0] proj_row_19_val;
input  [15:0] proj_row_35_val;
input  [15:0] proj_row_51_val;
input  [15:0] proj_row_67_val;
input  [15:0] proj_row_83_val;
input  [15:0] proj_row_99_val;
input  [15:0] proj_row_115_val;
input  [15:0] proj_row_131_val;
input  [15:0] proj_row_147_val;
input  [15:0] proj_row_163_val;
input  [15:0] proj_row_179_val;
input  [15:0] proj_row_195_val;
input  [15:0] proj_row_211_val;
input  [15:0] proj_row_4_val;
input  [15:0] proj_row_20_val;
input  [15:0] proj_row_36_val;
input  [15:0] proj_row_52_val;
input  [15:0] proj_row_68_val;
input  [15:0] proj_row_84_val;
input  [15:0] proj_row_100_val;
input  [15:0] proj_row_116_val;
input  [15:0] proj_row_132_val;
input  [15:0] proj_row_148_val;
input  [15:0] proj_row_164_val;
input  [15:0] proj_row_180_val;
input  [15:0] proj_row_196_val;
input  [15:0] proj_row_212_val;
input  [15:0] proj_row_5_val;
input  [15:0] proj_row_21_val;
input  [15:0] proj_row_37_val;
input  [15:0] proj_row_53_val;
input  [15:0] proj_row_69_val;
input  [15:0] proj_row_85_val;
input  [15:0] proj_row_101_val;
input  [15:0] proj_row_117_val;
input  [15:0] proj_row_133_val;
input  [15:0] proj_row_149_val;
input  [15:0] proj_row_165_val;
input  [15:0] proj_row_181_val;
input  [15:0] proj_row_197_val;
input  [15:0] proj_row_213_val;
input  [15:0] proj_row_6_val;
input  [15:0] proj_row_22_val;
input  [15:0] proj_row_38_val;
input  [15:0] proj_row_54_val;
input  [15:0] proj_row_70_val;
input  [15:0] proj_row_86_val;
input  [15:0] proj_row_102_val;
input  [15:0] proj_row_118_val;
input  [15:0] proj_row_134_val;
input  [15:0] proj_row_150_val;
input  [15:0] proj_row_166_val;
input  [15:0] proj_row_182_val;
input  [15:0] proj_row_198_val;
input  [15:0] proj_row_214_val;
input  [15:0] proj_row_7_val;
input  [15:0] proj_row_23_val;
input  [15:0] proj_row_39_val;
input  [15:0] proj_row_55_val;
input  [15:0] proj_row_71_val;
input  [15:0] proj_row_87_val;
input  [15:0] proj_row_103_val;
input  [15:0] proj_row_119_val;
input  [15:0] proj_row_135_val;
input  [15:0] proj_row_151_val;
input  [15:0] proj_row_167_val;
input  [15:0] proj_row_183_val;
input  [15:0] proj_row_199_val;
input  [15:0] proj_row_215_val;
input  [15:0] proj_row_8_val;
input  [15:0] proj_row_24_val;
input  [15:0] proj_row_40_val;
input  [15:0] proj_row_56_val;
input  [15:0] proj_row_72_val;
input  [15:0] proj_row_88_val;
input  [15:0] proj_row_104_val;
input  [15:0] proj_row_120_val;
input  [15:0] proj_row_136_val;
input  [15:0] proj_row_152_val;
input  [15:0] proj_row_168_val;
input  [15:0] proj_row_184_val;
input  [15:0] proj_row_200_val;
input  [15:0] proj_row_216_val;
input  [15:0] proj_row_9_val;
input  [15:0] proj_row_25_val;
input  [15:0] proj_row_41_val;
input  [15:0] proj_row_57_val;
input  [15:0] proj_row_73_val;
input  [15:0] proj_row_89_val;
input  [15:0] proj_row_105_val;
input  [15:0] proj_row_121_val;
input  [15:0] proj_row_137_val;
input  [15:0] proj_row_153_val;
input  [15:0] proj_row_169_val;
input  [15:0] proj_row_185_val;
input  [15:0] proj_row_201_val;
input  [15:0] proj_row_217_val;
input  [15:0] proj_row_10_val;
input  [15:0] proj_row_26_val;
input  [15:0] proj_row_42_val;
input  [15:0] proj_row_58_val;
input  [15:0] proj_row_74_val;
input  [15:0] proj_row_90_val;
input  [15:0] proj_row_106_val;
input  [15:0] proj_row_122_val;
input  [15:0] proj_row_138_val;
input  [15:0] proj_row_154_val;
input  [15:0] proj_row_170_val;
input  [15:0] proj_row_186_val;
input  [15:0] proj_row_202_val;
input  [15:0] proj_row_218_val;
input  [15:0] proj_row_11_val;
input  [15:0] proj_row_27_val;
input  [15:0] proj_row_43_val;
input  [15:0] proj_row_59_val;
input  [15:0] proj_row_75_val;
input  [15:0] proj_row_91_val;
input  [15:0] proj_row_107_val;
input  [15:0] proj_row_123_val;
input  [15:0] proj_row_139_val;
input  [15:0] proj_row_155_val;
input  [15:0] proj_row_171_val;
input  [15:0] proj_row_187_val;
input  [15:0] proj_row_203_val;
input  [15:0] proj_row_219_val;
input  [15:0] proj_row_12_val;
input  [15:0] proj_row_28_val;
input  [15:0] proj_row_44_val;
input  [15:0] proj_row_60_val;
input  [15:0] proj_row_76_val;
input  [15:0] proj_row_92_val;
input  [15:0] proj_row_108_val;
input  [15:0] proj_row_124_val;
input  [15:0] proj_row_140_val;
input  [15:0] proj_row_156_val;
input  [15:0] proj_row_172_val;
input  [15:0] proj_row_188_val;
input  [15:0] proj_row_204_val;
input  [15:0] proj_row_220_val;
input  [15:0] proj_row_13_val;
input  [15:0] proj_row_29_val;
input  [15:0] proj_row_45_val;
input  [15:0] proj_row_61_val;
input  [15:0] proj_row_77_val;
input  [15:0] proj_row_93_val;
input  [15:0] proj_row_109_val;
input  [15:0] proj_row_125_val;
input  [15:0] proj_row_141_val;
input  [15:0] proj_row_157_val;
input  [15:0] proj_row_173_val;
input  [15:0] proj_row_189_val;
input  [15:0] proj_row_205_val;
input  [15:0] proj_row_221_val;
input  [15:0] proj_row_14_val;
input  [15:0] proj_row_30_val;
input  [15:0] proj_row_46_val;
input  [15:0] proj_row_62_val;
input  [15:0] proj_row_78_val;
input  [15:0] proj_row_94_val;
input  [15:0] proj_row_110_val;
input  [15:0] proj_row_126_val;
input  [15:0] proj_row_142_val;
input  [15:0] proj_row_158_val;
input  [15:0] proj_row_174_val;
input  [15:0] proj_row_190_val;
input  [15:0] proj_row_206_val;
input  [15:0] proj_row_222_val;
input  [15:0] proj_row_15_val;
input  [15:0] proj_row_31_val;
input  [15:0] proj_row_47_val;
input  [15:0] proj_row_63_val;
input  [15:0] proj_row_79_val;
input  [15:0] proj_row_95_val;
input  [15:0] proj_row_111_val;
input  [15:0] proj_row_127_val;
input  [15:0] proj_row_143_val;
input  [15:0] proj_row_159_val;
input  [15:0] proj_row_175_val;
input  [15:0] proj_row_191_val;
input  [15:0] proj_row_207_val;
input  [15:0] proj_row_223_val;
output  [34:0] p_out;
output   p_out_ap_vld;
output  [34:0] p_out1;
output   p_out1_ap_vld;
output  [34:0] p_out2;
output   p_out2_ap_vld;
output  [34:0] p_out3;
output   p_out3_ap_vld;
output  [34:0] p_out4;
output   p_out4_ap_vld;
output  [34:0] p_out5;
output   p_out5_ap_vld;
output  [34:0] p_out6;
output   p_out6_ap_vld;
output  [34:0] p_out7;
output   p_out7_ap_vld;
output  [34:0] p_out8;
output   p_out8_ap_vld;
output  [34:0] p_out9;
output   p_out9_ap_vld;
output  [34:0] p_out10;
output   p_out10_ap_vld;
output  [34:0] p_out11;
output   p_out11_ap_vld;
output  [34:0] p_out12;
output   p_out12_ap_vld;
output  [34:0] p_out13;
output   p_out13_ap_vld;
output  [34:0] p_out14;
output   p_out14_ap_vld;
output  [34:0] p_out15;
output   p_out15_ap_vld;
output  [11:0] RunSubbandRealtimeTopCoreQ610_stream_stream_ap_uint_const_int_bool_stream_la_1_address0;
output   RunSubbandRealtimeTopCoreQ610_stream_stream_ap_uint_const_int_bool_stream_la_1_ce0;
input  [15:0] RunSubbandRealtimeTopCoreQ610_stream_stream_ap_uint_const_int_bool_stream_la_1_q0;
output  [11:0] RunSubbandRealtimeTopCoreQ610_stream_stream_ap_uint_const_int_bool_stream_la_1_address1;
output   RunSubbandRealtimeTopCoreQ610_stream_stream_ap_uint_const_int_bool_stream_la_1_ce1;
input  [15:0] RunSubbandRealtimeTopCoreQ610_stream_stream_ap_uint_const_int_bool_stream_la_1_q1;
output  [11:0] RunSubbandRealtimeTopCoreQ610_stream_stream_ap_uint_const_int_bool_stream_la_address0;
output   RunSubbandRealtimeTopCoreQ610_stream_stream_ap_uint_const_int_bool_stream_la_ce0;
input  [15:0] RunSubbandRealtimeTopCoreQ610_stream_stream_ap_uint_const_int_bool_stream_la_q0;
output  [11:0] RunSubbandRealtimeTopCoreQ610_stream_stream_ap_uint_const_int_bool_stream_la_address1;
output   RunSubbandRealtimeTopCoreQ610_stream_stream_ap_uint_const_int_bool_stream_la_ce1;
input  [15:0] RunSubbandRealtimeTopCoreQ610_stream_stream_ap_uint_const_int_bool_stream_la_q1;

reg ap_idle;
reg p_out_ap_vld;
reg p_out1_ap_vld;
reg p_out2_ap_vld;
reg p_out3_ap_vld;
reg p_out4_ap_vld;
reg p_out5_ap_vld;
reg p_out6_ap_vld;
reg p_out7_ap_vld;
reg p_out8_ap_vld;
reg p_out9_ap_vld;
reg p_out10_ap_vld;
reg p_out11_ap_vld;
reg p_out12_ap_vld;
reg p_out13_ap_vld;
reg p_out14_ap_vld;
reg p_out15_ap_vld;
reg[11:0] RunSubbandRealtimeTopCoreQ610_stream_stream_ap_uint_const_int_bool_stream_la_1_address0;
reg RunSubbandRealtimeTopCoreQ610_stream_stream_ap_uint_const_int_bool_stream_la_1_ce0;
reg[11:0] RunSubbandRealtimeTopCoreQ610_stream_stream_ap_uint_const_int_bool_stream_la_1_address1;
reg RunSubbandRealtimeTopCoreQ610_stream_stream_ap_uint_const_int_bool_stream_la_1_ce1;
reg[11:0] RunSubbandRealtimeTopCoreQ610_stream_stream_ap_uint_const_int_bool_stream_la_address0;
reg RunSubbandRealtimeTopCoreQ610_stream_stream_ap_uint_const_int_bool_stream_la_ce0;
reg[11:0] RunSubbandRealtimeTopCoreQ610_stream_stream_ap_uint_const_int_bool_stream_la_address1;
reg RunSubbandRealtimeTopCoreQ610_stream_stream_ap_uint_const_int_bool_stream_la_ce1;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2_subdone;
reg   [0:0] icmp_ln4474_reg_4256;
reg    ap_condition_exit_pp0_iter0_stage2;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_pp0_stage3_subdone;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln4474_fu_2386_p2;
wire   [6:0] lshr_ln_fu_2392_p4;
reg   [6:0] lshr_ln_reg_4260;
wire   [15:0] rhs_fu_2428_p31;
reg  signed [15:0] rhs_reg_4280;
wire   [15:0] rhs_138_fu_2492_p31;
reg  signed [15:0] rhs_138_reg_4285;
wire   [15:0] rhs_139_fu_2588_p31;
reg  signed [15:0] rhs_139_reg_4300;
wire   [15:0] rhs_140_fu_2652_p31;
reg  signed [15:0] rhs_140_reg_4305;
wire   [15:0] rhs_141_fu_2716_p31;
reg  signed [15:0] rhs_141_reg_4310;
wire   [15:0] rhs_142_fu_2780_p31;
reg  signed [15:0] rhs_142_reg_4315;
wire   [15:0] rhs_143_fu_2844_p31;
reg  signed [15:0] rhs_143_reg_4320;
wire   [15:0] rhs_144_fu_2908_p31;
reg  signed [15:0] rhs_144_reg_4325;
wire   [15:0] rhs_145_fu_2972_p31;
reg  signed [15:0] rhs_145_reg_4330;
wire   [15:0] rhs_146_fu_3036_p31;
reg  signed [15:0] rhs_146_reg_4335;
wire   [15:0] rhs_147_fu_3100_p31;
reg  signed [15:0] rhs_147_reg_4340;
wire   [15:0] rhs_148_fu_3164_p31;
reg  signed [15:0] rhs_148_reg_4345;
wire   [15:0] rhs_149_fu_3228_p31;
reg  signed [15:0] rhs_149_reg_4350;
wire   [15:0] rhs_150_fu_3292_p31;
reg  signed [15:0] rhs_150_reg_4355;
wire   [15:0] rhs_151_fu_3356_p31;
reg  signed [15:0] rhs_151_reg_4360;
wire   [15:0] rhs_152_fu_3420_p31;
reg  signed [15:0] rhs_152_reg_4365;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_11001;
wire    ap_block_pp0_stage2_11001;
wire    ap_block_pp0_stage3_11001;
reg    ap_enable_reg_pp0_iter0_reg;
wire   [31:0] zext_ln4480_1_fu_2412_p1;
wire    ap_block_pp0_stage0;
wire   [31:0] zext_ln4480_2_fu_2423_p1;
wire   [31:0] zext_ln4480_4_fu_2572_p1;
wire   [31:0] zext_ln4480_5_fu_2583_p1;
wire   [31:0] zext_ln4480_7_fu_3537_p1;
wire    ap_block_pp0_stage1;
wire   [31:0] zext_ln4480_8_fu_3547_p1;
wire   [31:0] zext_ln4480_10_fu_3566_p1;
wire   [31:0] zext_ln4480_11_fu_3576_p1;
wire   [31:0] zext_ln4480_13_fu_3623_p1;
wire    ap_block_pp0_stage2;
wire   [31:0] zext_ln4480_14_fu_3633_p1;
wire   [31:0] zext_ln4480_16_fu_3652_p1;
wire   [31:0] zext_ln4480_17_fu_3662_p1;
wire   [31:0] zext_ln4480_19_fu_3721_p1;
wire    ap_block_pp0_stage3;
wire   [31:0] zext_ln4480_20_fu_3731_p1;
wire   [31:0] zext_ln4480_22_fu_3750_p1;
wire   [31:0] zext_ln4480_23_fu_3760_p1;
reg  signed [34:0] empty_fu_616;
wire  signed [34:0] grp_fu_3957_p3;
wire    ap_loop_init;
reg  signed [34:0] empty_629_fu_620;
wire  signed [34:0] grp_fu_3966_p3;
reg  signed [34:0] empty_630_fu_624;
wire  signed [34:0] grp_fu_3975_p3;
reg  signed [34:0] empty_631_fu_628;
wire  signed [34:0] grp_fu_3984_p3;
reg  signed [34:0] empty_632_fu_632;
wire  signed [34:0] grp_fu_3993_p3;
reg  signed [34:0] empty_633_fu_636;
wire  signed [34:0] grp_fu_4002_p3;
reg  signed [34:0] empty_634_fu_640;
wire  signed [34:0] grp_fu_4011_p3;
reg  signed [34:0] empty_635_fu_644;
wire  signed [34:0] grp_fu_4020_p3;
reg  signed [34:0] empty_636_fu_648;
wire  signed [34:0] grp_fu_4029_p3;
reg  signed [34:0] empty_637_fu_652;
wire  signed [34:0] grp_fu_4038_p3;
reg  signed [34:0] empty_638_fu_656;
wire  signed [34:0] grp_fu_4047_p3;
reg  signed [34:0] empty_639_fu_660;
wire  signed [34:0] grp_fu_4056_p3;
reg  signed [34:0] empty_640_fu_664;
wire  signed [34:0] grp_fu_4065_p3;
reg  signed [34:0] empty_641_fu_668;
wire  signed [34:0] grp_fu_4074_p3;
reg  signed [34:0] empty_642_fu_672;
wire  signed [34:0] grp_fu_4083_p3;
reg  signed [34:0] empty_643_fu_676;
wire  signed [34:0] grp_fu_4092_p3;
reg   [7:0] hidden_index_fu_680;
wire   [7:0] add_ln4474_fu_3484_p2;
reg   [7:0] ap_sig_allocacmp_hidden_base;
wire    ap_block_pp0_stage2_01001;
wire   [11:0] zext_ln4480_fu_2402_p1;
wire   [11:0] add_ln4480_16_fu_2406_p2;
wire   [11:0] add_ln4480_17_fu_2417_p2;
wire   [15:0] rhs_fu_2428_p29;
wire   [15:0] rhs_138_fu_2492_p29;
wire   [6:0] or_ln4480_fu_2556_p2;
wire   [11:0] zext_ln4480_3_fu_2562_p1;
wire   [11:0] add_ln4480_18_fu_2566_p2;
wire   [11:0] add_ln4480_19_fu_2577_p2;
wire   [15:0] rhs_139_fu_2588_p29;
wire   [15:0] rhs_140_fu_2652_p29;
wire   [15:0] rhs_141_fu_2716_p29;
wire   [15:0] rhs_142_fu_2780_p29;
wire   [15:0] rhs_143_fu_2844_p29;
wire   [15:0] rhs_144_fu_2908_p29;
wire   [15:0] rhs_145_fu_2972_p29;
wire   [15:0] rhs_146_fu_3036_p29;
wire   [15:0] rhs_147_fu_3100_p29;
wire   [15:0] rhs_148_fu_3164_p29;
wire   [15:0] rhs_149_fu_3228_p29;
wire   [15:0] rhs_150_fu_3292_p29;
wire   [15:0] rhs_151_fu_3356_p29;
wire   [15:0] rhs_152_fu_3420_p29;
wire   [6:0] or_ln4480_1_fu_3523_p2;
wire   [11:0] zext_ln4480_6_fu_3528_p1;
wire   [11:0] add_ln4480_20_fu_3532_p2;
wire   [11:0] add_ln4480_21_fu_3542_p2;
wire   [6:0] or_ln4480_2_fu_3552_p2;
wire   [11:0] zext_ln4480_9_fu_3557_p1;
wire   [11:0] add_ln4480_22_fu_3561_p2;
wire   [11:0] add_ln4480_23_fu_3571_p2;
wire   [6:0] or_ln4480_3_fu_3609_p2;
wire   [11:0] zext_ln4480_12_fu_3614_p1;
wire   [11:0] add_ln4480_24_fu_3618_p2;
wire   [11:0] add_ln4480_25_fu_3628_p2;
wire   [6:0] or_ln4480_4_fu_3638_p2;
wire   [11:0] zext_ln4480_15_fu_3643_p1;
wire   [11:0] add_ln4480_26_fu_3647_p2;
wire   [11:0] add_ln4480_27_fu_3657_p2;
wire   [6:0] or_ln4480_5_fu_3707_p2;
wire   [11:0] zext_ln4480_18_fu_3712_p1;
wire   [11:0] add_ln4480_28_fu_3716_p2;
wire   [11:0] add_ln4480_29_fu_3726_p2;
wire   [6:0] or_ln4480_6_fu_3736_p2;
wire   [11:0] zext_ln4480_21_fu_3741_p1;
wire   [11:0] add_ln4480_30_fu_3745_p2;
wire   [11:0] add_ln4480_31_fu_3755_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [3:0] ap_NS_fsm;
wire    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0_1to1;
wire    ap_block_pp0_stage1_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [7:0] rhs_fu_2428_p1;
wire   [7:0] rhs_fu_2428_p3;
wire   [7:0] rhs_fu_2428_p5;
wire   [7:0] rhs_fu_2428_p7;
wire   [7:0] rhs_fu_2428_p9;
wire   [7:0] rhs_fu_2428_p11;
wire   [7:0] rhs_fu_2428_p13;
wire   [7:0] rhs_fu_2428_p15;
wire  signed [7:0] rhs_fu_2428_p17;
wire  signed [7:0] rhs_fu_2428_p19;
wire  signed [7:0] rhs_fu_2428_p21;
wire  signed [7:0] rhs_fu_2428_p23;
wire  signed [7:0] rhs_fu_2428_p25;
wire  signed [7:0] rhs_fu_2428_p27;
wire   [7:0] rhs_138_fu_2492_p1;
wire   [7:0] rhs_138_fu_2492_p3;
wire   [7:0] rhs_138_fu_2492_p5;
wire   [7:0] rhs_138_fu_2492_p7;
wire   [7:0] rhs_138_fu_2492_p9;
wire   [7:0] rhs_138_fu_2492_p11;
wire   [7:0] rhs_138_fu_2492_p13;
wire   [7:0] rhs_138_fu_2492_p15;
wire  signed [7:0] rhs_138_fu_2492_p17;
wire  signed [7:0] rhs_138_fu_2492_p19;
wire  signed [7:0] rhs_138_fu_2492_p21;
wire  signed [7:0] rhs_138_fu_2492_p23;
wire  signed [7:0] rhs_138_fu_2492_p25;
wire  signed [7:0] rhs_138_fu_2492_p27;
wire   [7:0] rhs_139_fu_2588_p1;
wire   [7:0] rhs_139_fu_2588_p3;
wire   [7:0] rhs_139_fu_2588_p5;
wire   [7:0] rhs_139_fu_2588_p7;
wire   [7:0] rhs_139_fu_2588_p9;
wire   [7:0] rhs_139_fu_2588_p11;
wire   [7:0] rhs_139_fu_2588_p13;
wire   [7:0] rhs_139_fu_2588_p15;
wire  signed [7:0] rhs_139_fu_2588_p17;
wire  signed [7:0] rhs_139_fu_2588_p19;
wire  signed [7:0] rhs_139_fu_2588_p21;
wire  signed [7:0] rhs_139_fu_2588_p23;
wire  signed [7:0] rhs_139_fu_2588_p25;
wire  signed [7:0] rhs_139_fu_2588_p27;
wire   [7:0] rhs_140_fu_2652_p1;
wire   [7:0] rhs_140_fu_2652_p3;
wire   [7:0] rhs_140_fu_2652_p5;
wire   [7:0] rhs_140_fu_2652_p7;
wire   [7:0] rhs_140_fu_2652_p9;
wire   [7:0] rhs_140_fu_2652_p11;
wire   [7:0] rhs_140_fu_2652_p13;
wire   [7:0] rhs_140_fu_2652_p15;
wire  signed [7:0] rhs_140_fu_2652_p17;
wire  signed [7:0] rhs_140_fu_2652_p19;
wire  signed [7:0] rhs_140_fu_2652_p21;
wire  signed [7:0] rhs_140_fu_2652_p23;
wire  signed [7:0] rhs_140_fu_2652_p25;
wire  signed [7:0] rhs_140_fu_2652_p27;
wire   [7:0] rhs_141_fu_2716_p1;
wire   [7:0] rhs_141_fu_2716_p3;
wire   [7:0] rhs_141_fu_2716_p5;
wire   [7:0] rhs_141_fu_2716_p7;
wire   [7:0] rhs_141_fu_2716_p9;
wire   [7:0] rhs_141_fu_2716_p11;
wire   [7:0] rhs_141_fu_2716_p13;
wire   [7:0] rhs_141_fu_2716_p15;
wire  signed [7:0] rhs_141_fu_2716_p17;
wire  signed [7:0] rhs_141_fu_2716_p19;
wire  signed [7:0] rhs_141_fu_2716_p21;
wire  signed [7:0] rhs_141_fu_2716_p23;
wire  signed [7:0] rhs_141_fu_2716_p25;
wire  signed [7:0] rhs_141_fu_2716_p27;
wire   [7:0] rhs_142_fu_2780_p1;
wire   [7:0] rhs_142_fu_2780_p3;
wire   [7:0] rhs_142_fu_2780_p5;
wire   [7:0] rhs_142_fu_2780_p7;
wire   [7:0] rhs_142_fu_2780_p9;
wire   [7:0] rhs_142_fu_2780_p11;
wire   [7:0] rhs_142_fu_2780_p13;
wire   [7:0] rhs_142_fu_2780_p15;
wire  signed [7:0] rhs_142_fu_2780_p17;
wire  signed [7:0] rhs_142_fu_2780_p19;
wire  signed [7:0] rhs_142_fu_2780_p21;
wire  signed [7:0] rhs_142_fu_2780_p23;
wire  signed [7:0] rhs_142_fu_2780_p25;
wire  signed [7:0] rhs_142_fu_2780_p27;
wire   [7:0] rhs_143_fu_2844_p1;
wire   [7:0] rhs_143_fu_2844_p3;
wire   [7:0] rhs_143_fu_2844_p5;
wire   [7:0] rhs_143_fu_2844_p7;
wire   [7:0] rhs_143_fu_2844_p9;
wire   [7:0] rhs_143_fu_2844_p11;
wire   [7:0] rhs_143_fu_2844_p13;
wire   [7:0] rhs_143_fu_2844_p15;
wire  signed [7:0] rhs_143_fu_2844_p17;
wire  signed [7:0] rhs_143_fu_2844_p19;
wire  signed [7:0] rhs_143_fu_2844_p21;
wire  signed [7:0] rhs_143_fu_2844_p23;
wire  signed [7:0] rhs_143_fu_2844_p25;
wire  signed [7:0] rhs_143_fu_2844_p27;
wire   [7:0] rhs_144_fu_2908_p1;
wire   [7:0] rhs_144_fu_2908_p3;
wire   [7:0] rhs_144_fu_2908_p5;
wire   [7:0] rhs_144_fu_2908_p7;
wire   [7:0] rhs_144_fu_2908_p9;
wire   [7:0] rhs_144_fu_2908_p11;
wire   [7:0] rhs_144_fu_2908_p13;
wire   [7:0] rhs_144_fu_2908_p15;
wire  signed [7:0] rhs_144_fu_2908_p17;
wire  signed [7:0] rhs_144_fu_2908_p19;
wire  signed [7:0] rhs_144_fu_2908_p21;
wire  signed [7:0] rhs_144_fu_2908_p23;
wire  signed [7:0] rhs_144_fu_2908_p25;
wire  signed [7:0] rhs_144_fu_2908_p27;
wire   [7:0] rhs_145_fu_2972_p1;
wire   [7:0] rhs_145_fu_2972_p3;
wire   [7:0] rhs_145_fu_2972_p5;
wire   [7:0] rhs_145_fu_2972_p7;
wire   [7:0] rhs_145_fu_2972_p9;
wire   [7:0] rhs_145_fu_2972_p11;
wire   [7:0] rhs_145_fu_2972_p13;
wire   [7:0] rhs_145_fu_2972_p15;
wire  signed [7:0] rhs_145_fu_2972_p17;
wire  signed [7:0] rhs_145_fu_2972_p19;
wire  signed [7:0] rhs_145_fu_2972_p21;
wire  signed [7:0] rhs_145_fu_2972_p23;
wire  signed [7:0] rhs_145_fu_2972_p25;
wire  signed [7:0] rhs_145_fu_2972_p27;
wire   [7:0] rhs_146_fu_3036_p1;
wire   [7:0] rhs_146_fu_3036_p3;
wire   [7:0] rhs_146_fu_3036_p5;
wire   [7:0] rhs_146_fu_3036_p7;
wire   [7:0] rhs_146_fu_3036_p9;
wire   [7:0] rhs_146_fu_3036_p11;
wire   [7:0] rhs_146_fu_3036_p13;
wire   [7:0] rhs_146_fu_3036_p15;
wire  signed [7:0] rhs_146_fu_3036_p17;
wire  signed [7:0] rhs_146_fu_3036_p19;
wire  signed [7:0] rhs_146_fu_3036_p21;
wire  signed [7:0] rhs_146_fu_3036_p23;
wire  signed [7:0] rhs_146_fu_3036_p25;
wire  signed [7:0] rhs_146_fu_3036_p27;
wire   [7:0] rhs_147_fu_3100_p1;
wire   [7:0] rhs_147_fu_3100_p3;
wire   [7:0] rhs_147_fu_3100_p5;
wire   [7:0] rhs_147_fu_3100_p7;
wire   [7:0] rhs_147_fu_3100_p9;
wire   [7:0] rhs_147_fu_3100_p11;
wire   [7:0] rhs_147_fu_3100_p13;
wire   [7:0] rhs_147_fu_3100_p15;
wire  signed [7:0] rhs_147_fu_3100_p17;
wire  signed [7:0] rhs_147_fu_3100_p19;
wire  signed [7:0] rhs_147_fu_3100_p21;
wire  signed [7:0] rhs_147_fu_3100_p23;
wire  signed [7:0] rhs_147_fu_3100_p25;
wire  signed [7:0] rhs_147_fu_3100_p27;
wire   [7:0] rhs_148_fu_3164_p1;
wire   [7:0] rhs_148_fu_3164_p3;
wire   [7:0] rhs_148_fu_3164_p5;
wire   [7:0] rhs_148_fu_3164_p7;
wire   [7:0] rhs_148_fu_3164_p9;
wire   [7:0] rhs_148_fu_3164_p11;
wire   [7:0] rhs_148_fu_3164_p13;
wire   [7:0] rhs_148_fu_3164_p15;
wire  signed [7:0] rhs_148_fu_3164_p17;
wire  signed [7:0] rhs_148_fu_3164_p19;
wire  signed [7:0] rhs_148_fu_3164_p21;
wire  signed [7:0] rhs_148_fu_3164_p23;
wire  signed [7:0] rhs_148_fu_3164_p25;
wire  signed [7:0] rhs_148_fu_3164_p27;
wire   [7:0] rhs_149_fu_3228_p1;
wire   [7:0] rhs_149_fu_3228_p3;
wire   [7:0] rhs_149_fu_3228_p5;
wire   [7:0] rhs_149_fu_3228_p7;
wire   [7:0] rhs_149_fu_3228_p9;
wire   [7:0] rhs_149_fu_3228_p11;
wire   [7:0] rhs_149_fu_3228_p13;
wire   [7:0] rhs_149_fu_3228_p15;
wire  signed [7:0] rhs_149_fu_3228_p17;
wire  signed [7:0] rhs_149_fu_3228_p19;
wire  signed [7:0] rhs_149_fu_3228_p21;
wire  signed [7:0] rhs_149_fu_3228_p23;
wire  signed [7:0] rhs_149_fu_3228_p25;
wire  signed [7:0] rhs_149_fu_3228_p27;
wire   [7:0] rhs_150_fu_3292_p1;
wire   [7:0] rhs_150_fu_3292_p3;
wire   [7:0] rhs_150_fu_3292_p5;
wire   [7:0] rhs_150_fu_3292_p7;
wire   [7:0] rhs_150_fu_3292_p9;
wire   [7:0] rhs_150_fu_3292_p11;
wire   [7:0] rhs_150_fu_3292_p13;
wire   [7:0] rhs_150_fu_3292_p15;
wire  signed [7:0] rhs_150_fu_3292_p17;
wire  signed [7:0] rhs_150_fu_3292_p19;
wire  signed [7:0] rhs_150_fu_3292_p21;
wire  signed [7:0] rhs_150_fu_3292_p23;
wire  signed [7:0] rhs_150_fu_3292_p25;
wire  signed [7:0] rhs_150_fu_3292_p27;
wire   [7:0] rhs_151_fu_3356_p1;
wire   [7:0] rhs_151_fu_3356_p3;
wire   [7:0] rhs_151_fu_3356_p5;
wire   [7:0] rhs_151_fu_3356_p7;
wire   [7:0] rhs_151_fu_3356_p9;
wire   [7:0] rhs_151_fu_3356_p11;
wire   [7:0] rhs_151_fu_3356_p13;
wire   [7:0] rhs_151_fu_3356_p15;
wire  signed [7:0] rhs_151_fu_3356_p17;
wire  signed [7:0] rhs_151_fu_3356_p19;
wire  signed [7:0] rhs_151_fu_3356_p21;
wire  signed [7:0] rhs_151_fu_3356_p23;
wire  signed [7:0] rhs_151_fu_3356_p25;
wire  signed [7:0] rhs_151_fu_3356_p27;
wire   [7:0] rhs_152_fu_3420_p1;
wire   [7:0] rhs_152_fu_3420_p3;
wire   [7:0] rhs_152_fu_3420_p5;
wire   [7:0] rhs_152_fu_3420_p7;
wire   [7:0] rhs_152_fu_3420_p9;
wire   [7:0] rhs_152_fu_3420_p11;
wire   [7:0] rhs_152_fu_3420_p13;
wire   [7:0] rhs_152_fu_3420_p15;
wire  signed [7:0] rhs_152_fu_3420_p17;
wire  signed [7:0] rhs_152_fu_3420_p19;
wire  signed [7:0] rhs_152_fu_3420_p21;
wire  signed [7:0] rhs_152_fu_3420_p23;
wire  signed [7:0] rhs_152_fu_3420_p25;
wire  signed [7:0] rhs_152_fu_3420_p27;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 empty_fu_616 = 35'd0;
#0 empty_629_fu_620 = 35'd0;
#0 empty_630_fu_624 = 35'd0;
#0 empty_631_fu_628 = 35'd0;
#0 empty_632_fu_632 = 35'd0;
#0 empty_633_fu_636 = 35'd0;
#0 empty_634_fu_640 = 35'd0;
#0 empty_635_fu_644 = 35'd0;
#0 empty_636_fu_648 = 35'd0;
#0 empty_637_fu_652 = 35'd0;
#0 empty_638_fu_656 = 35'd0;
#0 empty_639_fu_660 = 35'd0;
#0 empty_640_fu_664 = 35'd0;
#0 empty_641_fu_668 = 35'd0;
#0 empty_642_fu_672 = 35'd0;
#0 empty_643_fu_676 = 35'd0;
#0 hidden_index_fu_680 = 8'd0;
#0 ap_done_reg = 1'b0;
end

SubbandRealtimeTopQ610Ip_sparsemux_29_8_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 8'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 8'h10 ),
    .din1_WIDTH( 16 ),
    .CASE2( 8'h20 ),
    .din2_WIDTH( 16 ),
    .CASE3( 8'h30 ),
    .din3_WIDTH( 16 ),
    .CASE4( 8'h40 ),
    .din4_WIDTH( 16 ),
    .CASE5( 8'h50 ),
    .din5_WIDTH( 16 ),
    .CASE6( 8'h60 ),
    .din6_WIDTH( 16 ),
    .CASE7( 8'h70 ),
    .din7_WIDTH( 16 ),
    .CASE8( 8'h80 ),
    .din8_WIDTH( 16 ),
    .CASE9( 8'h90 ),
    .din9_WIDTH( 16 ),
    .CASE10( 8'hA0 ),
    .din10_WIDTH( 16 ),
    .CASE11( 8'hB0 ),
    .din11_WIDTH( 16 ),
    .CASE12( 8'hC0 ),
    .din12_WIDTH( 16 ),
    .CASE13( 8'hD0 ),
    .din13_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
sparsemux_29_8_16_1_1_U5123(
    .din0(proj_row_0_val),
    .din1(proj_row_16_val),
    .din2(proj_row_32_val),
    .din3(proj_row_48_val),
    .din4(proj_row_64_val),
    .din5(proj_row_80_val),
    .din6(proj_row_96_val),
    .din7(proj_row_112_val),
    .din8(proj_row_128_val),
    .din9(proj_row_144_val),
    .din10(proj_row_160_val),
    .din11(proj_row_176_val),
    .din12(proj_row_192_val),
    .din13(proj_row_208_val),
    .def(rhs_fu_2428_p29),
    .sel(ap_sig_allocacmp_hidden_base),
    .dout(rhs_fu_2428_p31)
);

SubbandRealtimeTopQ610Ip_sparsemux_29_8_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 8'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 8'h10 ),
    .din1_WIDTH( 16 ),
    .CASE2( 8'h20 ),
    .din2_WIDTH( 16 ),
    .CASE3( 8'h30 ),
    .din3_WIDTH( 16 ),
    .CASE4( 8'h40 ),
    .din4_WIDTH( 16 ),
    .CASE5( 8'h50 ),
    .din5_WIDTH( 16 ),
    .CASE6( 8'h60 ),
    .din6_WIDTH( 16 ),
    .CASE7( 8'h70 ),
    .din7_WIDTH( 16 ),
    .CASE8( 8'h80 ),
    .din8_WIDTH( 16 ),
    .CASE9( 8'h90 ),
    .din9_WIDTH( 16 ),
    .CASE10( 8'hA0 ),
    .din10_WIDTH( 16 ),
    .CASE11( 8'hB0 ),
    .din11_WIDTH( 16 ),
    .CASE12( 8'hC0 ),
    .din12_WIDTH( 16 ),
    .CASE13( 8'hD0 ),
    .din13_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
sparsemux_29_8_16_1_1_U5124(
    .din0(proj_row_1_val),
    .din1(proj_row_17_val),
    .din2(proj_row_33_val),
    .din3(proj_row_49_val),
    .din4(proj_row_65_val),
    .din5(proj_row_81_val),
    .din6(proj_row_97_val),
    .din7(proj_row_113_val),
    .din8(proj_row_129_val),
    .din9(proj_row_145_val),
    .din10(proj_row_161_val),
    .din11(proj_row_177_val),
    .din12(proj_row_193_val),
    .din13(proj_row_209_val),
    .def(rhs_138_fu_2492_p29),
    .sel(ap_sig_allocacmp_hidden_base),
    .dout(rhs_138_fu_2492_p31)
);

SubbandRealtimeTopQ610Ip_sparsemux_29_8_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 8'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 8'h10 ),
    .din1_WIDTH( 16 ),
    .CASE2( 8'h20 ),
    .din2_WIDTH( 16 ),
    .CASE3( 8'h30 ),
    .din3_WIDTH( 16 ),
    .CASE4( 8'h40 ),
    .din4_WIDTH( 16 ),
    .CASE5( 8'h50 ),
    .din5_WIDTH( 16 ),
    .CASE6( 8'h60 ),
    .din6_WIDTH( 16 ),
    .CASE7( 8'h70 ),
    .din7_WIDTH( 16 ),
    .CASE8( 8'h80 ),
    .din8_WIDTH( 16 ),
    .CASE9( 8'h90 ),
    .din9_WIDTH( 16 ),
    .CASE10( 8'hA0 ),
    .din10_WIDTH( 16 ),
    .CASE11( 8'hB0 ),
    .din11_WIDTH( 16 ),
    .CASE12( 8'hC0 ),
    .din12_WIDTH( 16 ),
    .CASE13( 8'hD0 ),
    .din13_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
sparsemux_29_8_16_1_1_U5125(
    .din0(proj_row_2_val),
    .din1(proj_row_18_val),
    .din2(proj_row_34_val),
    .din3(proj_row_50_val),
    .din4(proj_row_66_val),
    .din5(proj_row_82_val),
    .din6(proj_row_98_val),
    .din7(proj_row_114_val),
    .din8(proj_row_130_val),
    .din9(proj_row_146_val),
    .din10(proj_row_162_val),
    .din11(proj_row_178_val),
    .din12(proj_row_194_val),
    .din13(proj_row_210_val),
    .def(rhs_139_fu_2588_p29),
    .sel(ap_sig_allocacmp_hidden_base),
    .dout(rhs_139_fu_2588_p31)
);

SubbandRealtimeTopQ610Ip_sparsemux_29_8_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 8'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 8'h10 ),
    .din1_WIDTH( 16 ),
    .CASE2( 8'h20 ),
    .din2_WIDTH( 16 ),
    .CASE3( 8'h30 ),
    .din3_WIDTH( 16 ),
    .CASE4( 8'h40 ),
    .din4_WIDTH( 16 ),
    .CASE5( 8'h50 ),
    .din5_WIDTH( 16 ),
    .CASE6( 8'h60 ),
    .din6_WIDTH( 16 ),
    .CASE7( 8'h70 ),
    .din7_WIDTH( 16 ),
    .CASE8( 8'h80 ),
    .din8_WIDTH( 16 ),
    .CASE9( 8'h90 ),
    .din9_WIDTH( 16 ),
    .CASE10( 8'hA0 ),
    .din10_WIDTH( 16 ),
    .CASE11( 8'hB0 ),
    .din11_WIDTH( 16 ),
    .CASE12( 8'hC0 ),
    .din12_WIDTH( 16 ),
    .CASE13( 8'hD0 ),
    .din13_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
sparsemux_29_8_16_1_1_U5126(
    .din0(proj_row_3_val),
    .din1(proj_row_19_val),
    .din2(proj_row_35_val),
    .din3(proj_row_51_val),
    .din4(proj_row_67_val),
    .din5(proj_row_83_val),
    .din6(proj_row_99_val),
    .din7(proj_row_115_val),
    .din8(proj_row_131_val),
    .din9(proj_row_147_val),
    .din10(proj_row_163_val),
    .din11(proj_row_179_val),
    .din12(proj_row_195_val),
    .din13(proj_row_211_val),
    .def(rhs_140_fu_2652_p29),
    .sel(ap_sig_allocacmp_hidden_base),
    .dout(rhs_140_fu_2652_p31)
);

SubbandRealtimeTopQ610Ip_sparsemux_29_8_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 8'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 8'h10 ),
    .din1_WIDTH( 16 ),
    .CASE2( 8'h20 ),
    .din2_WIDTH( 16 ),
    .CASE3( 8'h30 ),
    .din3_WIDTH( 16 ),
    .CASE4( 8'h40 ),
    .din4_WIDTH( 16 ),
    .CASE5( 8'h50 ),
    .din5_WIDTH( 16 ),
    .CASE6( 8'h60 ),
    .din6_WIDTH( 16 ),
    .CASE7( 8'h70 ),
    .din7_WIDTH( 16 ),
    .CASE8( 8'h80 ),
    .din8_WIDTH( 16 ),
    .CASE9( 8'h90 ),
    .din9_WIDTH( 16 ),
    .CASE10( 8'hA0 ),
    .din10_WIDTH( 16 ),
    .CASE11( 8'hB0 ),
    .din11_WIDTH( 16 ),
    .CASE12( 8'hC0 ),
    .din12_WIDTH( 16 ),
    .CASE13( 8'hD0 ),
    .din13_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
sparsemux_29_8_16_1_1_U5127(
    .din0(proj_row_4_val),
    .din1(proj_row_20_val),
    .din2(proj_row_36_val),
    .din3(proj_row_52_val),
    .din4(proj_row_68_val),
    .din5(proj_row_84_val),
    .din6(proj_row_100_val),
    .din7(proj_row_116_val),
    .din8(proj_row_132_val),
    .din9(proj_row_148_val),
    .din10(proj_row_164_val),
    .din11(proj_row_180_val),
    .din12(proj_row_196_val),
    .din13(proj_row_212_val),
    .def(rhs_141_fu_2716_p29),
    .sel(ap_sig_allocacmp_hidden_base),
    .dout(rhs_141_fu_2716_p31)
);

SubbandRealtimeTopQ610Ip_sparsemux_29_8_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 8'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 8'h10 ),
    .din1_WIDTH( 16 ),
    .CASE2( 8'h20 ),
    .din2_WIDTH( 16 ),
    .CASE3( 8'h30 ),
    .din3_WIDTH( 16 ),
    .CASE4( 8'h40 ),
    .din4_WIDTH( 16 ),
    .CASE5( 8'h50 ),
    .din5_WIDTH( 16 ),
    .CASE6( 8'h60 ),
    .din6_WIDTH( 16 ),
    .CASE7( 8'h70 ),
    .din7_WIDTH( 16 ),
    .CASE8( 8'h80 ),
    .din8_WIDTH( 16 ),
    .CASE9( 8'h90 ),
    .din9_WIDTH( 16 ),
    .CASE10( 8'hA0 ),
    .din10_WIDTH( 16 ),
    .CASE11( 8'hB0 ),
    .din11_WIDTH( 16 ),
    .CASE12( 8'hC0 ),
    .din12_WIDTH( 16 ),
    .CASE13( 8'hD0 ),
    .din13_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
sparsemux_29_8_16_1_1_U5128(
    .din0(proj_row_5_val),
    .din1(proj_row_21_val),
    .din2(proj_row_37_val),
    .din3(proj_row_53_val),
    .din4(proj_row_69_val),
    .din5(proj_row_85_val),
    .din6(proj_row_101_val),
    .din7(proj_row_117_val),
    .din8(proj_row_133_val),
    .din9(proj_row_149_val),
    .din10(proj_row_165_val),
    .din11(proj_row_181_val),
    .din12(proj_row_197_val),
    .din13(proj_row_213_val),
    .def(rhs_142_fu_2780_p29),
    .sel(ap_sig_allocacmp_hidden_base),
    .dout(rhs_142_fu_2780_p31)
);

SubbandRealtimeTopQ610Ip_sparsemux_29_8_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 8'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 8'h10 ),
    .din1_WIDTH( 16 ),
    .CASE2( 8'h20 ),
    .din2_WIDTH( 16 ),
    .CASE3( 8'h30 ),
    .din3_WIDTH( 16 ),
    .CASE4( 8'h40 ),
    .din4_WIDTH( 16 ),
    .CASE5( 8'h50 ),
    .din5_WIDTH( 16 ),
    .CASE6( 8'h60 ),
    .din6_WIDTH( 16 ),
    .CASE7( 8'h70 ),
    .din7_WIDTH( 16 ),
    .CASE8( 8'h80 ),
    .din8_WIDTH( 16 ),
    .CASE9( 8'h90 ),
    .din9_WIDTH( 16 ),
    .CASE10( 8'hA0 ),
    .din10_WIDTH( 16 ),
    .CASE11( 8'hB0 ),
    .din11_WIDTH( 16 ),
    .CASE12( 8'hC0 ),
    .din12_WIDTH( 16 ),
    .CASE13( 8'hD0 ),
    .din13_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
sparsemux_29_8_16_1_1_U5129(
    .din0(proj_row_6_val),
    .din1(proj_row_22_val),
    .din2(proj_row_38_val),
    .din3(proj_row_54_val),
    .din4(proj_row_70_val),
    .din5(proj_row_86_val),
    .din6(proj_row_102_val),
    .din7(proj_row_118_val),
    .din8(proj_row_134_val),
    .din9(proj_row_150_val),
    .din10(proj_row_166_val),
    .din11(proj_row_182_val),
    .din12(proj_row_198_val),
    .din13(proj_row_214_val),
    .def(rhs_143_fu_2844_p29),
    .sel(ap_sig_allocacmp_hidden_base),
    .dout(rhs_143_fu_2844_p31)
);

SubbandRealtimeTopQ610Ip_sparsemux_29_8_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 8'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 8'h10 ),
    .din1_WIDTH( 16 ),
    .CASE2( 8'h20 ),
    .din2_WIDTH( 16 ),
    .CASE3( 8'h30 ),
    .din3_WIDTH( 16 ),
    .CASE4( 8'h40 ),
    .din4_WIDTH( 16 ),
    .CASE5( 8'h50 ),
    .din5_WIDTH( 16 ),
    .CASE6( 8'h60 ),
    .din6_WIDTH( 16 ),
    .CASE7( 8'h70 ),
    .din7_WIDTH( 16 ),
    .CASE8( 8'h80 ),
    .din8_WIDTH( 16 ),
    .CASE9( 8'h90 ),
    .din9_WIDTH( 16 ),
    .CASE10( 8'hA0 ),
    .din10_WIDTH( 16 ),
    .CASE11( 8'hB0 ),
    .din11_WIDTH( 16 ),
    .CASE12( 8'hC0 ),
    .din12_WIDTH( 16 ),
    .CASE13( 8'hD0 ),
    .din13_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
sparsemux_29_8_16_1_1_U5130(
    .din0(proj_row_7_val),
    .din1(proj_row_23_val),
    .din2(proj_row_39_val),
    .din3(proj_row_55_val),
    .din4(proj_row_71_val),
    .din5(proj_row_87_val),
    .din6(proj_row_103_val),
    .din7(proj_row_119_val),
    .din8(proj_row_135_val),
    .din9(proj_row_151_val),
    .din10(proj_row_167_val),
    .din11(proj_row_183_val),
    .din12(proj_row_199_val),
    .din13(proj_row_215_val),
    .def(rhs_144_fu_2908_p29),
    .sel(ap_sig_allocacmp_hidden_base),
    .dout(rhs_144_fu_2908_p31)
);

SubbandRealtimeTopQ610Ip_sparsemux_29_8_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 8'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 8'h10 ),
    .din1_WIDTH( 16 ),
    .CASE2( 8'h20 ),
    .din2_WIDTH( 16 ),
    .CASE3( 8'h30 ),
    .din3_WIDTH( 16 ),
    .CASE4( 8'h40 ),
    .din4_WIDTH( 16 ),
    .CASE5( 8'h50 ),
    .din5_WIDTH( 16 ),
    .CASE6( 8'h60 ),
    .din6_WIDTH( 16 ),
    .CASE7( 8'h70 ),
    .din7_WIDTH( 16 ),
    .CASE8( 8'h80 ),
    .din8_WIDTH( 16 ),
    .CASE9( 8'h90 ),
    .din9_WIDTH( 16 ),
    .CASE10( 8'hA0 ),
    .din10_WIDTH( 16 ),
    .CASE11( 8'hB0 ),
    .din11_WIDTH( 16 ),
    .CASE12( 8'hC0 ),
    .din12_WIDTH( 16 ),
    .CASE13( 8'hD0 ),
    .din13_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
sparsemux_29_8_16_1_1_U5131(
    .din0(proj_row_8_val),
    .din1(proj_row_24_val),
    .din2(proj_row_40_val),
    .din3(proj_row_56_val),
    .din4(proj_row_72_val),
    .din5(proj_row_88_val),
    .din6(proj_row_104_val),
    .din7(proj_row_120_val),
    .din8(proj_row_136_val),
    .din9(proj_row_152_val),
    .din10(proj_row_168_val),
    .din11(proj_row_184_val),
    .din12(proj_row_200_val),
    .din13(proj_row_216_val),
    .def(rhs_145_fu_2972_p29),
    .sel(ap_sig_allocacmp_hidden_base),
    .dout(rhs_145_fu_2972_p31)
);

SubbandRealtimeTopQ610Ip_sparsemux_29_8_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 8'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 8'h10 ),
    .din1_WIDTH( 16 ),
    .CASE2( 8'h20 ),
    .din2_WIDTH( 16 ),
    .CASE3( 8'h30 ),
    .din3_WIDTH( 16 ),
    .CASE4( 8'h40 ),
    .din4_WIDTH( 16 ),
    .CASE5( 8'h50 ),
    .din5_WIDTH( 16 ),
    .CASE6( 8'h60 ),
    .din6_WIDTH( 16 ),
    .CASE7( 8'h70 ),
    .din7_WIDTH( 16 ),
    .CASE8( 8'h80 ),
    .din8_WIDTH( 16 ),
    .CASE9( 8'h90 ),
    .din9_WIDTH( 16 ),
    .CASE10( 8'hA0 ),
    .din10_WIDTH( 16 ),
    .CASE11( 8'hB0 ),
    .din11_WIDTH( 16 ),
    .CASE12( 8'hC0 ),
    .din12_WIDTH( 16 ),
    .CASE13( 8'hD0 ),
    .din13_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
sparsemux_29_8_16_1_1_U5132(
    .din0(proj_row_9_val),
    .din1(proj_row_25_val),
    .din2(proj_row_41_val),
    .din3(proj_row_57_val),
    .din4(proj_row_73_val),
    .din5(proj_row_89_val),
    .din6(proj_row_105_val),
    .din7(proj_row_121_val),
    .din8(proj_row_137_val),
    .din9(proj_row_153_val),
    .din10(proj_row_169_val),
    .din11(proj_row_185_val),
    .din12(proj_row_201_val),
    .din13(proj_row_217_val),
    .def(rhs_146_fu_3036_p29),
    .sel(ap_sig_allocacmp_hidden_base),
    .dout(rhs_146_fu_3036_p31)
);

SubbandRealtimeTopQ610Ip_sparsemux_29_8_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 8'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 8'h10 ),
    .din1_WIDTH( 16 ),
    .CASE2( 8'h20 ),
    .din2_WIDTH( 16 ),
    .CASE3( 8'h30 ),
    .din3_WIDTH( 16 ),
    .CASE4( 8'h40 ),
    .din4_WIDTH( 16 ),
    .CASE5( 8'h50 ),
    .din5_WIDTH( 16 ),
    .CASE6( 8'h60 ),
    .din6_WIDTH( 16 ),
    .CASE7( 8'h70 ),
    .din7_WIDTH( 16 ),
    .CASE8( 8'h80 ),
    .din8_WIDTH( 16 ),
    .CASE9( 8'h90 ),
    .din9_WIDTH( 16 ),
    .CASE10( 8'hA0 ),
    .din10_WIDTH( 16 ),
    .CASE11( 8'hB0 ),
    .din11_WIDTH( 16 ),
    .CASE12( 8'hC0 ),
    .din12_WIDTH( 16 ),
    .CASE13( 8'hD0 ),
    .din13_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
sparsemux_29_8_16_1_1_U5133(
    .din0(proj_row_10_val),
    .din1(proj_row_26_val),
    .din2(proj_row_42_val),
    .din3(proj_row_58_val),
    .din4(proj_row_74_val),
    .din5(proj_row_90_val),
    .din6(proj_row_106_val),
    .din7(proj_row_122_val),
    .din8(proj_row_138_val),
    .din9(proj_row_154_val),
    .din10(proj_row_170_val),
    .din11(proj_row_186_val),
    .din12(proj_row_202_val),
    .din13(proj_row_218_val),
    .def(rhs_147_fu_3100_p29),
    .sel(ap_sig_allocacmp_hidden_base),
    .dout(rhs_147_fu_3100_p31)
);

SubbandRealtimeTopQ610Ip_sparsemux_29_8_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 8'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 8'h10 ),
    .din1_WIDTH( 16 ),
    .CASE2( 8'h20 ),
    .din2_WIDTH( 16 ),
    .CASE3( 8'h30 ),
    .din3_WIDTH( 16 ),
    .CASE4( 8'h40 ),
    .din4_WIDTH( 16 ),
    .CASE5( 8'h50 ),
    .din5_WIDTH( 16 ),
    .CASE6( 8'h60 ),
    .din6_WIDTH( 16 ),
    .CASE7( 8'h70 ),
    .din7_WIDTH( 16 ),
    .CASE8( 8'h80 ),
    .din8_WIDTH( 16 ),
    .CASE9( 8'h90 ),
    .din9_WIDTH( 16 ),
    .CASE10( 8'hA0 ),
    .din10_WIDTH( 16 ),
    .CASE11( 8'hB0 ),
    .din11_WIDTH( 16 ),
    .CASE12( 8'hC0 ),
    .din12_WIDTH( 16 ),
    .CASE13( 8'hD0 ),
    .din13_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
sparsemux_29_8_16_1_1_U5134(
    .din0(proj_row_11_val),
    .din1(proj_row_27_val),
    .din2(proj_row_43_val),
    .din3(proj_row_59_val),
    .din4(proj_row_75_val),
    .din5(proj_row_91_val),
    .din6(proj_row_107_val),
    .din7(proj_row_123_val),
    .din8(proj_row_139_val),
    .din9(proj_row_155_val),
    .din10(proj_row_171_val),
    .din11(proj_row_187_val),
    .din12(proj_row_203_val),
    .din13(proj_row_219_val),
    .def(rhs_148_fu_3164_p29),
    .sel(ap_sig_allocacmp_hidden_base),
    .dout(rhs_148_fu_3164_p31)
);

SubbandRealtimeTopQ610Ip_sparsemux_29_8_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 8'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 8'h10 ),
    .din1_WIDTH( 16 ),
    .CASE2( 8'h20 ),
    .din2_WIDTH( 16 ),
    .CASE3( 8'h30 ),
    .din3_WIDTH( 16 ),
    .CASE4( 8'h40 ),
    .din4_WIDTH( 16 ),
    .CASE5( 8'h50 ),
    .din5_WIDTH( 16 ),
    .CASE6( 8'h60 ),
    .din6_WIDTH( 16 ),
    .CASE7( 8'h70 ),
    .din7_WIDTH( 16 ),
    .CASE8( 8'h80 ),
    .din8_WIDTH( 16 ),
    .CASE9( 8'h90 ),
    .din9_WIDTH( 16 ),
    .CASE10( 8'hA0 ),
    .din10_WIDTH( 16 ),
    .CASE11( 8'hB0 ),
    .din11_WIDTH( 16 ),
    .CASE12( 8'hC0 ),
    .din12_WIDTH( 16 ),
    .CASE13( 8'hD0 ),
    .din13_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
sparsemux_29_8_16_1_1_U5135(
    .din0(proj_row_12_val),
    .din1(proj_row_28_val),
    .din2(proj_row_44_val),
    .din3(proj_row_60_val),
    .din4(proj_row_76_val),
    .din5(proj_row_92_val),
    .din6(proj_row_108_val),
    .din7(proj_row_124_val),
    .din8(proj_row_140_val),
    .din9(proj_row_156_val),
    .din10(proj_row_172_val),
    .din11(proj_row_188_val),
    .din12(proj_row_204_val),
    .din13(proj_row_220_val),
    .def(rhs_149_fu_3228_p29),
    .sel(ap_sig_allocacmp_hidden_base),
    .dout(rhs_149_fu_3228_p31)
);

SubbandRealtimeTopQ610Ip_sparsemux_29_8_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 8'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 8'h10 ),
    .din1_WIDTH( 16 ),
    .CASE2( 8'h20 ),
    .din2_WIDTH( 16 ),
    .CASE3( 8'h30 ),
    .din3_WIDTH( 16 ),
    .CASE4( 8'h40 ),
    .din4_WIDTH( 16 ),
    .CASE5( 8'h50 ),
    .din5_WIDTH( 16 ),
    .CASE6( 8'h60 ),
    .din6_WIDTH( 16 ),
    .CASE7( 8'h70 ),
    .din7_WIDTH( 16 ),
    .CASE8( 8'h80 ),
    .din8_WIDTH( 16 ),
    .CASE9( 8'h90 ),
    .din9_WIDTH( 16 ),
    .CASE10( 8'hA0 ),
    .din10_WIDTH( 16 ),
    .CASE11( 8'hB0 ),
    .din11_WIDTH( 16 ),
    .CASE12( 8'hC0 ),
    .din12_WIDTH( 16 ),
    .CASE13( 8'hD0 ),
    .din13_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
sparsemux_29_8_16_1_1_U5136(
    .din0(proj_row_13_val),
    .din1(proj_row_29_val),
    .din2(proj_row_45_val),
    .din3(proj_row_61_val),
    .din4(proj_row_77_val),
    .din5(proj_row_93_val),
    .din6(proj_row_109_val),
    .din7(proj_row_125_val),
    .din8(proj_row_141_val),
    .din9(proj_row_157_val),
    .din10(proj_row_173_val),
    .din11(proj_row_189_val),
    .din12(proj_row_205_val),
    .din13(proj_row_221_val),
    .def(rhs_150_fu_3292_p29),
    .sel(ap_sig_allocacmp_hidden_base),
    .dout(rhs_150_fu_3292_p31)
);

SubbandRealtimeTopQ610Ip_sparsemux_29_8_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 8'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 8'h10 ),
    .din1_WIDTH( 16 ),
    .CASE2( 8'h20 ),
    .din2_WIDTH( 16 ),
    .CASE3( 8'h30 ),
    .din3_WIDTH( 16 ),
    .CASE4( 8'h40 ),
    .din4_WIDTH( 16 ),
    .CASE5( 8'h50 ),
    .din5_WIDTH( 16 ),
    .CASE6( 8'h60 ),
    .din6_WIDTH( 16 ),
    .CASE7( 8'h70 ),
    .din7_WIDTH( 16 ),
    .CASE8( 8'h80 ),
    .din8_WIDTH( 16 ),
    .CASE9( 8'h90 ),
    .din9_WIDTH( 16 ),
    .CASE10( 8'hA0 ),
    .din10_WIDTH( 16 ),
    .CASE11( 8'hB0 ),
    .din11_WIDTH( 16 ),
    .CASE12( 8'hC0 ),
    .din12_WIDTH( 16 ),
    .CASE13( 8'hD0 ),
    .din13_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
sparsemux_29_8_16_1_1_U5137(
    .din0(proj_row_14_val),
    .din1(proj_row_30_val),
    .din2(proj_row_46_val),
    .din3(proj_row_62_val),
    .din4(proj_row_78_val),
    .din5(proj_row_94_val),
    .din6(proj_row_110_val),
    .din7(proj_row_126_val),
    .din8(proj_row_142_val),
    .din9(proj_row_158_val),
    .din10(proj_row_174_val),
    .din11(proj_row_190_val),
    .din12(proj_row_206_val),
    .din13(proj_row_222_val),
    .def(rhs_151_fu_3356_p29),
    .sel(ap_sig_allocacmp_hidden_base),
    .dout(rhs_151_fu_3356_p31)
);

SubbandRealtimeTopQ610Ip_sparsemux_29_8_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 8'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 8'h10 ),
    .din1_WIDTH( 16 ),
    .CASE2( 8'h20 ),
    .din2_WIDTH( 16 ),
    .CASE3( 8'h30 ),
    .din3_WIDTH( 16 ),
    .CASE4( 8'h40 ),
    .din4_WIDTH( 16 ),
    .CASE5( 8'h50 ),
    .din5_WIDTH( 16 ),
    .CASE6( 8'h60 ),
    .din6_WIDTH( 16 ),
    .CASE7( 8'h70 ),
    .din7_WIDTH( 16 ),
    .CASE8( 8'h80 ),
    .din8_WIDTH( 16 ),
    .CASE9( 8'h90 ),
    .din9_WIDTH( 16 ),
    .CASE10( 8'hA0 ),
    .din10_WIDTH( 16 ),
    .CASE11( 8'hB0 ),
    .din11_WIDTH( 16 ),
    .CASE12( 8'hC0 ),
    .din12_WIDTH( 16 ),
    .CASE13( 8'hD0 ),
    .din13_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
sparsemux_29_8_16_1_1_U5138(
    .din0(proj_row_15_val),
    .din1(proj_row_31_val),
    .din2(proj_row_47_val),
    .din3(proj_row_63_val),
    .din4(proj_row_79_val),
    .din5(proj_row_95_val),
    .din6(proj_row_111_val),
    .din7(proj_row_127_val),
    .din8(proj_row_143_val),
    .din9(proj_row_159_val),
    .din10(proj_row_175_val),
    .din11(proj_row_191_val),
    .din12(proj_row_207_val),
    .din13(proj_row_223_val),
    .def(rhs_152_fu_3420_p29),
    .sel(ap_sig_allocacmp_hidden_base),
    .dout(rhs_152_fu_3420_p31)
);

SubbandRealtimeTopQ610Ip_mac_muladd_16s_16s_35s_35_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 35 ),
    .dout_WIDTH( 35 ))
mac_muladd_16s_16s_35s_35_3_1_U5139(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(rhs_reg_4280),
    .din1(RunSubbandRealtimeTopCoreQ610_stream_stream_ap_uint_const_int_bool_stream_la_1_q1),
    .din2(empty_fu_616),
    .ce(1'b1),
    .dout(grp_fu_3957_p3)
);

SubbandRealtimeTopQ610Ip_mac_muladd_16s_16s_35s_35_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 35 ),
    .dout_WIDTH( 35 ))
mac_muladd_16s_16s_35s_35_3_1_U5140(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(rhs_138_reg_4285),
    .din1(RunSubbandRealtimeTopCoreQ610_stream_stream_ap_uint_const_int_bool_stream_la_q1),
    .din2(empty_629_fu_620),
    .ce(1'b1),
    .dout(grp_fu_3966_p3)
);

SubbandRealtimeTopQ610Ip_mac_muladd_16s_16s_35s_35_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 35 ),
    .dout_WIDTH( 35 ))
mac_muladd_16s_16s_35s_35_3_1_U5141(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(rhs_139_reg_4300),
    .din1(RunSubbandRealtimeTopCoreQ610_stream_stream_ap_uint_const_int_bool_stream_la_1_q0),
    .din2(empty_630_fu_624),
    .ce(1'b1),
    .dout(grp_fu_3975_p3)
);

SubbandRealtimeTopQ610Ip_mac_muladd_16s_16s_35s_35_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 35 ),
    .dout_WIDTH( 35 ))
mac_muladd_16s_16s_35s_35_3_1_U5142(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(rhs_140_reg_4305),
    .din1(RunSubbandRealtimeTopCoreQ610_stream_stream_ap_uint_const_int_bool_stream_la_q0),
    .din2(empty_631_fu_628),
    .ce(1'b1),
    .dout(grp_fu_3984_p3)
);

SubbandRealtimeTopQ610Ip_mac_muladd_16s_16s_35s_35_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 35 ),
    .dout_WIDTH( 35 ))
mac_muladd_16s_16s_35s_35_3_1_U5143(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(rhs_141_reg_4310),
    .din1(RunSubbandRealtimeTopCoreQ610_stream_stream_ap_uint_const_int_bool_stream_la_1_q1),
    .din2(empty_632_fu_632),
    .ce(1'b1),
    .dout(grp_fu_3993_p3)
);

SubbandRealtimeTopQ610Ip_mac_muladd_16s_16s_35s_35_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 35 ),
    .dout_WIDTH( 35 ))
mac_muladd_16s_16s_35s_35_3_1_U5144(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(rhs_142_reg_4315),
    .din1(RunSubbandRealtimeTopCoreQ610_stream_stream_ap_uint_const_int_bool_stream_la_q1),
    .din2(empty_633_fu_636),
    .ce(1'b1),
    .dout(grp_fu_4002_p3)
);

SubbandRealtimeTopQ610Ip_mac_muladd_16s_16s_35s_35_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 35 ),
    .dout_WIDTH( 35 ))
mac_muladd_16s_16s_35s_35_3_1_U5145(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(rhs_143_reg_4320),
    .din1(RunSubbandRealtimeTopCoreQ610_stream_stream_ap_uint_const_int_bool_stream_la_1_q0),
    .din2(empty_634_fu_640),
    .ce(1'b1),
    .dout(grp_fu_4011_p3)
);

SubbandRealtimeTopQ610Ip_mac_muladd_16s_16s_35s_35_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 35 ),
    .dout_WIDTH( 35 ))
mac_muladd_16s_16s_35s_35_3_1_U5146(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(rhs_144_reg_4325),
    .din1(RunSubbandRealtimeTopCoreQ610_stream_stream_ap_uint_const_int_bool_stream_la_q0),
    .din2(empty_635_fu_644),
    .ce(1'b1),
    .dout(grp_fu_4020_p3)
);

SubbandRealtimeTopQ610Ip_mac_muladd_16s_16s_35s_35_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 35 ),
    .dout_WIDTH( 35 ))
mac_muladd_16s_16s_35s_35_3_1_U5147(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(rhs_145_reg_4330),
    .din1(RunSubbandRealtimeTopCoreQ610_stream_stream_ap_uint_const_int_bool_stream_la_1_q1),
    .din2(empty_636_fu_648),
    .ce(1'b1),
    .dout(grp_fu_4029_p3)
);

SubbandRealtimeTopQ610Ip_mac_muladd_16s_16s_35s_35_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 35 ),
    .dout_WIDTH( 35 ))
mac_muladd_16s_16s_35s_35_3_1_U5148(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(rhs_146_reg_4335),
    .din1(RunSubbandRealtimeTopCoreQ610_stream_stream_ap_uint_const_int_bool_stream_la_q1),
    .din2(empty_637_fu_652),
    .ce(1'b1),
    .dout(grp_fu_4038_p3)
);

SubbandRealtimeTopQ610Ip_mac_muladd_16s_16s_35s_35_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 35 ),
    .dout_WIDTH( 35 ))
mac_muladd_16s_16s_35s_35_3_1_U5149(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(rhs_147_reg_4340),
    .din1(RunSubbandRealtimeTopCoreQ610_stream_stream_ap_uint_const_int_bool_stream_la_1_q0),
    .din2(empty_638_fu_656),
    .ce(1'b1),
    .dout(grp_fu_4047_p3)
);

SubbandRealtimeTopQ610Ip_mac_muladd_16s_16s_35s_35_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 35 ),
    .dout_WIDTH( 35 ))
mac_muladd_16s_16s_35s_35_3_1_U5150(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(rhs_148_reg_4345),
    .din1(RunSubbandRealtimeTopCoreQ610_stream_stream_ap_uint_const_int_bool_stream_la_q0),
    .din2(empty_639_fu_660),
    .ce(1'b1),
    .dout(grp_fu_4056_p3)
);

SubbandRealtimeTopQ610Ip_mac_muladd_16s_16s_35s_35_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 35 ),
    .dout_WIDTH( 35 ))
mac_muladd_16s_16s_35s_35_3_1_U5151(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(rhs_149_reg_4350),
    .din1(RunSubbandRealtimeTopCoreQ610_stream_stream_ap_uint_const_int_bool_stream_la_1_q1),
    .din2(empty_640_fu_664),
    .ce(1'b1),
    .dout(grp_fu_4065_p3)
);

SubbandRealtimeTopQ610Ip_mac_muladd_16s_16s_35s_35_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 35 ),
    .dout_WIDTH( 35 ))
mac_muladd_16s_16s_35s_35_3_1_U5152(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(rhs_150_reg_4355),
    .din1(RunSubbandRealtimeTopCoreQ610_stream_stream_ap_uint_const_int_bool_stream_la_q1),
    .din2(empty_641_fu_668),
    .ce(1'b1),
    .dout(grp_fu_4074_p3)
);

SubbandRealtimeTopQ610Ip_mac_muladd_16s_16s_35s_35_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 35 ),
    .dout_WIDTH( 35 ))
mac_muladd_16s_16s_35s_35_3_1_U5153(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(rhs_151_reg_4360),
    .din1(RunSubbandRealtimeTopCoreQ610_stream_stream_ap_uint_const_int_bool_stream_la_1_q0),
    .din2(empty_642_fu_672),
    .ce(1'b1),
    .dout(grp_fu_4083_p3)
);

SubbandRealtimeTopQ610Ip_mac_muladd_16s_16s_35s_35_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 35 ),
    .dout_WIDTH( 35 ))
mac_muladd_16s_16s_35s_35_3_1_U5154(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(rhs_152_reg_4365),
    .din1(RunSubbandRealtimeTopCoreQ610_stream_stream_ap_uint_const_int_bool_stream_la_q0),
    .din2(empty_643_fu_676),
    .ce(1'b1),
    .dout(grp_fu_4092_p3)
);

SubbandRealtimeTopQ610Ip_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage2),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage2)) begin
            ap_enable_reg_pp0_iter0_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage2_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        empty_629_fu_620 <= 35'd0;
    end else if (((icmp_ln4474_reg_4256 == 1'd1) & (1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        empty_629_fu_620 <= grp_fu_3966_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        empty_630_fu_624 <= 35'd0;
    end else if (((icmp_ln4474_reg_4256 == 1'd1) & (1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        empty_630_fu_624 <= grp_fu_3975_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        empty_631_fu_628 <= 35'd0;
    end else if (((icmp_ln4474_reg_4256 == 1'd1) & (1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        empty_631_fu_628 <= grp_fu_3984_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            empty_632_fu_632 <= 35'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            empty_632_fu_632 <= grp_fu_3993_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            empty_633_fu_636 <= 35'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            empty_633_fu_636 <= grp_fu_4002_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            empty_634_fu_640 <= 35'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            empty_634_fu_640 <= grp_fu_4011_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            empty_635_fu_644 <= 35'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            empty_635_fu_644 <= grp_fu_4020_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        empty_636_fu_648 <= 35'd0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        empty_636_fu_648 <= grp_fu_4029_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        empty_637_fu_652 <= 35'd0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        empty_637_fu_652 <= grp_fu_4038_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        empty_638_fu_656 <= 35'd0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        empty_638_fu_656 <= grp_fu_4047_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        empty_639_fu_660 <= 35'd0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        empty_639_fu_660 <= grp_fu_4056_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        empty_640_fu_664 <= 35'd0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        empty_640_fu_664 <= grp_fu_4065_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        empty_641_fu_668 <= 35'd0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        empty_641_fu_668 <= grp_fu_4074_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        empty_642_fu_672 <= 35'd0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        empty_642_fu_672 <= grp_fu_4083_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        empty_643_fu_676 <= 35'd0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        empty_643_fu_676 <= grp_fu_4092_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        empty_fu_616 <= 35'd0;
    end else if (((icmp_ln4474_reg_4256 == 1'd1) & (1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        empty_fu_616 <= grp_fu_3957_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln4474_fu_2386_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            hidden_index_fu_680 <= add_ln4474_fu_3484_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            hidden_index_fu_680 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln4474_reg_4256 <= icmp_ln4474_fu_2386_p2;
        lshr_ln_reg_4260 <= {{ap_sig_allocacmp_hidden_base[7:1]}};
        rhs_138_reg_4285 <= rhs_138_fu_2492_p31;
        rhs_139_reg_4300 <= rhs_139_fu_2588_p31;
        rhs_140_reg_4305 <= rhs_140_fu_2652_p31;
        rhs_141_reg_4310 <= rhs_141_fu_2716_p31;
        rhs_142_reg_4315 <= rhs_142_fu_2780_p31;
        rhs_143_reg_4320 <= rhs_143_fu_2844_p31;
        rhs_144_reg_4325 <= rhs_144_fu_2908_p31;
        rhs_145_reg_4330 <= rhs_145_fu_2972_p31;
        rhs_146_reg_4335 <= rhs_146_fu_3036_p31;
        rhs_147_reg_4340 <= rhs_147_fu_3100_p31;
        rhs_148_reg_4345 <= rhs_148_fu_3164_p31;
        rhs_149_reg_4350 <= rhs_149_fu_3228_p31;
        rhs_150_reg_4355 <= rhs_150_fu_3292_p31;
        rhs_151_reg_4360 <= rhs_151_fu_3356_p31;
        rhs_152_reg_4365 <= rhs_152_fu_3420_p31;
        rhs_reg_4280 <= rhs_fu_2428_p31;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            RunSubbandRealtimeTopCoreQ610_stream_stream_ap_uint_const_int_bool_stream_la_1_address0 = zext_ln4480_22_fu_3750_p1;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            RunSubbandRealtimeTopCoreQ610_stream_stream_ap_uint_const_int_bool_stream_la_1_address0 = zext_ln4480_16_fu_3652_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            RunSubbandRealtimeTopCoreQ610_stream_stream_ap_uint_const_int_bool_stream_la_1_address0 = zext_ln4480_10_fu_3566_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            RunSubbandRealtimeTopCoreQ610_stream_stream_ap_uint_const_int_bool_stream_la_1_address0 = zext_ln4480_4_fu_2572_p1;
        end else begin
            RunSubbandRealtimeTopCoreQ610_stream_stream_ap_uint_const_int_bool_stream_la_1_address0 = 'bx;
        end
    end else begin
        RunSubbandRealtimeTopCoreQ610_stream_stream_ap_uint_const_int_bool_stream_la_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            RunSubbandRealtimeTopCoreQ610_stream_stream_ap_uint_const_int_bool_stream_la_1_address1 = zext_ln4480_19_fu_3721_p1;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            RunSubbandRealtimeTopCoreQ610_stream_stream_ap_uint_const_int_bool_stream_la_1_address1 = zext_ln4480_13_fu_3623_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            RunSubbandRealtimeTopCoreQ610_stream_stream_ap_uint_const_int_bool_stream_la_1_address1 = zext_ln4480_7_fu_3537_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            RunSubbandRealtimeTopCoreQ610_stream_stream_ap_uint_const_int_bool_stream_la_1_address1 = zext_ln4480_1_fu_2412_p1;
        end else begin
            RunSubbandRealtimeTopCoreQ610_stream_stream_ap_uint_const_int_bool_stream_la_1_address1 = 'bx;
        end
    end else begin
        RunSubbandRealtimeTopCoreQ610_stream_stream_ap_uint_const_int_bool_stream_la_1_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        RunSubbandRealtimeTopCoreQ610_stream_stream_ap_uint_const_int_bool_stream_la_1_ce0 = 1'b1;
    end else begin
        RunSubbandRealtimeTopCoreQ610_stream_stream_ap_uint_const_int_bool_stream_la_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        RunSubbandRealtimeTopCoreQ610_stream_stream_ap_uint_const_int_bool_stream_la_1_ce1 = 1'b1;
    end else begin
        RunSubbandRealtimeTopCoreQ610_stream_stream_ap_uint_const_int_bool_stream_la_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            RunSubbandRealtimeTopCoreQ610_stream_stream_ap_uint_const_int_bool_stream_la_address0 = zext_ln4480_23_fu_3760_p1;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            RunSubbandRealtimeTopCoreQ610_stream_stream_ap_uint_const_int_bool_stream_la_address0 = zext_ln4480_17_fu_3662_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            RunSubbandRealtimeTopCoreQ610_stream_stream_ap_uint_const_int_bool_stream_la_address0 = zext_ln4480_11_fu_3576_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            RunSubbandRealtimeTopCoreQ610_stream_stream_ap_uint_const_int_bool_stream_la_address0 = zext_ln4480_5_fu_2583_p1;
        end else begin
            RunSubbandRealtimeTopCoreQ610_stream_stream_ap_uint_const_int_bool_stream_la_address0 = 'bx;
        end
    end else begin
        RunSubbandRealtimeTopCoreQ610_stream_stream_ap_uint_const_int_bool_stream_la_address0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            RunSubbandRealtimeTopCoreQ610_stream_stream_ap_uint_const_int_bool_stream_la_address1 = zext_ln4480_20_fu_3731_p1;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            RunSubbandRealtimeTopCoreQ610_stream_stream_ap_uint_const_int_bool_stream_la_address1 = zext_ln4480_14_fu_3633_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            RunSubbandRealtimeTopCoreQ610_stream_stream_ap_uint_const_int_bool_stream_la_address1 = zext_ln4480_8_fu_3547_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            RunSubbandRealtimeTopCoreQ610_stream_stream_ap_uint_const_int_bool_stream_la_address1 = zext_ln4480_2_fu_2423_p1;
        end else begin
            RunSubbandRealtimeTopCoreQ610_stream_stream_ap_uint_const_int_bool_stream_la_address1 = 'bx;
        end
    end else begin
        RunSubbandRealtimeTopCoreQ610_stream_stream_ap_uint_const_int_bool_stream_la_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        RunSubbandRealtimeTopCoreQ610_stream_stream_ap_uint_const_int_bool_stream_la_ce0 = 1'b1;
    end else begin
        RunSubbandRealtimeTopCoreQ610_stream_stream_ap_uint_const_int_bool_stream_la_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        RunSubbandRealtimeTopCoreQ610_stream_stream_ap_uint_const_int_bool_stream_la_ce1 = 1'b1;
    end else begin
        RunSubbandRealtimeTopCoreQ610_stream_stream_ap_uint_const_int_bool_stream_la_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln4474_reg_4256 == 1'd0) & (1'b0 == ap_block_pp0_stage2_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_condition_exit_pp0_iter0_stage2 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage2 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b0)) begin
        ap_idle_pp0_1to1 = 1'b1;
    end else begin
        ap_idle_pp0_1to1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_hidden_base = 8'd0;
    end else begin
        ap_sig_allocacmp_hidden_base = hidden_index_fu_680;
    end
end

always @ (*) begin
    if (((icmp_ln4474_reg_4256 == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        p_out10_ap_vld = 1'b1;
    end else begin
        p_out10_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln4474_reg_4256 == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        p_out11_ap_vld = 1'b1;
    end else begin
        p_out11_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln4474_reg_4256 == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        p_out12_ap_vld = 1'b1;
    end else begin
        p_out12_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln4474_reg_4256 == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        p_out13_ap_vld = 1'b1;
    end else begin
        p_out13_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln4474_reg_4256 == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        p_out14_ap_vld = 1'b1;
    end else begin
        p_out14_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln4474_reg_4256 == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        p_out15_ap_vld = 1'b1;
    end else begin
        p_out15_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln4474_reg_4256 == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        p_out1_ap_vld = 1'b1;
    end else begin
        p_out1_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln4474_reg_4256 == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        p_out2_ap_vld = 1'b1;
    end else begin
        p_out2_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln4474_reg_4256 == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        p_out3_ap_vld = 1'b1;
    end else begin
        p_out3_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln4474_reg_4256 == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        p_out4_ap_vld = 1'b1;
    end else begin
        p_out4_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln4474_reg_4256 == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        p_out5_ap_vld = 1'b1;
    end else begin
        p_out5_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln4474_reg_4256 == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        p_out6_ap_vld = 1'b1;
    end else begin
        p_out6_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln4474_reg_4256 == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        p_out7_ap_vld = 1'b1;
    end else begin
        p_out7_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln4474_reg_4256 == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        p_out8_ap_vld = 1'b1;
    end else begin
        p_out8_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln4474_reg_4256 == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        p_out9_ap_vld = 1'b1;
    end else begin
        p_out9_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln4474_reg_4256 == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        p_out_ap_vld = 1'b1;
    end else begin
        p_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to1 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b1 == ap_condition_exit_pp0_iter0_stage2)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln4474_fu_3484_p2 = (ap_sig_allocacmp_hidden_base + 8'd16);

assign add_ln4480_16_fu_2406_p2 = (sub_ln4480_1 + zext_ln4480_fu_2402_p1);

assign add_ln4480_17_fu_2417_p2 = (sub_ln4480 + zext_ln4480_fu_2402_p1);

assign add_ln4480_18_fu_2566_p2 = (sub_ln4480_1 + zext_ln4480_3_fu_2562_p1);

assign add_ln4480_19_fu_2577_p2 = (sub_ln4480 + zext_ln4480_3_fu_2562_p1);

assign add_ln4480_20_fu_3532_p2 = (sub_ln4480_1 + zext_ln4480_6_fu_3528_p1);

assign add_ln4480_21_fu_3542_p2 = (sub_ln4480 + zext_ln4480_6_fu_3528_p1);

assign add_ln4480_22_fu_3561_p2 = (sub_ln4480_1 + zext_ln4480_9_fu_3557_p1);

assign add_ln4480_23_fu_3571_p2 = (sub_ln4480 + zext_ln4480_9_fu_3557_p1);

assign add_ln4480_24_fu_3618_p2 = (sub_ln4480_1 + zext_ln4480_12_fu_3614_p1);

assign add_ln4480_25_fu_3628_p2 = (sub_ln4480 + zext_ln4480_12_fu_3614_p1);

assign add_ln4480_26_fu_3647_p2 = (sub_ln4480_1 + zext_ln4480_15_fu_3643_p1);

assign add_ln4480_27_fu_3657_p2 = (sub_ln4480 + zext_ln4480_15_fu_3643_p1);

assign add_ln4480_28_fu_3716_p2 = (sub_ln4480_1 + zext_ln4480_18_fu_3712_p1);

assign add_ln4480_29_fu_3726_p2 = (sub_ln4480 + zext_ln4480_18_fu_3712_p1);

assign add_ln4480_30_fu_3745_p2 = (sub_ln4480_1 + zext_ln4480_21_fu_3741_p1);

assign add_ln4480_31_fu_3755_p2 = (sub_ln4480 + zext_ln4480_21_fu_3741_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_subdone = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage2;

assign icmp_ln4474_fu_2386_p2 = ((ap_sig_allocacmp_hidden_base < 8'd224) ? 1'b1 : 1'b0);

assign lshr_ln_fu_2392_p4 = {{ap_sig_allocacmp_hidden_base[7:1]}};

assign or_ln4480_1_fu_3523_p2 = (lshr_ln_reg_4260 | 7'd2);

assign or_ln4480_2_fu_3552_p2 = (lshr_ln_reg_4260 | 7'd3);

assign or_ln4480_3_fu_3609_p2 = (lshr_ln_reg_4260 | 7'd4);

assign or_ln4480_4_fu_3638_p2 = (lshr_ln_reg_4260 | 7'd5);

assign or_ln4480_5_fu_3707_p2 = (lshr_ln_reg_4260 | 7'd6);

assign or_ln4480_6_fu_3736_p2 = (lshr_ln_reg_4260 | 7'd7);

assign or_ln4480_fu_2556_p2 = (lshr_ln_fu_2392_p4 | 7'd1);

assign p_out = empty_643_fu_676;

assign p_out1 = empty_642_fu_672;

assign p_out10 = empty_633_fu_636;

assign p_out11 = empty_632_fu_632;

assign p_out12 = empty_631_fu_628;

assign p_out13 = empty_630_fu_624;

assign p_out14 = empty_629_fu_620;

assign p_out15 = empty_fu_616;

assign p_out2 = empty_641_fu_668;

assign p_out3 = empty_640_fu_664;

assign p_out4 = empty_639_fu_660;

assign p_out5 = empty_638_fu_656;

assign p_out6 = empty_637_fu_652;

assign p_out7 = empty_636_fu_648;

assign p_out8 = empty_635_fu_644;

assign p_out9 = empty_634_fu_640;

assign rhs_138_fu_2492_p29 = 'bx;

assign rhs_139_fu_2588_p29 = 'bx;

assign rhs_140_fu_2652_p29 = 'bx;

assign rhs_141_fu_2716_p29 = 'bx;

assign rhs_142_fu_2780_p29 = 'bx;

assign rhs_143_fu_2844_p29 = 'bx;

assign rhs_144_fu_2908_p29 = 'bx;

assign rhs_145_fu_2972_p29 = 'bx;

assign rhs_146_fu_3036_p29 = 'bx;

assign rhs_147_fu_3100_p29 = 'bx;

assign rhs_148_fu_3164_p29 = 'bx;

assign rhs_149_fu_3228_p29 = 'bx;

assign rhs_150_fu_3292_p29 = 'bx;

assign rhs_151_fu_3356_p29 = 'bx;

assign rhs_152_fu_3420_p29 = 'bx;

assign rhs_fu_2428_p29 = 'bx;

assign zext_ln4480_10_fu_3566_p1 = add_ln4480_22_fu_3561_p2;

assign zext_ln4480_11_fu_3576_p1 = add_ln4480_23_fu_3571_p2;

assign zext_ln4480_12_fu_3614_p1 = or_ln4480_3_fu_3609_p2;

assign zext_ln4480_13_fu_3623_p1 = add_ln4480_24_fu_3618_p2;

assign zext_ln4480_14_fu_3633_p1 = add_ln4480_25_fu_3628_p2;

assign zext_ln4480_15_fu_3643_p1 = or_ln4480_4_fu_3638_p2;

assign zext_ln4480_16_fu_3652_p1 = add_ln4480_26_fu_3647_p2;

assign zext_ln4480_17_fu_3662_p1 = add_ln4480_27_fu_3657_p2;

assign zext_ln4480_18_fu_3712_p1 = or_ln4480_5_fu_3707_p2;

assign zext_ln4480_19_fu_3721_p1 = add_ln4480_28_fu_3716_p2;

assign zext_ln4480_1_fu_2412_p1 = add_ln4480_16_fu_2406_p2;

assign zext_ln4480_20_fu_3731_p1 = add_ln4480_29_fu_3726_p2;

assign zext_ln4480_21_fu_3741_p1 = or_ln4480_6_fu_3736_p2;

assign zext_ln4480_22_fu_3750_p1 = add_ln4480_30_fu_3745_p2;

assign zext_ln4480_23_fu_3760_p1 = add_ln4480_31_fu_3755_p2;

assign zext_ln4480_2_fu_2423_p1 = add_ln4480_17_fu_2417_p2;

assign zext_ln4480_3_fu_2562_p1 = or_ln4480_fu_2556_p2;

assign zext_ln4480_4_fu_2572_p1 = add_ln4480_18_fu_2566_p2;

assign zext_ln4480_5_fu_2583_p1 = add_ln4480_19_fu_2577_p2;

assign zext_ln4480_6_fu_3528_p1 = or_ln4480_1_fu_3523_p2;

assign zext_ln4480_7_fu_3537_p1 = add_ln4480_20_fu_3532_p2;

assign zext_ln4480_8_fu_3547_p1 = add_ln4480_21_fu_3542_p2;

assign zext_ln4480_9_fu_3557_p1 = or_ln4480_2_fu_3552_p2;

assign zext_ln4480_fu_2402_p1 = lshr_ln_fu_2392_p4;

endmodule //SubbandRealtimeTopQ610Ip_p_anonymous_namespace_ProjectionDotProductRealtimeRowFixedDspQ610_Pipeline_VITIS_s
